	ct_dialog_captcha: "{term:entercaptcha_tip}",
	ct_dialog_contactwowhead: "{term:contactwowhead}",
	ct_dialog_description: "{term:description}",
	ct_dialog_desc_caption: "{term:bespecific_tip}",
	ct_dialog_email: "{term:emailaddress_colon}",
	ct_dialog_email_caption: "{term:emailcontact_tip}",
	ct_dialog_optional: "{term:optional}",
	ct_dialog_reason: "{term:reason_colon}",
	ct_dialog_relatedurl: "{term:relatedurl_colon}",
	ct_dialog_currenturl: "{term:currenturl_colon}",
	ct_dialog_report: "{term:report}",
	ct_dialog_reportchar: "{term:reportcharacter}",
	ct_dialog_reportcomment: "{term:reportcomment_format}",
	ct_dialog_reportpost: "{term:reportpost_format}",
	ct_dialog_reportscreen: "{term:screenshotreport_format}",
	ct_dialog_reportvideo: "{term:videoreport_format}",
	ct_dialog_reporttopic: "{term:reporttopic_format}",
	ct_dialog_thanks: "{term:contactthanks_tip}",
	ct_dialog_thanks_user: "{term:contactreceived_tip}",
	ct_dialog_error_captcha: "{term:captchaerror_tip}",
	ct_dialog_error_desc: "{term:shortdescription_tip}",
	ct_dialog_error_email: "{term:entervalidemail_tip}",
	ct_dialog_error_emaillen: "{term:emailaddresslength_tip}",
	ct_dialog_error_reason: "{term:contactreason_tip}",
	ct_dialog_error_relatedurl: "{term:relatedurl_tip}",
	ct_dialog_error_invalidurl: "{term:entervalidurl_tip}",


/*
	ct_dialog_captcha: "Please enter the code above: ",
	ct_dialog_contactwowhead: "Contact Wowhead",
	ct_dialog_description: "Description",
	ct_dialog_desc_caption: "Please be as specific as possible.",
	ct_dialog_email: "Email address: ",
	ct_dialog_email_caption: "Only if you want to be contacted.",
	ct_dialog_optional: "Optional",
	ct_dialog_reason: "Reason: ",
	ct_dialog_relatedurl: "Related URL: ",
	ct_dialog_currenturl: "Current URL: ",
	ct_dialog_report: "Report",
	ct_dialog_reportchar: "Report Character",
	ct_dialog_reportcomment: "Report Comment by $1",
	ct_dialog_reportpost: "Report Post by $1",
	ct_dialog_reportscreen: "Report Screenshot from $1",
	ct_dialog_reportvideo: "Report Video from $1",
	ct_dialog_reporttopic: "Report Topic by $1",
	ct_dialog_thanks: "Your message has been received. Thanks for contacting us!",
	ct_dialog_thanks_user: "Your message has been received, $1. Thanks for contacting us!",
	ct_dialog_error_captcha: "The CAPTCHA you entered is invalid. Please try again.",
	ct_dialog_error_desc: "Please provide a thorough description, but not too long.",
	ct_dialog_error_email: "Please enter a valid email address.",
	ct_dialog_error_emaillen: "Please enter an email address with less than 100 characters.",
	ct_dialog_error_reason: "Please choose a reason for contacting us.",
	ct_dialog_error_relatedurl: "Please provide a related URL with less than 250 characters.",
	ct_dialog_error_invalidurl: "Please enter a valid URL.",
*/