	and: "{term:and_lc}",
	comma: "{term:comma_punct}",
	ellipsis: "{term:ellipsis_punct}",
	dash: "{term:dash_punct}",
	hyphen: "{term:hyphen_punct}",
	colon: "{term:colon_punct}",
	qty: "{term:_paren}",
	date: "{term:date}",
	date_colon: "{term:date_colon}",
	date_on: "{term:on_lc}",
	date_ago: "{term:ago2_format}",
	date_at: "{term:at_lc}",
	date_simple: "{term:date3_format}",
	date_months: ["{term:january}", "{term:february}", "{term:march}", "{term:april}", "{term:may}", "{term:june}", "{term:july}", "{term:august}", "{term:september}", "{term:october}", "{term:november}", "{term:december}"],
	abilities: "{term:abilities}",
	armor: "{term:armor}",
	author: "{term:author}",
	battlegroup: "{term:battlegroup}",
	category: "{term:category}",
	classes: "{term:classes}",
	classs: "{term:class}",
	close: "{term:close}",
	completed: "{term:completed}",
	contactus: "{term:contactus_stc}",
	cost: "{term:cost}",
	count: "{term:count}",
	daily: "{term:daily}",
	weekly: "{term:weekly}",
	damage: "{term:damage}",
	diet: "{term:diet}",
	dps: "{term:dps}",
	earned: "{term:earned}",
	enchant: "{term:enchant}",
	faction: "{term:faction}",
	gains: "{term:gains}",
	gender: "{term:gender}",
	gems: "{term:gems}",
	gearscore: "{term:gear}",
	gearscore_real: "{term:gearscore_stc}",
	glyphtype: "{term:glyphtype_stc}",
	guildlevel: "{term:guildlevel}",
	group: "{term:group}",
	guild: "{term:guild}",
	guildleader: "{term:guildleader}",
	guildrank: "{term:guildrank}",
	health: "{term:health}",
	heroiclevel: "{term:heroiclevel_stc}",
	icon: "{term:icon}",
	instancetype: "{term:instancetype_stc}",
	lastpost: "{term:lastpost_stc}",
	level: "{term:level}",
	location: "{term:location}",
	losses: "{term:losses}",
	members: "{term:members}",
	name: "{term:name}",
	players: "{term:players}",
	race: "{term:race}",
	races: "{term:races}",
	rankno: "{term:rank_format}",
	rating: "{term:rating}",
	react: "{term:react}",
	realm: "{term:realm}",
	reagents: "{term:reagents}",
	region: "{term:region}",
	rep: "{term:reputation_abbrev}",
	req: "{term:requires_abbrev}",
	reputation: "{term:reputation}",
	rewards: "{term:rewards}",
	petfamily: "{term:petfamily_stc}",
	pieces: "{term:pieces}",
	points: "{term:points}",
	posted: "{term:posted}",
	premiumupgrade: "{term:premiumupgrade}",
	preview: "{term:preview}",
	privateprofile: "{term:private}",
	prize: "{term:prize}",
	profiler: "{term:profiler}",
	progress: "{term:progress}",
	publicprofile: "{term:public}",
	replies: "{term:replies}",
	report: "{term:report}",
	report_tooltip: "{term:reportingoptions_tip}",
	school: "{term:school}",
	score: "{term:score}",
	settings: "{term:settings}",
	side: "{term:side}",
	signout: "{term:signout}",
	sockets: "{term:sockets}",
	source: "{term:source}",
	skill: "{term:skill}",
	skin: "{term:skin}",
	slot: "{term:slot}",
	slots: "{term:slots}",
	smartloot: "{term:smartloot_stc}",
	speed: "{term:speed}",
	stack: "{term:stack}",
	standing: "{term:standing}",
	stock: "{term:stock}",
	statistic: "{term:statistic}",
	subject: "{term:subject}",
	submit: "{term:submit}",
	talents: "{term:talents}",
	territory: "{term:territory}",
	tier: "{term:tier}",
	topics: "{term:topics}",
	tp: "{term:talentpoint_abbrev}",
	type: "{term:type}",
	user: "{term:user}",
	views: "{term:views}",
	userpage: "{term:userpage}",
	wins: "{term:wins}",
	when: "{term:when}",
	today: "{term:today_lc}",
	yesterday: "{term:yesterday_lc}",
	dayatnoon: "{term:dayatnoon_format}",
	dayatmidnight: "{term:dayatmidnight_format}",
	dayatam: "{term:dayatam_format}",
	dayatpm: "{term:dayatpm_format}",
	male: "{term:male}",
	female: "{term:female}",
	source_zonedrop: "{term:zonedrop}",
	source_quests: "{term:quests}",
	source_vendors: "{term:vendors}",
	infobox_noneyet: "{term:noneyet_format}",
	infobox_submitone: "{term:submitone_stc}",
	infobox_suggestone: "{term:suggestone_stc}",
	infobox_showall: "{term:showall_format}",
	lvclass_hero: "{term:heroclass_stc}",
	lvcomment_add: "{term:addyourcomment}",
	lvcomment_sort: "{term:sortby_colon}",
	lvcomment_sortdate: "{term:date}",
	lvcomment_sortrating: "{term:highestrated_stc}",
	lvcomment_patchfilter: "{term:filterbypatch_colon}",
	lvcomment_by: "{term:by}",
	lvcomment_patch: "{term:patch_format}",
	lvcomment_show: "{term:showcomment_stc}",
	lvcomment_hide: "{term:hidecomment_stc}",
	lvcomment_rating: "{term:rating_colon}",
	lvcomment_lastedit: "{term:lasteditedby_stc}",
	lvcomment_nedits: "{term:editcount_format}",
	lvcomment_edit: "{term:edit}",
	lvcomment_delete: "{term:delete}",
	lvcomment_detach: "{term:detach}",
	lvcomment_reply: "{term:reply}",
	lvcomment_report: "{term:report}",
	lvcomment_reported: "{term:reported}",
	lvcomment_deleted: "{term:deleted_paren}",
	lvcomment_purged: "{term:purged_paren}",
	lvdrop_outof: "{term:outof_format}",
	lvitem_dd: "{term:dd_format}",
	lvitem_normal: "{term:normal_abbrev}",
	lvitem_heroic: "{term:heroic_abbrev}",
	lvitem_raid10: "10",
	lvitem_raid25: "25",
	lvitem_heroicitem: "{term:heroic}",
	lvitem_vendorin: "{term:vendorin}",
	lvitem_reqlevel: "{term:requires_abbrev}",
	lvnpc_alliance: "{term:alliance_abbrev}",
	lvnpc_horde: "{term:heroic_abbrev}",
	premium_title: "{term:wowheadpatron}",
	lvquest_daily: "{term:daily_format}",
	lvquest_weekly: "{term:weekly_format}",
	lvquest_pickone: "{term:pickone_colon}",
	lvquest_alsoget: "{term:alsoget_colon}",
	lvquest_xp: "{term:xp_format}",
	lvquest_removed: "{term:removed}",
	lvzone_xman: "{term:dungeonplayer_format}",
	lvzone_xvx: "{term:arenateam_format}",
	lvpet_exotic: "{term:exotic}",
	lvpage_of: "{term:of_lc}",
	lvpage_first: "{term:first}",
	lvpage_previous: "{term:previous}",
	lvpage_next: "{term:next}",
	lvpage_last: "{term:last}",
	lvscreenshot_submit: "{term:submitascreenshot_stc}",
	lvscreenshot_from: "{term:from}",
	lvscreenshot_hires: "{term:view}",
	lvscreenshot_hires2: "{term:highresolution_format}",
	lvvideo_suggest: "{term:suggestavideo_stc}",
	lvvideo_from: "{term:from}",
	lvnodata: "{term:nodata_tip}",
	lvnodata2: "{term:nomatches_tip}",
	lvnodata_co1: "{term:nocomments_tip}",
	lvnodata_co2: "{term:commentfirst_tip}",
	lvnodata_co3: "{term:commentlogin_tip}",
	lvnodata_ss1: "{term:noscreenshots_tip}",
	lvnodata_ss2: "{term:firstscreenshot_tip}",
	lvnodata_ss3: "{term:screenshotlogin_tip}",
	lvnodata_vi1: "{term:novideos_tip}",
	lvnodata_vi2: "{term:videofirst_tip}",
	lvnodata_vi3: "{term:videologin_tip}",
	lvnote_tryfiltering: "{term:searchfilter_tip}",
	lvnote_trynarrowing: "{term:searchnarrow_tip}",
	lvnote_upgradesfor: "{term:findingupgrades_tip}",
	lvnote_itemsfound: "{term:itemsfounddisplayed_format}",
	lvnote_itemsetsfound: "{term:itemsetsfounddisplayed_format}",
	lvnote_npcsfound: "{term:npcsfounddisplayed_format}",
	lvnote_objectsfound: "{term:objectsfounddisplayed_format}",
	lvnote_questsfound: "{term:questsfounddisplayed_format}",
	lvnote_questsind: "{term:questindicator_tip}",
	lvnote_spellsfound: "{term:spellsfounddisplayed_format}",
	lvnote_skillsfound: "{term:skillsfounddisplayed_format}",
	lvnote_abilitiesfound: "{term:abilitiesfounddisplayed_format}",
	lvnote_talentsfound: "{term:talentsfounddisplayed_format}",
	lvnote_professionfound: "{term:professionsfounddisplayed_format}",
	lvnote_mountsfound: "{term:mountsfounddisplayed_format}",
	lvnote_zonesfound: "{term:zonesfounddisplayed_format}",
	lvnote_companionsfound: "{term:companionsfounddisplayed_format}",
	lvnote_factionsfound: "{term:factionsfounddisplayed_format}",
	lvnote_petsfound: "{term:petsfounddisplayed_format}",
	lvnote_achievementsfound: "{term:achievementsfounddisplayed_forma}",
	lvnote_achievementsind: "{term:achievementsindicator_tip}",
	lvnote_statisticsfound: "{term:statisticsfounddisplayed_format}",
	lvnote_charactersfound: "{term:totalcharacters_format}",
	lvnote_charactersfound2: "{term:characterstotalmatching_format}",
	lvnote_guildsfound: "{term:totalguilds_format}",
	lvnote_guildsfound2: "{term:totalguildsmatching_format}",
	lvnote_arenateamsfound: "{term:totalarenateams_format}",
	lvnote_arenateamsfound2: "{term:arenateamstotalmatching_format}",
	lvnote_createafilter: "{term:createafilter_format}",
	lvnote_filterresults: "{term:filterresults_format}",
	lvnote_questgivers: "{term:questgivers_tip}",
	lvnote_allpets: "{term:passivepetskills_tip}",
	lvnote_zonequests: "{term:zonequests_tip}",
	lvnote_crafteditems: "{term:crafteditems_tip}",
	lvnote_viewmoreslot: "{term:moreresultslot_tip}",
	lvnote_viewmorelevel: "{term:moreitemlevel_tip}",
	lvnote_itemdisenchanting: "{term:itemdisenchanted_format}",
	lvnote_itemdropsinnormalonly: "{term:dropsinnormalonly_tip}",
	lvnote_itemdropsinheroiconly: "{term:dropsinheroiconly_tip}",
	lvnote_itemdropsinnormalheroic: "{term:dropsinboth_tip}",
	lvnote_itemdropsinnormal10only: "{term:dropsinnormal10only_tip}",
	lvnote_itemdropsinnormal25only: "{term:dropsinnormal25only_tip}",
	lvnote_itemdropsinheroic10only: "{term:dropsinheroic10only_tip}",
	lvnote_itemdropsinheroic25only: "{term:dropsinheroic25only_tip}",
	lvnote_itemmilling: "{term:herbmilled_format}",
	lvnote_itemopening: "{term:itemopened_format}",
	lvnote_itemprospecting: "{term:oreprospected_format}",
	lvnote_npcdrops: "{term:npclooted_format}",
	lvnote_npcdropsnormal: "{term:npclootednormal_format}",
	lvnote_npcdropsheroic: "{term:npclootedheroic_format}",
	lvnote_npcdropsnormalX: "{term:npclootednormalx_format}",
	lvnote_npcdropsheroicX: "{term:npclootedheroicx_format}",
	lvnote_npcobject: "{term:npcobjectopened_format}",
	lvnote_npcobjectnormal: "{term:npcobjectopenednormal_format}",
	lvnote_npcobjectheroic: "{term:npcobjectopenedheroic_format}",
	lvnote_npcobjectnormalX: "{term:npcobjectopenednormalx_format}",
	lvnote_npcobjectheroicX: "{term:npcobjectopenedheroicx_format}",
	lvnote_npcherbgathering: "{term:npcherbgathered_format}",
	lvnote_npcmining: "{term:npcmined_format}",
	lvnote_npcpickpocketing: "{term:npcpickpocketed_format}",
	lvnote_npcskinning: "{term:npcskinned_format}",
	lvnote_objectherbgathering: "{term:herbgathered_format}",
	lvnote_objectmining: "{term:veinmined_format}",
	lvnote_objectopening: "{term:objectopened_format}",
	lvnote_objectopeningnormal: "{term:objectopenednormal_format}",
	lvnote_objectopeningheroic: "{term:objectopenedheroic_format}",
	lvnote_objectopeningnormalX: "{term:objectopenednormalx_tip}",
	lvnote_objectopeningheroicX: "{term:objectopenedheroicx_tip}",
	lvnote_zonefishing: "{term:zonefished_format}",
	lvnote_achieveevent: "{term:achievementevent_format}",
	lvnote_usercomments: "{term:usercomments_format}",
	lvnote_userscreenshots: "{term:userscreenshots_format}",
	lvnote_uservideos: "{term:uservideos_format}",
	lvnote_usertopics: "{term:usertopics_format}",
	lvnote_userreplies: "{term:userreplies_format}",
	button_compare: "{term:compare}",
	button_delete: "{term:delete}",
	button_deselect: "{term:deselect}",
	button_exclude: "{term:exclude}",
	button_include: "{term:include}",
	button_lmwhtfy: "{term:lmwhtfy}",
	button_makepriv: "{term:makeprivate_stc}",
	button_makepub: "{term:makepublic_stc}",
	button_new: "{term:new}",
	button_quickexclude: "{term:manageexclusions_stc}",
	button_remove: "{term:remove}",
	button_resync: "{term:resync}",
	button_selectall: "{term:selectall_stc}",
	button_viewin3d: "{term:viewin3d}",
	dialog_cantdisplay: "{term:itemsignored_tip}",
	dialog_compare: "{term:itemcomparison}",
	dialog_image: "{term:image}",
	dialog_imagedetails: "{term:imagedetails}",
	dialog_imagename: "{term:name_colon}",
	dialog_imageselector: "{term:imageselection}",
	dialog_losechanges: "{term:willlosechanges_tip}",
	dialog_nosaveandview: "{term:viewwithoutsaving_stc}",
	dialog_saveandview: "{term:saveandviewnow_stc}",
	dialog_saveforlater: "{term:saveforlater_stc}",
	dialog_selecteditem: "{term:itemselected_format}",
	dialog_selecteditems: "{term:itemsselected_format}",
	dialog_seeallusingicon: "{term:seeallusingicon_format}",
	message_ajaxnotsupported: "{term:upgradebrowser_tip}",
	message_cantdeletecomment: "{term:commentpurge_tip}",
	message_cantdetachcomment: "{term:commentalreadydetached_tip}",
	message_codenotentered: "{term:youdidnotenterthecaptcha_stc}",
	message_commentdetached: "{term:commentdetached_tip}",
	message_commenttooshort: "{term:messagetooshort_tip}",
	message_descriptiontooshort: "{term:descriptionminimum_tip}",
	message_emailnotvalid: "{term:invalidemail_tip}",
	message_entercurrpass: "{term:entercurrentpassword_tip}",
	message_enteremailorpass: "{term:enternewemailorpass_tip}",
	message_enteremail: "{term:enteremailaddress_tip}",
	message_enternewemail: "{term:enternewemailaddress_tip}",
	message_enternewpass: "{term:enternewpassword_tip}",
	message_enterpassword: "{term:enterpassword_tip}",
	message_enterusername: "{term:enterusername_tip}",
	message_forumposttooshort: "{term:postempty_tip}",
	message_invalidfilter: "{term:invalidfilter_stc}",
	message_invalidname: "{term:invalideimagename_tip}",
	message_newemaildifferent: "{term:newemaildiff_tip}",
	message_newpassdifferent: "{term:newpassworddiff_tip}",
	message_noscreenshot: "{term:selectscreenshot_tip}",
	message_novideo: "{term:errorvideo_tip}",
	message_nothingtoviewin3d: "{term:nothingtoviewin3d_tip}",
	message_passwordmin: "{term:passwordmin_tip}",
	message_passwordsdonotmatch: "{term:passwordsdonotmatch_stc}",
	message_savebeforeexit: "{term:savebeforeexit_tip}",
	message_startedpost: "{term:messagestarted_tip}",
	message_sharetheurlbelow: "{term:shareurl_tip}",
	message_usernamemin: "{term:usernamemin_tip}",
	message_usernamenotvalid: "{term:activate_invalidusername}",
	confirm_addtosaved: "{term:savedcomparison_prompt}",
	confirm_commenttoolong: "{term:commentlength_tip}",
	confirm_deletecomment: "{term:deletecomment_prompt}",
	confirm_descriptiontoolong: "{term:descriptionlength_tip}",
	confirm_detachcomment: "{term:commentstandalone_prompt}",
	confirm_forumposttoolong: "{term:postlength_tip}",
	confirm_report2: "{term:postreport_prompt}",
	confirm_report3: "{term:reportavatar_prompt}",
	confirm_report4: "{term:reportimage_prompt}",
	confirm_report: "{term:commentreport_prompt}",
	confirm_signaturetoolong: "{term:signaturelength_tip}",
	confirm_signaturetoomanylines: "{term:signaturelines_tip}",
	prompt_colfilter1: "{term:columnfilter_format}",
	prompt_colfilter2: "{term:examplefilter_tip}",
	prompt_colfilter3: "{term:examplefilter2_tip}",
	prompt_customrating: "{term:customrating_format}",
	prompt_details: "{term:pleaseprovidedetailsbelow_colon}",
	prompt_gotopage: "{term:gotopage_format}",
	prompt_ingamelink: "{term:copypasteingame_tip}",
	prompt_linkurl: "{term:linkurl_tip}",
	prompt_ratinglevel: "{term:ratinglevel_format}",
	genericerror: "{term:genericerror_tip}",
	tooltip_achievementcomplete: "{term:achievementcomplete_format}",
	tooltip_achievementnotfound: "{term:achievementnotfound_stc}",
	tooltip_achievementpoints: "{term:achievementpoints_stc}",
	tooltip_allianceonly: "{term:allianceonly_stc}",
	tooltip_arenapoints: "{term:arenapoints}",
	tooltip_armorbonus: "{term:bonusarmor_format}",
	tooltip_avgmoneycontained: "{term:averagemoneycontained_stc}",
	tooltip_avgmoneydropped: "{term:averagemoneydropped_stc}",
	tooltip_banned_rating: "{term:ratingban2_tip}",
	tooltip_buyoutprice: "{term:averagebuyoutpricesh_stc}",
	tooltip_captcha: "{term:generatecaptcha_tip}",
	tooltip_changelevel2: "{term:dragtochangelevel_stc}",
	tooltip_changelevel: "{term:clicktochangelevel_stc}",
	tooltip_colfilter1: "{term:filter_label}",
	tooltip_colfilter2: "{term:invertedfilter_label}",
	tooltip_combatrating: "{term:combatrating_format}",
	tooltip_consumedonuse: "{term:consumedwhenused_stc}",
	tooltip_customrating: "{term:customrating_stc}",
	tooltip_dailyquest: "{term:dailyquestlimit25_tip}",
	tooltip_downrate: "{term:poororredundant}",
	tooltip_extendedachievementsearch: "{term:extendedachievementsearch_tip}",
	tooltip_extendednpcsearch: "{term:searchtag_tip}",
	tooltip_extendedquestsearch: "{term:searchobjectives_tip}",
	tooltip_extendedspellsearch: "{term:searchdescription_tip}",
	tooltip_flight: "{term:flight}",
	tooltip_gotopage: "{term:gotopage_tip}",
	tooltip_ground: "{term:ground}",
	tooltip_heroclass: "{term:heroclass_tip}",
	tooltip_heroicmodeavailable: "{term:heroicmodeavailable_stc}",
	tooltip_honorpoints: "{term:honorpoints}",
	tooltip_hordeonly: "{term:hordeonly_stc}",
	tooltip_autores: "{term:automaticresurrection_tip}",
	tooltip_itemnotfound: "{term:itemnotfound_stc}",
	tooltip_loading: "{term:loading_ellipsis}",
	tooltip_lmwhtfy: "{term:lmwhtfy_tip}",
	tooltip_lvheader1: "{term:clicktosort_stc}",
	tooltip_lvheader2: "{term:rightclicktofilter_stc}",
	tooltip_lvheader3: "{term:shiftclicktofilter_stc}",
	tooltip_noresponse: "{term:noresponse_tip}",
	tooltip_normal: "{term:normal}",
	tooltip_notconsumedonuse: "{term:notconsumedwhenused_stc}",
	tooltip_npcnotfound: "{term:npcnotfound_stc}",
	tooltip_objectnotfound: "{term:objectnotfound_stc}",
	tooltip_partyloot: "{term:partyloot_tip}",
	tooltip_pending: "{term:pending}",
	tooltip_questnotfound: "{term:questnotfound_stc}",
	tooltip_refundable: "{term:refundableitem_tip}",
	tooltip_repgain: "{term:reputationgain_stc}",
	tooltip_reqenchanting: "{term:reqenchanting_tip}",
	tooltip_reqinscription: "{term:reqinscription_tip}",
	tooltip_reqjewelcrafting: "{term:reqjewelcrafting_tip}",
	tooltip_reqlevel: "{term:requiredlevel_stc}",
	tooltip_reqlockpicking: "{term:reqlockpicking_tip}",
	tooltip_smartloot: "{term:smartloot_tip}",
	tooltip_deprecated: "{term:cannotbeusedorequipped_stc}",
	tooltip_noequipcooldown: "{term:noequipcooldown_tip}",
	tooltip_realduration: "{term:realduration_tip}",
	tooltip_progressiveloot: "{term:progressiveloot_tip}",
	tooltip_cannotrollneed: "{term:cannotrollneed_tip}",
	tooltip_spellnotfound: "{term:spellnotfound_stc}",
	tooltip_statweighting: "{term:statweighting_tip}",
	tooltip_sticky: "{term:sticky}",
	tooltip_totaldatauploads: "{term:totaldatauploads_tip}",
	tooltip_totalratings: "{term:commentratingsum_tip}",
	tooltip_trainingpoints: "{term:trainingpoints_stc}",
	tooltip_uprate: "{term:insightfulorfunny}",
	tooltip_zonelink: "{term:zonelink_tip}",
	tab_abilities: "{term:abilities}",
	tab_achievements: "{term:achievements}",
	tab_addyourcomment: "{term:addyourcomment}",
	tab_armorproficiencies: "{term:armorproficiencies_stc}",
	tab_article: "{term:article}",
	tab_articles: "{term:articles}",
	tab_bosses: "{term:bosses}",
	tab_canbeplacedin: "{term:canbeplacedin_stc}",
	tab_cancontain: "{term:cancontain_stc}",
	tab_characters: "{term:characters}",
	tab_classes: "{term:classes}",
	tab_comments: "{term:comments}",
	tab_companions: "{term:companions}",
	tab_containedin: "{term:containedin}",
	tab_contains: "{term:contains}",
	tab_crafteditems: "{term:crafteditems_stc}",
	tab_createdby: "{term:createdby}",
	tab_criteriaof: "{term:criteriaof}",
	tab_currencyfor: "{term:currencyfor}",
	tab_disenchantedfrom: "{term:disenchantedfrom}",
	tab_disenchanting: "{term:disenchanting}",
	tab_droppedby: "{term:droppedby}",
	tab_creates: "{term:creates}",
	tab_drops: "{term:drops}",
	tab_ends: "{term:ends}",
	tab_factions: "{term:factions}",
	tab_fishedin: "{term:fishedin}",
	tab_fishing: "{term:profession_fishing}",
	tab_gallery: "{term:gallery}",
	tab_gatheredfrom: "{term:gatheredfrom}",
	tab_gatheredfromnpc: "{term:gatheredfromnpc}",
	tab_guildperks: "{term:guildperks}",
	tab_armorspecializations: "{term:armorspecializations}",
	tab_herbalism: "{term:herbalism}",
	tab_heroicdrops: "{term:heroicdrops_stc}",
	tab_heroicXdrops: "{term:heroicxdrops_format}",
	tab_heroic: "{term:heroic}",
	tab_heroicX: "{term:heroic_format}",
	tab_holidays: "{term:worldevents}",
	tab_info: "{term:info}",
	tab_items: "{term:items}",
	tab_itemsets: "{term:itemsets_stc}",
	tab_languages: "{term:languages}",
	tab_latestcomments: "{term:latestcomments}",
	tab_latestreplies: "{term:latestreplies}",
	tab_latestscreenshots: "{term:latestscreenshots}",
	tab_latestvideos: "{term:latestvideos}",
	tab_latesttopics: "{term:latesttopics}",
	tab_members: "{term:members}",
	tab_milledfrom: "{term:milledfrom}",
	tab_milling: "{term:milling}",
	tab_minedfrom: "{term:minedfrom}",
	tab_minedfromnpc: "{term:minedfromnpc}",
	tab_mining: "{term:mining}",
	tab_modifiedby: "{term:modifiedby}",
	tab_modifies: "{term:modifies}",
	tab_mounts: "{term:mounts}",
	tab_normaldrops: "{term:normaldrops_stc}",
	tab_normalXdrops: "{term:normaldrops_format}",
	tab_normal: "{term:normal}",
	tab_normalX: "{term:normal_format}",
	tab_npcs: "{term:npcs}",
	tab_npcabilities: "{term:npcabilities_stc}",
	tab_objectiveof: "{term:objectiveof}",
	tab_objects: "{term:objects}",
	tab_pets: "{term:hunterpets}",
	tab_pickpocketedfrom: "{term:pickpocketedfrom}",
	tab_pickpocketing: "{term:pickpocketing}",
	tab_professions: "{term:professions}",
	tab_profiles: "{term:profiles}",
	tab_prospectedfrom: "{term:prospectedfrom}",
	tab_prospecting: "{term:prospecting}",
	tab_providedfor: "{term:providedfor}",
	tab_questrewards: "{term:questrewards_stc}",
	tab_quests: "{term:quests}",
	tab_reagentfor: "{term:reagentfor}",
	tab_races: "{term:races}",
	tab_racialtraits: "{term:racialtraits_stc}",
	tab_recipes: "{term:recipes}",
	tab_recipeitems: "{term:recipeitems_stc}",
	tab_replies: "{term:replies}",
	tab_requiredby: "{term:requiredby}",
	tab_rewardfrom: "{term:rewardfrom}",
	tab_samemodelas: "{term:samemodelas_stc}",
	tab_screenshots: "{term:screenshots}",
	tab_statistics: "{term:statistics}",
	tab_videos: "{term:videos}",
	tab_seealso: "{term:seealso_stc}",
	tab_sells: "{term:sells}",
	tab_sharedcooldown: "{term:sharedcooldown_stc}",
	tab_skills: "{term:skills}",
	tab_skinnedfrom: "{term:skinnedfrom}",
	tab_skinning: "{term:skinning}",
	tab_soldby: "{term:soldby}",
	tab_spells: "{term:spells}",
	tab_starts: "{term:starts}",
	tab_startsquest: "{term:startsquest_stc}",
	tab_submitascreenshot: "{term:submitascreenshot_stc}",
	tab_suggestavideo: "{term:suggestavideo_stc}",
	tab_summonedby: "{term:summonedby}",
	tab_talents: "{term:talents}",
	tab_tameable: "{term:tameable}",
	tab_taughtby: "{term:taughtby}",
	tab_teaches: "{term:teaches}",
	tab_titles: "{term:titles}",
	tab_toolfor: "{term:toolfor}",
	tab_topics: "{term:topics}",
	tab_trainers: "{term:trainers}",
	tab_triggeredby: "{term:triggeredby}",
	tab_uncategorizedspells: "{term:uncategorizedspells_stc}",
	tab_unlocks: "{term:unlocks}",
	tab_usedby: "{term:usedby}",
	tab_weaponskills: "{term:weaponskills_stc}",
	tab_world: "{term:world}",
	tab_zones: "{term:zones}",
	menu_browse: "{term:browse}",
	mapper_tipzoom: "{term:clickmapzoom_tip}",
	mapper_tippin: "{term:clickmappins_tip}",
	mapper_hidepins: "{term:hidepins_stc}",
	mapper_showpins: "{term:showpins_stc}",
	mapper_floor: "{term:changefloor_ellipsis}",
	mapper_relevantlocs: "{term:relevantlocations}",
	mapper_entiretyinzone: "{term:questobjectives1zone_tip}",
	mapper_happensin: "{term:partofquesthappensin_format}",
	mapper_objectives: {
		ox: "{term:questobjectives_format}",
		sx: "{term:queststart_format}",
		ex: "{term:questendsin_format}",
		sex: "{term:queststartsends_format}",
		osx: "{term:questobjectivesstarts_format}",
		oex: "{term:questobjectivesends_format}",
		osx_ey: "{term:questobjectivesstartsinendsin_ti}",
		oex_sy: "{term:questobjectivesends_tip}",
		sx_ey: "{term:queststartsends2_format}",
		ox_sy: "{term:queststartsobjectives_format}",
		ox_ey: "{term:questobjectives2_format}",
		ox_sey: "{term:questobjectivesinstartsendsin_ti}",
		ox_sy_ez: "{term:questobjectives_tip}"
	},
	mapper_startsquest: "{term:startsthequest_stc}",
	mapper_endsquest: "{term:endsthequest_stc}",
	mapper_requiredquest: "{term:objectiveofthequest_stc}",
	mapper_sourcestart: "{term:sourceofqueststart_colon}",
	mapper_sourceend: "{term:sourceofquestend_colon}",
	mapper_sourcereq: "{term:sourceofaquestobjective_colon}",
	mapper_clicktoview: "{term:clicktoview_format}",
	markup_b: "{term:bold}",
	markup_i: "{term:italic}",
	markup_u: "{term:underline}",
	markup_s: "{term:strikethrough}",
	markup_small: "{term:smalltext_stc}",
	markup_url: "{term:link}",
	markup_quote: "{term:quotebox_stc}",
	markup_code: "{term:codebox_stc}",
	markup_ul: "{term:unorderedlistbullets_stc}",
	markup_ol: "{term:orderedlistnumbers_stc}",
	markup_li: "{term:listitem_stc}",
	markup_img: "{term:image}",
	markup_said: "{term:said_colon}",
	markup_toc: "{term:tableofcontents}",
	cn_fieldrequired: "{term:fieldrequired_format}",
	cn_fieldinvalid: "{term:fieldinvalid_format}",
	cn_confirm: "{term:contestverify_tip}",
	cn_entrylogin: "{term:contestlogin_tip}",
	cn_entryerror: "{term:contesterror_tip}",
	cn_entrywhen: "{term:contestentered_tip}",
	cn_entrywhen2: "{term:contestentered2_tip}",
	cn_entrysuccess: "{term:contestsuccess_tip}",
	cn_entryended: "{term:contestended_tip}",
	cn_entryupcoming: "{term:contestupcoming_tip}",
	cn_entryregion: "{term:contestregion_tip}",
	cn_mustbe18: "{term:contestmustbe18_tip}",
	cn_winnerslist: "{term:winnerslist}",
	cn_updated: "{term:updated}",
	ct_resp_error1: "{term:captchaerror_tip}",
	ct_resp_error2: "{term:shortdescription_tip}",
	ct_resp_error3: "{term:contactreason_tip}",
	ct_resp_error7: "{term:alreadyreported_tip}",
	compose_mode: "{term:mode_colon}",
	compose_edit: "{term:edit}",
	compose_preview: "{term:preview}",
	compose_livepreview: "{term:livepreview}",
	compose_save: "{term:save}",
	compose_cancel: "{term:cancel}",
	compose_limit: "{term:uptoxcharacters_format}",
	compose_limit2: "{term:uptoxcharactersorlines_format}",
	user_nodescription: "{term:nopublicdescription_tip}",
	user_nodescription2: "{term:nodescription_tip}",
	user_composeone: "{term:composeonenow_stc}",
	user_editdescription: "{term:edit}",
	myaccount_passmatch: "{term:passwordsmatch_stc}",
	myaccount_passdontmatch: "{term:passwordsnomatch_tip}",
	myaccount_purged: "{term:purged}",
	myaccount_purgefailed: "{term:purgefailed_stc}",
	myaccount_purgesuccess: "{term:purgesuccess_tip}",
	types: {
		1: ["{term:npc}", "{term:npc_lc}", "{term:npcs}", "{term:npcs}"],
		2: ["{term:object}", "{term:object_lc}", "{term:objects}", "{term:objects_lc}"],
		3: ["{term:item}", "{term:item_lc}", "{term:items}", "{term:items_lc}"],
		4: ["{term:itemset}", "{term:itemset_lc}", "{term:itemsets}", "{term:itemsets_lc}"],
		5: ["{term:quest}", "{term:quest_lc}", "{term:quests}", "{term:quests_lc}"],
		6: ["{term:spell}", "{term:spell_lc}", "{term:spells}", "{term:spells_lc}"],
		7: ["{term:zone}", "{term:zone_lc}", "{term:zones}", "{term:zones_lc}"],
		8: ["{term:faction}", "{term:faction_lc}", "{term:factions}", "{term:factions_lc}"],
		9: ["{term:pet}", "{term:pet_lc}", "{term:pets}", "{term:pets_lc}"],
		10: ["{term:achievement}", "{term:achievement_lc}", "{term:achievements}", "{term:achievements_lc}"],
		11: ["{term:title}", "{term:title_lc}", "{term:titles}", "{term:titles_lc}"],
		12: ["{term:worldevent}", "{term:worldevent_lc}", "{term:worldevents}", "{term:worldevents_lc}"],
		13: ["{term:class}", "{term:class_lc}", "{term:classes}", "{term:classes_lc}"],
		14: ["{term:race}", "{term:race_lc}", "{term:races}", "{term:races_lc}"],
		15: ["{term:skill}", "{term:skill_lc}", "{term:skills}", "{term:skills_lc}"],
		16: ["{term:statistic}", "{term:statistic_lc}", "{term:statistics}", "{term:statistics_lc}"]
	},
	timeunitssg: ["{term:year_lc}", "{term:month_lc}", "{term:week_lc}", "{term:day_lc}", "{term:hour_lc}", "{term:minute_lc}", "{term:second_lc}"],
	timeunitspl: ["{term:years_lc}", "{term:months_lc}", "{term:weeks_lc}", "{term:days_lc}", "{term:hours_lc}", "{term:minutes_lc}", "{term:seconds_lc}"],
	timeunitsab: ["{term:year_abbrev}", "{term:month_abbrev}", "{term:week_abbrev}", "{term:day_abbrev}", "{term:hour_abbrev}", "{term:minute_abbrev}", "{term:second_abbrev}"],
	added: "{term:added}",
	build: "{term:build}",
	calculators: "{term:calculators}",
	patch: "{term:patch}"

/*
	and: " and ",
	comma: ", ",
	ellipsis: "…",
	dash: " – ",
	hyphen: " - ",
	colon: ": ",
	qty: " ($1)",
	date: "Date",
	date_colon: "Date: ",
	date_on: "on ",
	date_ago: "$1 ago",
	date_at: " at ",
	date_simple: "$2/$1/$3",
	date_months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
	abilities: "Abilities",
	armor: "Armor",
	author: "Author",
	battlegroup: "Battlegroup",
	category: "Category",
	classes: "Classes",
	classs: "Class",
	close: "Close",
	completed: "Completed",
	contactus: "Contact us",
	cost: "Cost",
	count: "Count",
	daily: "Daily",
	weekly: "Weekly",
	damage: "Damage",
	diet: "Diet",
	dps: "DPS",
	earned: "Earned",
	enchant: "Enchant",
	faction: "Faction",
	gains: "Gains",
	gender: "Gender",
	gems: "Gems",
	gearscore: "Gear",
	gearscore_real: "Gear score",
	glyphtype: "Glyph type",
	guildlevel: "Guild Level",
	group: "Group",
	guild: "Guild",
	guildleader: "Guild Leader",
	guildrank: "Guild Rank",
	health: "Health",
	heroiclevel: "Heroic level",
	icon: "Icon",
	instancetype: "Instance type",
	lastpost: "Last post",
	level: "Level",
	location: "Location",
	losses: "Losses",
	members: "Members",
	name: "Name",
	players: "Players",
	race: "Race",
	races: "Races",
	rankno: "Rank $1",
	rating: "Rating",
	react: "React",
	realm: "Realm",
	reagents: "Reagents",
	region: "Region",
	rep: "Rep.",
	req: "Req. ",
	reputation: "Reputation",
	rewards: "Rewards",
	petfamily: "Pet family",
	pieces: "Pieces",
	points: "Points",
	posted: "Posted",
	premiumupgrade: "Premium Upgrade",
	preview: "Preview",
	privateprofile: "Private",
	prize: "Prize",
	profiler: "Profiler",
	progress: "Progress",
	publicprofile: "Public",
	replies: "Replies",
	report: "Report",
	report_tooltip: "Click for many reporting options",
	school: "School",
	score: "Score",
	settings: "Settings",
	side: "Side",
	signout: "Sign Out",
	sockets: "Sockets",
	source: "Source",
	skill: "Skill",
	skin: "Skin",
	slot: "Slot",
	slots: "Slots",
	smartloot: "Smart loot",
	speed: "Speed",
	stack: "Stack",
	standing: "Standing",
	stock: "Stock",
	statistic: "Statistic",
	subject: "Subject",
	submit: "Submit",
	talents: "Talents",
	territory: "Territory",
	tier: "Tier",
	topics: "Topics",
	tp: "TP",
	type: "Type",
	user: "User",
	views: "Views",
	userpage: "User Page",
	wins: "Wins",
	when: "When",
	today: "today",
	yesterday: "yesterday",
	dayatnoon: "$1 at noon",
	dayatmidnight: "$1 at midnight",
	dayatam: "$1 at $2 AM",
	dayatpm: "$1 at $2 PM",
	male: "Male",
	female: "Female",
	source_zonedrop: "Zone Drop",
	source_quests: "Quests",
	source_vendors: "Vendors",
	infobox_noneyet: "None yet &ndash; $1!",
	infobox_submitone: "Submit one",
	infobox_suggestone: "Suggest one",
	infobox_showall: "Show all ($1)",
	lvclass_hero: "Hero class",
	lvcomment_add: "Add your comment",
	lvcomment_sort: "Sort by: ",
	lvcomment_sortdate: "Date",
	lvcomment_sortrating: "Highest rated",
	lvcomment_patchfilter: "Filter by patch: ",
	lvcomment_by: "By ",
	lvcomment_patch: " (Patch $1)",
	lvcomment_show: "Show comment",
	lvcomment_hide: "Hide comment",
	lvcomment_rating: "Rating: ",
	lvcomment_lastedit: "Last edited by ",
	lvcomment_nedits: "edited $1 times",
	lvcomment_edit: "Edit",
	lvcomment_delete: "Delete",
	lvcomment_detach: "Detach",
	lvcomment_reply: "Reply",
	lvcomment_report: "Report",
	lvcomment_reported: "Reported!",
	lvcomment_deleted: " (Deleted)",
	lvcomment_purged: " (Purged)",
	lvdrop_outof: "out of $1",
	lvitem_dd: " ($1$2)",
	lvitem_normal: "N",
	lvitem_heroic: "H",
	lvitem_raid10: "10",
	lvitem_raid25: "25",
	lvitem_heroicitem: "Heroic",
	lvitem_vendorin: "Vendor in ",
	lvitem_reqlevel: "Req. ",
	lvnpc_alliance: "A",
	lvnpc_horde: "H",
	premium_title: "Wowhead Patron",
	lvquest_daily: "Daily $1",
	lvquest_weekly: "Weekly $1",
	lvquest_pickone: "Pick one: ",
	lvquest_alsoget: "Also get: ",
	lvquest_xp: "$1 XP",
	lvquest_removed: "Removed",
	lvzone_xman: "$1-player",
	lvzone_xvx: "$1v$2",
	lvpet_exotic: "Exotic",
	lvpage_of: " of ",
	lvpage_first: " First",
	lvpage_previous: " Previous",
	lvpage_next: "Next ",
	lvpage_last: "Last ",
	lvscreenshot_submit: "Submit a screenshot",
	lvscreenshot_from: "From ",
	lvscreenshot_hires: "View",
	lvscreenshot_hires2: " higher resolution version ($1x$2)",
	lvvideo_suggest: "Suggest a video",
	lvvideo_from: "From ",
	lvnodata: "There is no data to display.",
	lvnodata2: "No matches found.",
	lvnodata_co1: "No comments have been posted yet.",
	lvnodata_co2: "Be the first to <a>add a comment</a> to this page!",
	lvnodata_co3: "Please <a>sign in</a> to add your comment, or <a>sign up</a> if you don't already have an account.",
	lvnodata_ss1: "No screenshots have been submitted yet.",
	lvnodata_ss2: "Be the first to <a>submit a screenshot</a> for this page!",
	lvnodata_ss3: "Please <a>sign in</a> to submit a screenshot, or <a>sign up</a> if you don't already have an account.",
	lvnodata_vi1: "No videos have been submitted yet.",
	lvnodata_vi2: "Be the first to <a>suggest a video</a> for this page!",
	lvnodata_vi3: "Please <a>sign in</a> to suggest a video, or <a>sign up</a> if you don't already have an account.",
	lvnote_tryfiltering: "Try filtering your results",
	lvnote_trynarrowing: "Try narrowing your search",
	lvnote_upgradesfor: 'Finding upgrades for <a href="/item=$1" class="q$2"><b>$3</b></a>.',
	lvnote_itemsfound: "$1 items found ($2 displayed)",
	lvnote_itemsetsfound: "$1 item sets found ($2 displayed)",
	lvnote_npcsfound: "$1 NPCs found ($2 displayed)",
	lvnote_objectsfound: "$1 objects found ($2 displayed)",
	lvnote_questsfound: "$1 quests found ($2 displayed)",
	lvnote_questsind: 'Quests categorized under <a href="/quests=$1.$2" target="_blank">$3</a>.',
	lvnote_spellsfound: "$1 spells found ($2 displayed)",
	lvnote_skillsfound: "$1 skills found ($2 displayed)",
	lvnote_abilitiesfound: "$1 abilities found ($2 displayed)",
	lvnote_talentsfound: "$1 talents found ($2 displayed)",
	lvnote_professionfound: "$1 professions found ($2 displayed)",
	lvnote_mountsfound: "$1 mounts found ($2 displayed)",
	lvnote_zonesfound: "$1 zones found ($2 displayed)",
	lvnote_companionsfound: "$1 companions found ($2 displayed)",
	lvnote_factionsfound: "$1 factions found ($2 displayed)",
	lvnote_petsfound: "$1 pets found ($2 displayed)",
	lvnote_achievementsfound: "$1 achievements found ($2 displayed)",
	lvnote_achievementsind: 'Achievements categorized under <a href="/achievements=$1.$2" target="_blank">$3</a>.',
	lvnote_statisticsfound: "$1 statistics found ($2 displayed)",
	lvnote_charactersfound: "$1 total characters",
	lvnote_charactersfound2: "$1 total characters, $2 matching",
	lvnote_guildsfound: "$1 total guilds",
	lvnote_guildsfound2: "$1 total guilds, $2 matching",
	lvnote_arenateamsfound: "$1 total arena teams",
	lvnote_arenateamsfound2: "$1 total arena teams, $2 matching",
	lvnote_createafilter: '<small><a href="$1">Create a filter</a></small>',
	lvnote_filterresults: '<a href="$1">Filter these results</a>',
	lvnote_questgivers: 'View <a href="/zone=$1">quest givers</a> in <b>$2</b> &nbsp;<b>|</b>&nbsp; Filter <a href="/items?filter=cr=126;crs=$3;crv=0">quest rewards</a>',
	lvnote_allpets: 'All pets can learn all of the <a href="/spells=-3.270">passive skills</a>',
	lvnote_zonequests: 'Browse <a href="/quests=$1.$2">quests</a> in the <b>$3</b> category &nbsp;<b>|</b>&nbsp; Filter <a href="/items?filter=cr=126;crs=$4;crv=0">quest rewards</a>',
	lvnote_crafteditems: 'Filter <a href="/items?filter=cr=86;crs=$1;crv=0">crafted items</a>',
	lvnote_viewmoreslot: 'View <a href="/items$1?filter=$2">more results</a> for this slot',
	lvnote_viewmorelevel: 'View <a href="/items$1?filter=$2">more results</a> for this item level',
	lvnote_itemdisenchanting: "This item has been disenchanted $1 times.",
	lvnote_itemdropsinnormalonly: "This item only drops in Normal mode.",
	lvnote_itemdropsinheroiconly: "This item only drops in Heroic mode.",
	lvnote_itemdropsinnormalheroic: "This item drops in both Normal and Heroic modes.",
	lvnote_itemdropsinnormal10only: "This item only drops in Normal 10 mode.",
	lvnote_itemdropsinnormal25only: "This item only drops in Normal 25 mode.",
	lvnote_itemdropsinheroic10only: "This item only drops in Heroic 10 mode.",
	lvnote_itemdropsinheroic25only: "This item only drops in Heroic 25 mode.",
	lvnote_itemmilling: "This herb has been milled $1 times.",
	lvnote_itemopening: "This item has been opened $1 times.",
	lvnote_itemprospecting: "This mineral ore has been prospected $1 times.",
	lvnote_npcdrops: "This NPC has been looted $1 times.",
	lvnote_npcdropsnormal: "This NPC has been looted $1 times in Normal mode.",
	lvnote_npcdropsheroic: "This NPC has been looted $1 times in Heroic mode.",
	lvnote_npcdropsnormalX: "This NPC has been looted $1 times in Normal $2 mode.",
	lvnote_npcdropsheroicX: "This NPC has been looted $1 times in Heroic $2 mode.",
	lvnote_npcobject: '<a href="/object=$1">$2</a> has been opened $3 times.',
	lvnote_npcobjectnormal: '<a href="/object=$1">$2</a> has been opened $3 times in Normal mode.',
	lvnote_npcobjectheroic: '<a href="/object=$1">$2</a> has been opened $3 times in Heroic mode.',
	lvnote_npcobjectnormalX: '<a href="/object=$1">$2</a> has been opened $3 times in Normal $4 mode.',
	lvnote_npcobjectheroicX: '<a href="/object=$1">$2</a> has been opened $3 times in Heroic $4 mode.',
	lvnote_npcherbgathering: "This NPC has been skinned with Herbalism $1 times.",
	lvnote_npcmining: "This NPC has been skinned with Mining $1 times.",
	lvnote_npcpickpocketing: "This NPC has been pickpocketed $1 times.",
	lvnote_npcskinning: "This NPC has been skinned $1 times.",
	lvnote_objectherbgathering: "This herb has been gathered $1 times.",
	lvnote_objectmining: "This mineral vein has been mined $1 times.",
	lvnote_objectopening: "This object has been opened $1 times.",
	lvnote_objectopeningnormal: "This object has been opened $1 times in Normal mode.",
	lvnote_objectopeningheroic: "This object has been opened $1 times in Heroic mode.",
	lvnote_objectopeningnormalX: "This object has been opened $1 times in Normal $2 mode.",
	lvnote_objectopeningheroicX: "This object has been opened $1 times in Heroic $2 mode.",
	lvnote_zonefishing: "Waters in this zone have been fished $1 times.",
	lvnote_achieveevent: 'View <a href="/event=$1">event page</a> for <b>$2</b>',
	lvnote_usercomments: "This user has posted a total of $1 comments.",
	lvnote_userscreenshots: "This user has submitted a total of $1 screenshots.",
	lvnote_uservideos: "This user has submitted a total of $1 videos.",
	lvnote_usertopics: "This user has posted a total of $1 topics.",
	lvnote_userreplies: "This user has posted a total of $1 replies.",
	button_compare: "Compare",
	button_delete: "Delete",
	button_deselect: "Deselect",
	button_exclude: "Exclude",
	button_include: "Include",
	button_lmwhtfy: "LMWHTFY",
	button_makepriv: "Make private",
	button_makepub: "Make public",
	button_new: "New",
	button_quickexclude: "Manage exclusions",
	button_remove: "Remove",
	button_resync: "Resync",
	button_selectall: "Select all",
	button_viewin3d: "View in 3D",
	dialog_cantdisplay: "Note: Some of the items you selected were ignored. Select them individually to display them in 3D.",
	dialog_compare: "Item Comparison",
	dialog_image: "Image",
	dialog_imagedetails: "Image Details",
	dialog_imagename: "Name: ",
	dialog_imageselector: "Image Selection",
	dialog_losechanges: "You are viewing an Armory character. Any changes you make will be lost unless you save this character as a custom profile.",
	dialog_nosaveandview: "View without saving",
	dialog_saveandview: "Save and view now",
	dialog_saveforlater: "Save for later",
	dialog_selecteditem: "<b>$1</b> item has been selected.",
	dialog_selecteditems: "<b>$1</b> items have been selected.",
	dialog_seeallusingicon: "See all $1, $2, or $3 using this icon.",
	message_ajaxnotsupported: "Please upgrade to a modern browser (such as Firefox) that supports 'Ajax' requests.",
	message_cantdeletecomment: "This comment has been automatically purged due to a negative rating. It cannot be deleted.",
	message_cantdetachcomment: "This comment has already been detached.",
	message_codenotentered: "You did not enter the CAPTCHA.",
	message_commentdetached: "This comment is now detached.",
	message_commenttooshort: "Your message must not be empty.",
	message_descriptiontooshort: "Your description must be at least 10 characters long.\n\nPlease elaborate a little.",
	message_emailnotvalid: "That email address is not valid.",
	message_entercurrpass: "Please enter your current password.",
	message_enteremailorpass: "You must enter your new email address or password!",
	message_enteremail: "Please enter your email address.",
	message_enternewemail: "Please enter your new email address.",
	message_enternewpass: "Please enter your new password.",
	message_enterpassword: "Please enter your password.",
	message_enterusername: "Please enter your username.",
	message_forumposttooshort: "Your post is empty!",
	message_invalidfilter: "Invalid filter.",
	message_invalidname: "Image name is invalid. Must be alphanumeric, 20 characters max, and start with a letter.",
	message_newemaildifferent: "Your new email address must be different than your previous one.",
	message_newpassdifferent: "Your new password must be different than your previous one.",
	message_noscreenshot: "Please select the screenshot to upload.",
	message_novideo: "Please enter valid video information.",
	message_nothingtoviewin3d: "No items were selected that can be viewed in 3D.",
	message_passwordmin: "Your password must be at least 6 characters long.",
	message_passwordsdonotmatch: "Passwords do not match.",
	message_savebeforeexit: "You will lose any unsaved changes you have made.",
	message_startedpost: "You have started to write a message.",
	message_sharetheurlbelow: "Share the URL below:",
	message_usernamemin: "Your username must be at least 4 characters long.",
	message_usernamenotvalid: "Your username can only contain letters and numbers.",
	confirm_addtosaved: "Add to your saved comparison?",
	confirm_commenttoolong: "Your comment is longer than $1 characters and will be truncated after:\n\n$2\n\nDo you want to proceed anyway?",
	confirm_deletecomment: "Are you sure that you want to delete this comment?",
	confirm_descriptiontoolong: "Your description is longer than $1 characters and will be truncated after:\n\n$2\n\nDo you want to proceed anyway?",
	confirm_detachcomment: "Are you sure that you want to make this comment a standalone one?",
	confirm_forumposttoolong: "Your post is longer than $1 characters and will be truncated after:\n\n$2\n\nDo you want to proceed anyway?",
	confirm_report2: "Are you sure that you want to report this post as $1?",
	confirm_report3: "Are you sure that you want to report this user's avatar as vulgar/inappropriate?",
	confirm_report4: "Are you sure that you want to report this image as vulgar/inappropriate?",
	confirm_report: "Are you sure that you want to report this comment as $1?",
	confirm_signaturetoolong: "Your signature is longer than $1 characters and will be truncated after:\n\n$2\n\nDo you want to proceed anyway?",
	confirm_signaturetoomanylines: "Your signature contains more than $1 lines and will be truncated.\n\nDo you want to proceed anyway?",
	prompt_colfilter1: "You may set a filter for the $1 column:\n\n",
	prompt_colfilter2: 'e.g. "sword"',
	prompt_colfilter3: 'e.g. ">100", "32-34" or "!<=10"',
	prompt_customrating: "Please enter a rating value between -$1 and $2:",
	prompt_details: "Please provide details below:",
	prompt_gotopage: "Please enter the page number you wish to go to ($1 - $2):",
	prompt_ingamelink: "Copy/paste the following to your in-game chat window:",
	prompt_linkurl: "Please enter the URL of your link:",
	prompt_ratinglevel: "Please enter the level used in the calculation ($1 - $2):",
	genericerror: "An error has occurred; refresh the page and try again. If the error persists email feedback@wowhead.com",
	tooltip_achievementcomplete: "Achievement earned by $1 on $2/$3/$4",
	tooltip_achievementnotfound: "Achievement not found :(",
	tooltip_achievementpoints: "Achievement points",
	tooltip_allianceonly: "Alliance only",
	tooltip_arenapoints: "Arena Points",
	tooltip_armorbonus: "Has $1 bonus armor.",
	tooltip_avgmoneycontained: "Average money contained",
	tooltip_avgmoneydropped: "Average money dropped",
	tooltip_banned_rating: "You have been banned from rating comments.",
	tooltip_buyoutprice: "Average buyout price (AH)",
	tooltip_captcha: "Click to generate a new one",
	tooltip_changelevel2: "Drag to change level",
	tooltip_changelevel: "Click to change level",
	tooltip_colfilter1: "Filter: $1",
	tooltip_colfilter2: "Inverted filter: $1",
	tooltip_combatrating: "$1&nbsp;@&nbsp;L$2",
	tooltip_consumedonuse: "Consumed when used",
	tooltip_customrating: "Custom rating",
	tooltip_dailyquest: "You may complete up to<br />25 daily quests per day.",
	tooltip_downrate: "Poor/redundant",
	tooltip_extendedachievementsearch: "Check this option to search in the<br />description as well.",
	tooltip_extendednpcsearch: "Check this option to search in the<br />&lt;tag&gt; as well.",
	tooltip_extendedquestsearch: "Check this option to search in the<br />objectives and description as well.",
	tooltip_extendedspellsearch: "Check this option to search in the<br />description and buff as well.",
	tooltip_flight: "Flight",
	tooltip_gotopage: "Click to go to a specific page",
	tooltip_ground: "Ground",
	tooltip_heroclass: "Players who have a character of at least level<br />55 on the account they play are able to create<br />a new level-55 hero class character.",
	tooltip_heroicmodeavailable: "Heroic mode available",
	tooltip_honorpoints: "Honor Points",
	tooltip_hordeonly: "Horde only",
	tooltip_autores: "When you release your spirit after death,<br />you will resurrect automatically without having<br />to go back to your corpse.",
	tooltip_itemnotfound: "Item not found :(",
	tooltip_loading: "Loading...",
	tooltip_lmwhtfy: '<b class="q">LMWHTFY</b><br />Get a LMWHTFY.com link to this search.',
	tooltip_lvheader1: "Click to sort",
	tooltip_lvheader2: "Right-click to filter",
	tooltip_lvheader3: "Shift-click to filter",
	tooltip_noresponse: "No response from server :(",
	tooltip_normal: "Normal",
	tooltip_notconsumedonuse: "Not consumed when used",
	tooltip_npcnotfound: "NPC not found :(",
	tooltip_objectnotfound: "Object not found :(",
	tooltip_partyloot: "When this item drops, each<br />member of the group can loot one.",
	tooltip_pending: "Pending",
	tooltip_questnotfound: "Quest not found :(",
	tooltip_refundable: "May be returned for a refund at a vendor<br />if within two hours after the purchase.",
	tooltip_repgain: "Reputation gain",
	tooltip_reqenchanting: "Required Enchanting skill",
	tooltip_reqinscription: "Required Inscription skill",
	tooltip_reqjewelcrafting: "Required Jewelcrafting skill",
	tooltip_reqlevel: "Required level",
	tooltip_reqlockpicking: "Required Lockpicking skill",
	tooltip_smartloot: "Only available to players who have<br />the profession and don't already<br />have the recipe.",
	tooltip_deprecated: "Cannot be used or equipped",
	tooltip_noequipcooldown: "The item will be ready immediately when equipped,<br />without the normal 30-second cooldown.",
	tooltip_realduration: "The item's duration is real time, not play time.<br />It will keep ticking while logged off.",
	tooltip_progressiveloot: "This item has a dynamic drop rate<br />that increases with quest progression.",
	tooltip_cannotrollneed: "You cannot roll Need on this item.",
	tooltip_spellnotfound: "Spell not found :(",
	tooltip_statweighting: '<b class="q1">Stat Weighting</b><br />\nFind the best items for your class/spec.',
	tooltip_sticky: "Sticky",
	tooltip_totaldatauploads: "Total size of all their data uploads",
	tooltip_totalratings: "Sum of all the comment ratings received",
	tooltip_trainingpoints: "Training points",
	tooltip_uprate: "Insightful/funny",
	tooltip_zonelink: "Clicking on this link will<br />take you to the zone page.",
	tab_abilities: "Abilities",
	tab_achievements: "Achievements",
	tab_addyourcomment: "Add your comment",
	tab_armorproficiencies: "Armor proficiencies",
	tab_article: "Article",
	tab_articles: "Articles",
	tab_bosses: "Bosses",
	tab_canbeplacedin: "Can be placed in",
	tab_cancontain: "Can contain",
	tab_characters: "Characters",
	tab_classes: "Classes",
	tab_comments: "Comments",
	tab_companions: "Companions",
	tab_containedin: "Contained in",
	tab_contains: "Contains",
	tab_crafteditems: "Crafted items",
	tab_createdby: "Created by",
	tab_criteriaof: "Criteria of",
	tab_currencyfor: "Currency for",
	tab_disenchantedfrom: "Disenchanted from",
	tab_disenchanting: "Disenchanting",
	tab_droppedby: "Dropped by",
	tab_creates: "Creates",
	tab_drops: "Drops",
	tab_ends: "Ends",
	tab_factions: "Factions",
	tab_fishedin: "Fished in",
	tab_fishing: "Fishing",
	tab_gallery: "Gallery",
	tab_gatheredfrom: "Gathered from",
	tab_gatheredfromnpc: "Gathered from NPC",
	tab_guildperks: "Guild Perks",
	tab_armorspecializations: "Armor Specializations",
	tab_herbalism: "Herbalism",
	tab_heroicdrops: "Heroic drops",
	tab_heroicXdrops: "Heroic $1 drops",
	tab_heroic: "Heroic",
	tab_heroicX: "Heroic $1",
	tab_holidays: "World Events",
	tab_info: "Info",
	tab_items: "Items",
	tab_itemsets: "Item sets",
	tab_languages: "Languages",
	tab_latestcomments: "Latest Comments",
	tab_latestreplies: "Latest Replies",
	tab_latestscreenshots: "Latest Screenshots",
	tab_latestvideos: "Latest Videos",
	tab_latesttopics: "Latest Topics",
	tab_members: "Members",
	tab_milledfrom: "Milled from",
	tab_milling: "Milling",
	tab_minedfrom: "Mined from",
	tab_minedfromnpc: "Mined from NPC",
	tab_mining: "Mining",
	tab_modifiedby: "Modified by",
	tab_modifies: "Modifies",
	tab_mounts: "Mounts",
	tab_normaldrops: "Normal drops",
	tab_normalXdrops: "Normal $1 drops",
	tab_normal: "Normal",
	tab_normalX: "Normal $1",
	tab_npcs: "NPCs",
	tab_npcabilities: "NPC abilities",
	tab_objectiveof: "Objective of",
	tab_objects: "Objects",
	tab_pets: "Hunter Pets",
	tab_pickpocketedfrom: "Pickpocketed from",
	tab_pickpocketing: "Pickpocketing",
	tab_professions: "Professions",
	tab_profiles: "Profiles",
	tab_prospectedfrom: "Prospected from",
	tab_prospecting: "Prospecting",
	tab_providedfor: "Provided for",
	tab_questrewards: "Quest rewards",
	tab_quests: "Quests",
	tab_reagentfor: "Reagent for",
	tab_races: "Races",
	tab_racialtraits: "Racial traits",
	tab_recipes: "Recipes",
	tab_recipeitems: "Recipe items",
	tab_replies: "Replies",
	tab_requiredby: "Required by",
	tab_rewardfrom: "Reward from",
	tab_samemodelas: "Same model as",
	tab_screenshots: "Screenshots",
	tab_statistics: "Statistics",
	tab_videos: "Videos",
	tab_seealso: "See also",
	tab_sells: "Sells",
	tab_sharedcooldown: "Shared cooldown",
	tab_skills: "Skills",
	tab_skinnedfrom: "Skinned from",
	tab_skinning: "Skinning",
	tab_soldby: "Sold by",
	tab_spells: "Spells",
	tab_starts: "Starts",
	tab_startsquest: "Starts quest",
	tab_submitascreenshot: "Submit a screenshot",
	tab_suggestavideo: "Suggest a video",
	tab_summonedby: "Summoned by",
	tab_talents: "Talents",
	tab_tameable: "Tameable",
	tab_taughtby: "Taught by",
	tab_teaches: "Teaches",
	tab_titles: "Titles",
	tab_toolfor: "Tool for",
	tab_topics: "Topics",
	tab_trainers: "Trainers",
	tab_triggeredby: "Triggered by",
	tab_uncategorizedspells: "Uncategorized spells",
	tab_unlocks: "Unlocks",
	tab_usedby: "Used by",
	tab_weaponskills: "Weapon skills",
	tab_world: "World",
	tab_zones: "Zones",
	menu_browse: "Browse",
	mapper_tipzoom: "Tip: Click map to zoom",
	mapper_tippin: "Tip: Click map to add/remove pins",
	mapper_hidepins: "Hide pins",
	mapper_showpins: "Show pins",
	mapper_floor: "Change floor...",
	mapper_relevantlocs: "Relevant Locations",
	mapper_entiretyinzone: "The entirety of this quest happens in $$",
	mapper_happensin: "Part of this quest happens in $$.",
	mapper_objectives: {
		ox: "This quest has objectives in $$.",
		sx: "This quest starts in $$.",
		ex: "This quest ends in $$.",
		sex: "This quest starts and ends in $$.",
		osx: "This quest has objectives and starts in $$.",
		oex: "This quest has objectives and ends in $$.",
		osx_ey: "This quest has objectives and starts in $$ and ends in $$.",
		oex_sy: "This quest has objectives and ends in $$ and starts in $$.",
		sx_ey: "This quest starts in $$ and ends in $$.",
		ox_sy: "This quest starts in $$ and has objectives in $$.",
		ox_ey: "This quest has objectives in $$ and ends in $$.",
		ox_sey: "This quest starts and ends in $$ and has objectives in $$.",
		ox_sy_ez: "This quest starts in $$, has objectives in $$ and ends in $$."
	},
	mapper_startsquest: "Starts the quest",
	mapper_endsquest: "Ends the quest",
	mapper_requiredquest: "Objective of the quest",
	mapper_sourcestart: "Source of the quest's start:",
	mapper_sourceend: "Source of the quest's end:",
	mapper_sourcereq: "Source of a quest objective: ",
	mapper_clicktoview: "Click to view this $1",
	markup_b: "Bold",
	markup_i: "Italic",
	markup_u: "Underline",
	markup_s: "Strikethrough",
	markup_small: "Small text",
	markup_url: "Link",
	markup_quote: "Quote box",
	markup_code: "Code box",
	markup_ul: "Unordered list (bullets)",
	markup_ol: "Ordered list (numbers)",
	markup_li: "List item",
	markup_img: "Image",
	markup_said: "said: ",
	markup_toc: "Table of Contents",
	cn_fieldrequired: "$1 is required.",
	cn_fieldinvalid: "$1 must be valid.",
	cn_confirm: "Make sure you have verified the information you entered, and then click OK.",
	cn_entrylogin: 'Please <a href="/account=signin">sign in</a> to enter the contest, or <a href="/account=signup">sign up</a> if you don\'t already have an account.',
	cn_entryerror: "An error occurred. Please try again.",
	cn_entrywhen: "You entered the contest on <b>$1</b>.",
	cn_entrywhen2: "You have already entered the contest.",
	cn_entrysuccess: "You have just entered the contest. Best of luck!",
	cn_entryended: "This contest has ended.",
	cn_entryupcoming: "This contest has not yet begun. Stay tuned to enter!",
	cn_entryregion: "You are not eligible to enter this contest in your region.",
	cn_mustbe18: "You must be 18 years old or older to enter the contest.",
	cn_winnerslist: "Winners List",
	cn_updated: "Updated ",
	ct_resp_error1: "The CAPTCHA you entered is invalid. Please try again.",
	ct_resp_error2: "Please provide a thorough description, but not too long.",
	ct_resp_error3: "Please choose a reason for contacting us.",
	ct_resp_error7: "You've already reported this.",
	compose_mode: "Mode: ",
	compose_edit: "Edit",
	compose_preview: "Preview",
	compose_livepreview: "Live Preview",
	compose_save: "Save",
	compose_cancel: "Cancel",
	compose_limit: "Up to $1 characters",
	compose_limit2: "Up to $1 characters and/or $2 lines",
	user_nodescription: "This user hasn't composed a public description yet.",
	user_nodescription2: "You haven't composed one yet.",
	user_composeone: "Compose one now!",
	user_editdescription: "Edit",
	myaccount_passmatch: "Passwords match",
	myaccount_passdontmatch: "Passwords do not match",
	myaccount_purged: "Purged",
	myaccount_purgefailed: "Purge failed :(",
	myaccount_purgesuccess: "Announcement data has been successfully purged!",
	types: {
		1: ["NPC", "NPC", "NPCs", "NPCs"],
		2: ["Object", "object", "Objects", "objects"],
		3: ["Item", "item", "Items", "items"],
		4: ["Item Set", "item set", "Item Sets", "item sets"],
		5: ["Quest", "quest", "Quests", "quests"],
		6: ["Spell", "spell", "Spells", "spells"],
		7: ["Zone", "zone", "Zones", "zones"],
		8: ["Faction", "faction", "Factions", "factions"],
		9: ["Pet", "pet", "Pets", "pets"],
		10: ["Achievement", "achievement", "Achievements", "achievements"],
		11: ["Title", "title", "Titles", "titles"],
		12: ["World Event", "world event", "World Events", "world events"],
		13: ["Class", "class", "Classes", "classes"],
		14: ["Race", "race", "Races", "races"],
		15: ["Skill", "skill", "Skills", "skills"],
		16: ["Statistic", "statistic", "Statistics", "statistics"]
	},
	timeunitssg: ["year", "month", "week", "day", "hour", "minute", "second"],
	timeunitspl: ["years", "months", "weeks", "days", "hours", "minutes", "seconds"],
	timeunitsab: ["yr", "mo", "wk", "{term:day_abbrev}", "hr", "min", "sec"],
	added: "Added",
	build: "Build",
	calculators: "Calculators",
	patch: "Patch"
*/