	su_notice: "{term:summaryhelp_tip}",
	su_itemtip: "{term:shiftorrightclick_tip}",
	su_additems: "{term:additems_tip}",
	su_autosaving: "{term:autosaving}",
	su_viewsaved: "{term:viewsavedcomparison_stc}",
	su_savecompare: "{term:save}",
	su_linkcompare: "{term:linktothiscomparison_stc}",
	su_clear: "{term:clear}",
	su_help: "{term:help}",
	su_addscale: "{term:weightscale_stc}",
	su_additem: "{term:item}",
	su_addset: "{term:itemset_stc}",
	su_toggle: "{term:clicktotoggledisplay_stc}",
	su_preset: "{term:preset_colon}",
	su_name: "{term:name_colon}",
	su_level: "{term:level_colon}",
	su_addweight: "{term:addnotherweight_stc}",
	su_applyweight: "{term:add}",
	su_resetweight: "{term:reset}",
	su_export: "{term:export}",
	su_viewin3d: "{term:viewin3d}",
	su_split: "{term:split}",
	su_customscale: "{term:customscale_format}",
	su_comparing: "{term:comparing}",
	su_comparewith: "{term:with_lc}",
	su_note_name: "{term:name_colon}",
	su_searching3: "{term:searchingitems_format}",
	su_searching4: "{term:searchingitemsets_format}",
	su_specifyitem3: "{term:specifyitemsearch_tip}",
	su_specifyitem4: "{term:specifyitemsetsearch_tip}",
	su_added3: "{term:addeditem_tip}",
	su_added4: "{term:addeditemset_tip}",
	su_noresults: "{term:noresults_format}",
	tooltip_setfocus: "{term:focuscolumn_tip}",
	tooltip_removefocus: "{term:removefocus_stc}",
	tooltip_gains: "{term:columngains_tip}",
	message_deleteitem: "{term:deletex_prompt}",
	message_deletegroup: "{term:deletegroup_prompt}",

/*
	su_notice: 'First time? &ndash; Don\'t be shy! Just check out our <a href="/help=item-comparison" target="_blank">Help page</a>! &nbsp; <small class="q0"><a href="javascript:;">close</a></small>',
	su_itemtip: "Tip: Shift or right-click items for more options.",
	su_additems: "To begin, add some items.",
	su_autosaving: "Autosaving",
	su_viewsaved: "View saved comparison",
	su_savecompare: "Save",
	su_linkcompare: "Link to this comparison",
	su_clear: "Clear",
	su_help: "Help",
	su_addscale: "Weight scale",
	su_additem: "Item",
	su_addset: "Item set",
	su_toggle: "Click to toggle display",
	su_preset: "Preset: ",
	su_name: "Name: ",
	su_level: "Level: ",
	su_addweight: "Add another weight",
	su_applyweight: "Add",
	su_resetweight: "Reset",
	su_export: "Export",
	su_viewin3d: "View in 3D",
	su_split: "Split",
	su_customscale: "Custom scale #$1",
	su_comparing: "Comparing ",
	su_comparewith: " with ",
	su_note_name: "Name: ",
	su_searching3: 'Searching for items named "$1"...',
	su_searching4: 'Searching for item sets named "$1"...',
	su_specifyitem3: "Please enter an item name to search for.",
	su_specifyitem4: "Please enter an item set name to search for.",
	su_added3: 'Added item <a href="/item=$1" class="q$2" target="_blank">[$3]</a> to comparison.',
	su_added4: 'Added item set <a href="/itemset=$1" class="q$2" target="_blank">[$3]</a> to comparison.',
	su_noresults: 'No results found for "$1"!',
	tooltip_setfocus: '<b>Set focus</b><br /><span class="q1">Compare all other columns to this one.</span>',
	tooltip_removefocus: "Remove focus",
	tooltip_gains: "Bonuses you gain above the minimum<br />shared stats between all columns.",
	message_deleteitem: "Delete $1?",
	message_deletegroup: "Delete this group?",
*/