	tc_rank: "{term:rankoutof_format}",
	tc_tier: "{term:requirestalents_format}",
	tc_prereq: "{term:requirespoint_format}",
	tc_prereqpl: "{term:requirespoints_format}",
	tc_learn: "{term:clicktolearn_stc}",
	tc_unlearn: "{term:rightclicktounlearn_stc}",
	tc_nextrank: "{term:nextrank_colon}",
	tc_inccap: "{term:raiselevelcap_tip}",
	tc_deccap: "{term:decreaselevel_tip}",
	tc_addbon: "{term:beastmastery_tip}",
	tc_rembon: "{term:removebm_tip}",
	tc_masterytiptitle: "{term:masterybonuses_stc}",
	tc_masterytipdesc: "{term:talentmastery_tip}",
	tc_point: "{term:point_lc}",
	tc_points: "{term:points}",
	tc_none: "{term:none}",
	tc_printh: "{term:levelcombo_format}",
	tc_link: "{term:linktothisbuild_stc}",
	tc_resetall: "{term:resetall_stc}",
	tc_resettree: "{term:resettree_stc}",
	tc_resetglyphs: "{term:resetglyphs_stc}",
	tc_lock: "{term:lock}",
	tc_unlock: "{term:unlock}",
	tc_reset: "{term:reset_lc}",
	tc_ptsleft: "{term:pointsleft_colon}",
	tc_ptsspent: "{term:pointsspent_colon}",
	tc_reqlevel: "{term:requiredlevel_colon}",
	tc_levelcap: "{term:levelcap_colon}",
	tc_bonuspts: "{term:bonuspoints_colon}",
	tc_help: "{term:help}",
	tc_import: "{term:import}",
	tc_summary: "{term:summary}",
	tc_restore: "{term:restore}",
	tc_link: "{term:link}",
	tc_print: "{term:print}",
	tc_glyphs: "{term:glyphs}",
	tc_empty: "{term:empty}",
	tc_locked: "{term:locked}",
	tc_majgly: "{term:majorglyph}",
	tc_mingly: "{term:minorglyph}",
	tc_lockgly: "{term:unlockedglyph_format}",
	tc_addgly: "{term:inscribespellbook_tip}",
	tc_remgly: "{term:rightclicktoremove_stc}",
	tc_nonegly: "{term:none}",
	tc_viewtalents: "{term:viewtalenttrees}",
	tc_viewsummary: "{term:viewsummaries}",
	alert_invalidurl: "{term:invalidurl_stc}",
	alert_chooseclass: "{term:chooseaclass_tip}",
	alert_choosefamily: "{term:chooseapetfamily_tip}",
	alert_buildempty: "{term:yourbuildisempty_stc}",
	prompt_importwh: "{term:talentcalcwhurl_tip}",
	prompt_importblizz: "{term:talentcalcblizzurl_tip}",

/*
	tc_rank: "Rank $1/$2",
	tc_tier: "Requires $1 points in $2 Talents",
	tc_prereq: "Requires $1 point in $2",
	tc_prereqpl: "Requires $1 points in $2",
	tc_learn: "Click to learn",
	tc_unlearn: "Right-click to unlearn",
	tc_nextrank: "Next rank: ",
	tc_inccap: "Click to raise the level cap to 85",
	tc_deccap: "Click to decrease the level cap to 80",
	tc_addbon: "Click to add 4 bonus points from<br />the Beast Mastery talent",
	tc_rembon: "Click to remove the bonus<br />points from Beast Mastery",
	tc_masterytiptitle: "Mastery bonuses",
	tc_masterytipdesc: "The talent tree you're specialized in grants 3 bonuses that scale with the number of points spent in that tree. These bonuses stop increasing once 51 points have been spent in that tree.",
	tc_point: "point",
	tc_points: "Points",
	tc_none: "None",
	tc_printh: "Level $1 $2",
	tc_link: "Link to this build",
	tc_resetall: "Reset all",
	tc_resettree: "Reset tree",
	tc_resetglyphs: "Reset glyphs",
	tc_lock: "Lock",
	tc_unlock: "Unlock",
	tc_reset: "reset",
	tc_ptsleft: "Points left: ",
	tc_ptsspent: "Points spent: ",
	tc_reqlevel: "Required level: ",
	tc_levelcap: "Level cap: ",
	tc_bonuspts: "Bonus points: ",
	tc_help: "Help",
	tc_import: "Import",
	tc_summary: "Summary",
	tc_restore: "Restore",
	tc_link: "Link",
	tc_print: "Print",
	tc_glyphs: "Glyphs",
	tc_empty: "Empty",
	tc_locked: "Locked",
	tc_majgly: "Major Glyph",
	tc_mingly: "Minor Glyph",
	tc_lockgly: "Unlocked at level $1",
	tc_addgly: "Click to inscribe your spellbook",
	tc_remgly: "Right-click to remove",
	tc_nonegly: "None",
	tc_viewtalents: "View Talent Trees",
	tc_viewsummary: "View Summaries",
	alert_invalidurl: "Invalid URL.",
	alert_chooseclass: "Please choose a class first.",
	alert_choosefamily: "Please choose a pet family first.",
	alert_buildempty: "Your build is empty.",
	prompt_importwh: "Please paste the URL of a build made with Wowhead's talent calculator:",
	prompt_importblizz: "Please paste the URL of a build made with Blizzard's talent calculator:",
*/