	pr_notice: "{term:profilerhelp_tip}",
	pr_datasource: "{term:profilerdatasource_tip}",
	message_nocharacterselected: "{term:nocharactersselected_stc}",
	message_noprofileselected: "{term:noprofilesselected_stc}",
	message_norowselected: "{term:selectsomeitems_format}",
	message_characterresync: "{term:charactersresync_tip}",
	message_resyncerror: "{term:resyncerror2_tip}",
	message_saveerror: "{term:profilesaveerror_tip}",
	message_saveok: "{term:savesuccessful_stc}",
	message_saveasinvalidname: "{term:invalidname_stc}",
	message_invalidlevel: "{term:deathknightsmin55_tip}",
	message_missingregion: "{term:pleaseselectaregion_stc}",
	message_missingrealm: "{term:pleaseselectarealm_stc}",
	message_missingcharacter: "{term:entercharactername_tip}",
	message_profilenotsaved: "{term:profilenotsaved_format}",
	confirm_linkcharacter: "{term:characterlink_tip}",
	confirm_linkedcharacter: "{term:characterlinked_tip}",
	confirm_unlinkcharacter: "{term:characterunlink_prompt}",
	confirm_deleteprofile: "{term:deleteprofiles_prompt}",
	confirm_deleteprofile2: "{term:deleteprofile_prompt}",
	confirm_privateprofile: "{term:privateprofile_prompt}",
	confirm_publicprofile: "{term:publicprofile_prompt}",
	confirm_newprofile: "{term:newprofile_prompt}",
	confirm_resetexclusions: "{term:resetexcludes_tip}",
	prompt_charlookup: "{term:characterlookup_tip}",
	prompt_nameprofile: "{term:profilename_tip}",
	dialog_notavail: "{term:notavailabletoplayers_stc}",
	dialog_tcg: "{term:obtainedviatcglootredemption_stc}",
	dialog_collector: "{term:rewardfromce_tip}",
	dialog_promo: "{term:obtainedfromapromotion_stc}",
	dialog_nonus: "{term:notavailableonusservers_stc}",
	dialog_faction: "{term:favoredbyoppositefaction_stc}",
	dialog_profession: "{term:requiresanotherprofession_stc}",
	dialog_exclude: "{term:excludeexplain2_tip}",
	dialog_noexalted: "{term:impossibletoreachexalted_stc}",
	dialog_manageexclusions: "{term:managepersonalexclusions}",
	dialog_resetexclusions: "{term:resetallexclusions_stc}",
	tab_arenateams: "{term:arenateams_stc}",
	tab_character: "{term:character}",
	tab_characters: "{term:characters}",
	tab_guilds: "{term:guilds}",
	tab_reputation: "{term:reputation}",
	lvnodata3: "{term:selectcategory_tip}",
	lvnodata4: "{term:noexcludes_tip}",
	lvnote_clicksubcatg: "{term:filtersubcategory_tip}",
	button_save: "{term:save}",
	button_saveas: "{term:saveass}",
	button_bookmark: "{term:bookmark}",
	button_claimchar: "{term:claimcharacter_stc}",
	button_resync: "{term:resync}",
	pr_lookup: "{term:lookup_colon}",
	pr_noneitem: "{term:none}",
	pr_nonegem: "{term:none}",
	pr_noneenchant: "{term:none}",
	pr_nonepet: "{term:none}",
	pr_specifyitem: "{term:specifyitemsearch_tip}",
	pr_searching: "{term:searchingitems_format}",
	pr_noresults: "{term:noresults_format}",
	pr_region: "{term:region_paren}",
	pr_realm: "{term:realm_paren}",
	pr_selectregion: "{term:selectaregion_stc}",
	pr_vendorsin: "{term:vendorsin}",
	pr_yes: "{term:yes}",
	pr_tt_items: "{term:items}",
	pr_tt_enchants: "{term:enchants}",
	pr_tt_gems: "{term:gems}",
	pr_tt_normal: "{term:tenplayer_format}",
	pr_tt_heroic: "{term:twentyfiveplayer_format}",
	pr_tt_earned: "{term:achievementprogress_format}",
	pr_tt_earned2: "{term:killedallbosses_format}",
	pr_tt_progress: "{term:progress}",
	pr_tt_obtained: "{term:totalnumberobtained_label}",
	pr_tt_nodata: "{term:statisticnodata_tip}",
	pr_tt_enchreq: "{term:enchantmentreqlevel_format}",
	pr_tt_new: "{term:newprofile_tip}",
	pr_tt_saveas: "{term:saveprofileas_tip}",
	pr_tt_resync: "{term:characterresync_tip}",
	pr_tt_claim: "{term:claimcharacter_tip}",
	pr_tt_include: "{term:includeexplain_tip}",
	pr_tt_exclude: "{term:excludeexplain_tip}",
	pr_tt_noqexcl: "{term:noquickexclude_tip}",
	pr_tt_excldone: "{term:completebutexcluded_stc}",
	pr_tt_questtip: "{term:untrackedquests_tip}",
	pr_tip_rclkopt: "{term:rightclickslots_tip}",
	pr_tip_sclkopt: "{term:shiftclickslots_tip}",
	pr_tip_rclkopt2: "{term:rightclickenhancements_tip}",
	pr_tip_sclkopt2: "{term:shiftclickenhancements_tip}",
	pr_tip_quests: "{term:untrackedquests2_tip}",
	pr_header_noname: "{term:noname}",
	pr_header_character: "{term:levelcombo2_format}",
	pr_header_edit: "{term:edit}",
	pr_header_armory: "{term:armory}",
	pr_header_help: "{term:help}",
	pr_header_print: "{term:print}",
	pr_header_figureprint: "{term:buyfigureprint}",
	pr_dialog_chardetails: "{term:characterdetails}",
	pr_dialog_name: "{term:name_colon}",
	pr_dialog_level: "{term:level_colon}",
	pr_dialog_class: "{term:class_colon}",
	pr_dialog_race: "{term:race_colon}",
	pr_dialog_gender: "{term:gender_colon}",
	pr_dialog_icon: "{term:icon_colon}",
	pr_dialog_iconeg: "{term:exampleicon_tip}",
	pr_dialog_description: "{term:description_colon}",
	pr_dialog_public: "{term:visibility_colon}",
	pr_qf_quickfacts: "{term:quickfacts}",
	pr_qf_progress: "{term:progress}",
	pr_qf_toc: "{term:tableofcontents}",
	pr_qf_owner: "{term:owner_colon}",
	pr_qf_character: "{term:character_colon}",
	pr_qf_profiles: "{term:profiles_colon}",
	pr_qf_playedtime: "{term:playedtime_colon}",
	pr_qf_gearscore: "{term:gearscore_colon}",
	pr_qf_talents: "{term:talents_colon}",
	pr_qf_achievements: "{term:achievements_colon}",
	pr_qf_xvxteam: "{term:xvxteam_format}",
	pr_qf_updated: "{term:updated}",
	pr_qf_resynced: "{term:resynced}",
	pr_qf_notsaved: "{term:profilenotsaved_tip}",
	pr_qf_raid: "{term:raid}",
	pr_qf_n: "10",
	pr_qf_h: "25",
	menu_charlookup: "{term:lookupbyname_ellipsis}",
	menu_newprofile: "{term:newcustomprofile}",
	menu_chooseclassspec: "{term:chooseclassspec}",
	pr_menu_equip: "{term:equip_ellipsis}",
	pr_menu_replace: "{term:replace_ellipsis}",
	pr_menu_add: "{term:add_ellipsis}",
	pr_menu_unequip: "{term:unequip}",
	pr_menu_remove: "{term:remove}",
	pr_menu_addgem: "{term:addgem_ellipsis}",
	pr_menu_repgem: "{term:replacegem_ellipsis}",
	pr_menu_addenchant: "{term:addenchant_ellipsis_tc}",
	pr_menu_repenchant: "{term:replaceenchant_ellipsis}",
	pr_menu_addsubitem: "{term:addrandomproperty_ellipsis_tc}",
	pr_menu_repsubitem: "{term:replacerandomproperty_ellipsis}",
	pr_menu_extrasock: "{term:extrasocket}",
	pr_menu_display: "{term:displayoncharacter}",
	pr_menu_clearenh: "{term:clearenhancements}",
	pr_menu_links: "{term:links}",
	pr_menu_compare: "{term:compare}",
	pr_menu_upgrades: "{term:findupgrades}",
	pr_menu_whowears: "{term:whowearsthis}",
	pr_queue_unknown: "{term:unknown}",
	pr_queue_noprocess: "{term:queuehalted_tip}",
	pr_queue_resyncreq: "{term:resyncrequested_tip}",
	pr_queue_addqueue: "{term:addingtoqueue_tip}",
	pr_queue_partial: "{term:resyncpartial_tip}",
	pr_queue_status1: "{term:queueposition_tip}",
	pr_queue_status2: "{term:fetchingcharacternow_ellipsis}",
	pr_queue_status3: "{term:characterready_tip}",
	pr_queue_status4: "{term:resyncerror_tip}",
	pr_error_armory0: "{term:errorunknown_stc}",
	pr_error_armory1: "{term:characterdoesnotexist_stc}",
	pr_error_armory2: "{term:characterfailure_tip}",
	pr_error_armory3: "{term:failedtofetchtalents_stc}",
	pr_error_armory4: "{term:failedtofetchskills_stc}",
	pr_error_armory5: "{term:reputationfailure_tip}",
	pr_error_armory6: "{term:achievementfailure_tip}",
	pr_error_armory7: "{term:statisticfailure_tip}",
	pr_error_armory8: "{term:armoryunreachable_tip}",
	pr_inv_title: "{term:gearsummary}",
	pr_inv_missing: "{term:missing_colon}",
	pr_inv_lowlevel: "{term:lowlevel_colon}",
	pr_inv_metareq: "{term:metacondition_colon}",
	pr_inv_item: "{term:item_format}",
	pr_inv_items: "{term:items_format}",
	pr_inv_gem: "{term:gem_format}",
	pr_inv_gems: "{term:gems_format}",
	pr_inv_enchant: "{term:enchant_format}",
	pr_inv_enchants: "{term:enchants_format}",
	pr_inv_socket: "{term:socket_format}",
	pr_inv_sockets: "{term:sockets_format}",
	pr_print_none: "{term:none}",
	pr_print_yes: "{term:yes}",
	pr_print_no: "{term:no}",
	pr_print_normal: "{term:normal}",
	pr_print_heroic: "{term:heroic}",
	pr_stats_warning: "{term:statisticswarning_tip}",
	pr_stats_title: "{term:statistics}",
	pr_stats_base: "{term:base}",
	pr_stats_melee: "{term:melee}",
	pr_stats_ranged: "{term:ranged}",
	pr_stats_spell: "{term:spell}",
	pr_stats_defenses: "{term:defenses}",
	pr_stats_resistances: "{term:resistances}",
	pr_stats_beta: "{term:beta_lc}",
	pr_stats_agi: "{term:agility}",
	pr_stats_arcres: "{term:arcaneresistance_stc}",
	pr_stats_armor: "{term:armor}",
	pr_stats_armorpenpct: "{term:penetration}",
	pr_stats_blockpct: "{term:block}",
	pr_stats_def: "{term:defense}",
	pr_stats_dodgepct: "{term:dodge}",
	pr_stats_energy: "{term:energy}",
	pr_stats_exp: "{term:expertise}",
	pr_stats_firres: "{term:fireresistance_stc}",
	pr_stats_frores: "{term:frostresistance_stc}",
	pr_stats_health: "{term:health}",
	pr_stats_holres: "{term:holyresistance_stc}",
	pr_stats_int: "{term:intellect}",
	pr_stats_mana: "{term:mana}",
	pr_stats_mleatkpwr: "{term:power}",
	pr_stats_mlecritstrkpct: "{term:critical}",
	pr_stats_mlehastepct: "{term:haste}",
	pr_stats_mlehitpct: "{term:hit}",
	pr_stats_natres: "{term:natureresistance_stc}",
	pr_stats_oocmanargn: "{term:manaregen}",
	pr_stats_parrypct: "{term:parry}",
	pr_stats_rage: "{term:rage}",
	pr_stats_resipct: "{term:resilience}",
	pr_stats_rgdatkpwr: "{term:power}",
	pr_stats_rgdcritstrkpct: "{term:critical}",
	pr_stats_rgdhastepct: "{term:haste}",
	pr_stats_rgdhitpct: "{term:hit}",
	pr_stats_runic: "{term:runicpower}",
	pr_stats_shares: "{term:shadowresistance_stc}",
	pr_stats_spi: "{term:spirit}",
	pr_stats_splcritstrkpct: "{term:critical}",
	pr_stats_spldmg: "{term:bonusdamage}",
	pr_stats_splhastepct: "{term:haste}",
	pr_stats_splheal: "{term:bonushealing}",
	pr_stats_splhitpct: "{term:hit}",
	pr_stats_splpen: "{term:penetration}",
	pr_stats_sta: "{term:stamina}",
	pr_stats_str: "{term:strength}",
	pr_statstt_arc: "{term:arcane}",
	pr_statstt_fir: "{term:fire}",
	pr_statstt_fro: "{term:frost}",
	pr_statstt_hol: "{term:holy}",
	pr_statstt_nat: "{term:nature}",
	pr_statstt_sha: "{term:shadow}",
	pr_statstt_agi: "{term:agility_tip}",
	pr_statstt_armor: "{term:armor2_format}",
	pr_statstt_armor2: "{term:armorpet_tip}",
	pr_statstt_armorpenpct: "{term:armorpenetrationrating_tip}",
	pr_statstt_blockpct: "{term:blockrating_tip}",
	pr_statstt_def: "{term:defenserating_tip}",
	pr_statstt_dodgepct: '{term:dodgerating_tip}',
	pr_statstt_exp: "{term:expertiserating_tip}",
	pr_statstt_int: "{term:intellect2_tip}",
	pr_statstt_int2: "{term:intellect_tip}",
	pr_statstt_mleatkpwr: "{term:meleeattackpower_tip}",
	pr_statstt_mlecritstrkpct: "{term:meleecritrating_tip}",
	pr_statstt_mlehastepct: "{term:meleehasterating_tip}",
	pr_statstt_mlehitpct: "{term:meleehitrating_tip}",
	pr_statstt_oocmanargn: "{term:manaregen_tip}",
	pr_statstt_parrypct: '{term:parryrating_tip}',
	pr_statstt_resipct: '{term:resiliencerating_tip}',
	pr_statstt_resist: "{term:schoolresistance_tip}",
	pr_statstt_rgdatkpwr: "{term:rangedattackpower_format}",
	pr_statstt_rgdatkpwr2: "{term:rangedattackpoerpet_tip}",
	pr_statstt_rgdcritstrkpct: "{term:rangedcritrating_tip}",
	pr_statstt_rgdhastepct: "{term:rangedhasterating_tip}",
	pr_statstt_rgdhitpct: "{term:rangedhitrating_tip}",
	pr_statstt_spi: "{term:spirit_tip}",
	pr_statstt_splcritstrkpct: "{term:spellcritstrikerating_tip}",
	pr_statstt_spldmg: "$1",
	pr_statstt_spldmg2: "{term:spelldamagepet_tip}",
	pr_statstt_splhastepct: "{term:spellhasterating_tip}",
	pr_statstt_splheal: "{term:spellhealing_format}",
	pr_statstt_splhitpct: "{term:spellhitrating_tip}",
	pr_statstt_splpen: "{term:spellpenetration_format}",
	pr_statstt_sta: "{term:stamina_tip}",
	pr_statstt_sta2: "{term:staminapet_tip}",
	pr_statstt_str: "{term:attackpower_format}",
	pr_statstt_str2: "{term:strength_tip}",
	pr_ach_overall: "{term:overallprogress}",
	pr_note_color: "{term:color_colon}",
	pr_note_source: "{term:source_colon}",
	pr_note_view: "{term:view_colon}",
	pr_note_type: "{term:type_colon}",
	pr_note_name: "{term:name_colon}",
	pr_note_family: "{term:family_colon}",
	pr_note_sort: "{term:sortby_colon}",
	ddaysago: "{term:daysago_format}",
	pr_note_all: "{term:all}",
	pr_note_bc: "{term:burningcrusade_abbrev}",
	pr_note_subcategories: "{term:subcategories}",
	pr_note_earned: "{term:earned}",
	pr_note_complete: "{term:complete}",
	pr_note_incomplete: "{term:incomplete}",
	pr_note_excluded: "{term:excluded}",
	pr_note_items: "{term:items}",
	pr_note_match: "{term:match}",
	pr_note_profs: "{term:professions}",
	pr_note_wotlk: "{term:wrathofthelichking_abbrev}",
	pr_note_usable: "{term:usable}",
	pr_note_known: "{term:known}",
	pr_note_missing: "{term:missing}",
	pr_note_normal: "{term:normal}",
	pr_note_exotic: "{term:exotic}",
	pr_note_gearscore: "{term:gearscore_stc}",
	pr_note_weighted: "{term:weighted}",

/*
	pr_notice: 'First time? &ndash; Don\'t be shy! Just check out our <a href="/help=profiler" target="_blank">Help page</a>! &nbsp; <small class="q0"><a href="javascript:;">close</a></small>',
	pr_datasource: 'Data in this tab was last updated $2 by <a href="/user=$1" target="_blank">$1</a> using the <a href="/client" target="_blank">Wowhead Client</a>.',
	message_nocharacterselected: "No characters selected.",
	message_noprofileselected: "No profiles selected.",
	message_norowselected: "Please select one or more items to $1 from this list.",
	message_characterresync: "An Armory resync has been requested for the selected characters.",
	message_resyncerror: "An error occurred when resyncing this character:",
	message_saveerror: "Error: Your profile could not be saved. Wowhead accounts have a limit of ten profiles. Please delete some from your user page, or upgrade your account to Premium for more space.",
	message_saveok: "Save successful!",
	message_saveasinvalidname: "Invalid name.",
	message_invalidlevel: "Death Knights must be at least level 55.",
	message_missingregion: "Please select a region.",
	message_missingrealm: "Please select a realm.",
	message_missingcharacter: "Please enter a character name.",
	message_profilenotsaved: "$1Warning:$2 Your changes haven't been saved!",
	confirm_linkcharacter: "This character will be added to your list of characters.\n\nDo you want to continue?",
	confirm_linkedcharacter: "This character has been added to your list.\n\nDo you want to be taken there?",
	confirm_unlinkcharacter: "Are you sure that you want to remove the selected characters from your list?",
	confirm_deleteprofile: "Are you sure that you want to delete the selected profiles?",
	confirm_deleteprofile2: "Are you sure that you want to delete this profile?",
	confirm_privateprofile: "Are you sure that you want to make the selected profiles private?",
	confirm_publicprofile: "Are you sure that you want to make the selected profiles public?",
	confirm_newprofile: "Create a new profile?\n\nYou will be redirected upon saving the profile.",
	confirm_resetexclusions: "This will reset your exclusion settings to the default. Are you sure you want to proceed?",
	prompt_charlookup: "Please enter the name of the character you wish to view:",
	prompt_nameprofile: "Please provide a name for this profile.\n(i.e. Resistance Gear, PvP Set, Wishlist, etc.)\n\nYou will be redirected upon saving the profile.",
	dialog_notavail: "Not available to players",
	dialog_tcg: "Obtained via TCG loot redemption",
	dialog_collector: "Reward from a Collector's Edition",
	dialog_promo: "Obtained from a promotion",
	dialog_nonus: "Not available on US servers",
	dialog_faction: "Favored by opposite faction",
	dialog_profession: "Requires another profession",
	dialog_exclude: "Excluding entries lets you remove things you can't or don't plan on completing. Individual inclusions/exclusions will override the quick categories below.<br /><br />Your exclusion settings are shared between all characters.",
	dialog_noexalted: "Impossible to reach exalted",
	dialog_manageexclusions: "Manage Personal Exclusions",
	dialog_resetexclusions: "Reset all exclusions",
	tab_arenateams: "Arena teams",
	tab_character: "Character",
	tab_characters: "Characters",
	tab_guilds: "Guilds",
	tab_reputation: "Reputation",
	lvnodata3: "Please select a category above.",
	lvnodata4: "You haven't excluded any entries.",
	lvnote_clicksubcatg: "Click on a subcategory below to filter the other tabs.",
	button_save: "Save",
	button_saveas: "Save as",
	button_bookmark: "Bookmark",
	button_claimchar: "Claim character",
	button_resync: "Resync",
	pr_lookup: "Lookup: ",
	pr_noneitem: "None",
	pr_nonegem: "None",
	pr_noneenchant: "None",
	pr_nonepet: "None",
	pr_specifyitem: "Please enter an item name to search for.",
	pr_searching: 'Searching for items named "$1"...',
	pr_noresults: 'No results found for "$1"!',
	pr_region: "(Region)",
	pr_realm: "(Realm)",
	pr_selectregion: "Select a region",
	pr_vendorsin: "Vendors in ",
	pr_yes: "Yes",
	pr_tt_items: "Items",
	pr_tt_enchants: "Enchants",
	pr_tt_gems: "Gems",
	pr_tt_normal: "$1 (10-player)",
	pr_tt_heroic: "$1 (25-player)",
	pr_tt_earned: "$1 has earned $2 of $3 achievements ($4%).",
	pr_tt_earned2: "$1 has killed all bosses in this instance.",
	pr_tt_progress: "Progress",
	pr_tt_obtained: "Total number obtained: $1",
	pr_tt_nodata: "This statistic is not currently available in-game<br />and cannot be tracked by Wowhead.",
	pr_tt_enchreq: "Enchantment Requires Level $1",
	pr_tt_new: '<b class="q">New</b><br />Create a new custom profile from scratch.',
	pr_tt_saveas: '<b class="q">Save as</b><br />Save the current character as a custom<br />profile tied to your Wowhead account.',
	pr_tt_resync: '<b class="q">Resync</b><br />Resync the character with the latest<br />version available on the Armory.',
	pr_tt_claim: '<b class="q">Claim character</b><br />Add this character to your list of characters.',
	pr_tt_include: '<b class="q">Include</b><br />Move selected entries out of your exclusion list.',
	pr_tt_exclude: '<b class="q">Exclude</b><br />Move selected entries to your exclusion list.<br />This can be useful to hide things you don\'t<br />consider important to reach 100% completion.',
	pr_tt_noqexcl: '<div class="pad"><span class="q10">Note:</span> Quick exclusions aren\'t currently available for this tab.',
	pr_tt_excldone: "Complete but excluded",
	pr_tt_questtip: "Repeatable quests and quests that don't<br />appear in your quest log aren't tracked.",
	pr_tip_rclkopt: "Tip: Right-click slots for more options.",
	pr_tip_sclkopt: "Tip: Shift-click items for more options.",
	pr_tip_rclkopt2: "Tip: Right-click items, gems and enchants for more options.",
	pr_tip_sclkopt2: "Tip: Shift-click items, gems and enchants for more options.",
	pr_tip_quests: "Note: <span class=\"tip\">Certain</span> quests aren't tracked by Blizzard's API.",
	pr_header_noname: "Noname",
	pr_header_character: 'Level $1 <a href="/race=$4">$2</a> <a href="/class=$5" class="c$5">$3</a>',
	pr_header_edit: "Edit",
	pr_header_armory: "Armory",
	pr_header_help: "Help",
	pr_header_print: "Print",
	pr_header_figureprint: "Buy FigurePrint",
	pr_dialog_chardetails: "Character Details",
	pr_dialog_name: "Name: ",
	pr_dialog_level: "Level: ",
	pr_dialog_class: "Class: ",
	pr_dialog_race: "Race: ",
	pr_dialog_gender: "Gender: ",
	pr_dialog_icon: "Icon: ",
	pr_dialog_iconeg: "e.g. INV_Axe_54",
	pr_dialog_description: "Description: ",
	pr_dialog_public: "Visibility: ",
	pr_qf_quickfacts: "Quick Facts",
	pr_qf_progress: "Progress",
	pr_qf_toc: "Table of Contents",
	pr_qf_owner: "Owner: ",
	pr_qf_character: "Character: ",
	pr_qf_profiles: "Profiles: ",
	pr_qf_playedtime: "Played time: ",
	pr_qf_gearscore: "Gear score: ",
	pr_qf_talents: "Talents: ",
	pr_qf_achievements: "Achievements: ",
	pr_qf_xvxteam: "$1v$1 team: ",
	pr_qf_updated: "Updated ",
	pr_qf_resynced: "Resynced ",
	pr_qf_notsaved: "Profile has not been saved!",
	pr_qf_raid: "Raid",
	pr_qf_n: "10",
	pr_qf_h: "25",
	menu_charlookup: "Lookup by name...",
	menu_newprofile: "New Custom Profile",
	menu_chooseclassspec: "Choose Your Class/Spec",
	pr_menu_equip: "Equip...",
	pr_menu_replace: "Replace...",
	pr_menu_add: "Add...",
	pr_menu_unequip: "Unequip",
	pr_menu_remove: "Remove",
	pr_menu_addgem: "Add Gem...",
	pr_menu_repgem: "Replace Gem...",
	pr_menu_addenchant: "Add Enchant...",
	pr_menu_repenchant: "Replace Enchant...",
	pr_menu_addsubitem: "Add Random Property...",
	pr_menu_repsubitem: "Replace Random Property...",
	pr_menu_extrasock: "Extra Socket",
	pr_menu_display: "Display on Character",
	pr_menu_clearenh: "Clear Enhancements",
	pr_menu_links: "Links",
	pr_menu_compare: "Compare",
	pr_menu_upgrades: "Find Upgrades",
	pr_menu_whowears: "Who Wears This?",
	pr_queue_unknown: "Unknown",
	pr_queue_noprocess: "The queue is not currently running.",
	pr_queue_resyncreq: "<b>An Armory resync for this character has been requested.</b>",
	pr_queue_addqueue: "Adding character to the Armory queue...",
	pr_queue_partial: "<b>This character was partially retrieved, so a full Armory resync has been requested.</b>",
	pr_queue_status1: "Position in queue: <b>$1</b> &ndash; Estimated time: <b>$2</b>",
	pr_queue_status2: "Fetching character now...",
	pr_queue_status3: 'Character is ready! <a href="/$3" rel="np">Reload profile</a>',
	pr_queue_status4: 'Unable to resync from the Armory: $1. Try <a href="javascript:;">resyncing</a> this character again.',
	pr_error_armory0: "Error unknown",
	pr_error_armory1: "Character does not exist",
	pr_error_armory2: "Failed to fetch character",
	pr_error_armory3: "Failed to fetch talents",
	pr_error_armory4: "Failed to fetch skills",
	pr_error_armory5: "Failed to fetch reputations",
	pr_error_armory6: "Failed to fetch achievements",
	pr_error_armory7: "Failed to fetch statistics",
	pr_error_armory8: "The Armory could not be reached",
	pr_inv_title: "Gear Summary",
	pr_inv_missing: "Missing: ",
	pr_inv_lowlevel: "Low level: ",
	pr_inv_metareq: "Meta condition: ",
	pr_inv_item: "$1 item",
	pr_inv_items: "$1 items",
	pr_inv_gem: "$1 gem",
	pr_inv_gems: "$1 gems",
	pr_inv_enchant: "$1 enchant",
	pr_inv_enchants: "$1 enchants",
	pr_inv_socket: "$1 socket",
	pr_inv_sockets: "$1 sockets",
	pr_print_none: "None",
	pr_print_yes: "Yes",
	pr_print_no: "No",
	pr_print_normal: "Normal",
	pr_print_heroic: "Heroic",
	pr_stats_warning: "Warning: Some statistics (particularly dodge) may not be entirely accurate.",
	pr_stats_title: "Statistics",
	pr_stats_base: "Base",
	pr_stats_melee: "Melee",
	pr_stats_ranged: "Ranged",
	pr_stats_spell: "Spell",
	pr_stats_defenses: "Defenses",
	pr_stats_resistances: "Resistances",
	pr_stats_beta: "beta",
	pr_stats_agi: "Agility",
	pr_stats_arcres: "Arcane resistance",
	pr_stats_armor: "Armor",
	pr_stats_armorpenpct: "Penetration",
	pr_stats_blockpct: "Block",
	pr_stats_def: "Defense",
	pr_stats_dodgepct: "Dodge",
	pr_stats_energy: "Energy",
	pr_stats_exp: "Expertise",
	pr_stats_firres: "Fire resistance",
	pr_stats_frores: "Frost resistance",
	pr_stats_health: "Health",
	pr_stats_holres: "Holy resistance",
	pr_stats_int: "Intellect",
	pr_stats_mana: "Mana",
	pr_stats_mleatkpwr: "Power",
	pr_stats_mlecritstrkpct: "Critical",
	pr_stats_mlehastepct: "Haste",
	pr_stats_mlehitpct: "Hit",
	pr_stats_natres: "Nature resistance",
	pr_stats_oocmanargn: "Mana Regen",
	pr_stats_parrypct: "Parry",
	pr_stats_rage: "Rage",
	pr_stats_resipct: "Resilience",
	pr_stats_rgdatkpwr: "Power",
	pr_stats_rgdcritstrkpct: "Critical",
	pr_stats_rgdhastepct: "Haste",
	pr_stats_rgdhitpct: "Hit",
	pr_stats_runic: "Runic Power",
	pr_stats_shares: "Shadow resistance",
	pr_stats_spi: "Spirit",
	pr_stats_splcritstrkpct: "Critical",
	pr_stats_spldmg: "Bonus Damage",
	pr_stats_splhastepct: "Haste",
	pr_stats_splheal: "Bonus Healing",
	pr_stats_splhitpct: "Hit",
	pr_stats_splpen: "Penetration",
	pr_stats_sta: "Stamina",
	pr_stats_str: "Strength",
	pr_statstt_arc: "Arcane",
	pr_statstt_fir: "Fire",
	pr_statstt_fro: "Frost",
	pr_statstt_hol: "Holy",
	pr_statstt_nat: "Nature",
	pr_statstt_sha: "Shadow",
	pr_statstt_agi: "Increases attack power by $1<br />Increases physical critical hit chance by $2%<br />Increases armor by $3",
	pr_statstt_armor: "Reduces physical damage taken by $2%",
	pr_statstt_armor2: "Reduces physical damage taken by $2%<br />Increases your pet's armor by $1",
	pr_statstt_armorpenpct: '<span class="q2">Armor penetration rating $1 (+$2% armor penetration)</span><br />Reduces enemy armor by $3%',
	pr_statstt_blockpct: '<span class="q2">Block rating $1 (+$2% block)</span><br />Increases chance to block by $4%<br />Your block stops $3 damage',
	pr_statstt_def: '<span class="q2">Defense rating $1 (+$2 defense)</span><br />Increases chance to dodge, block and parry by $3%<br />Decreases chance to be hit and critically hit by $4%',
	pr_statstt_dodgepct: '{term:dodgerating_tip}',
	pr_statstt_exp: '<span class="q2">Expertise rating $1 (+$2 expertise)</span><br />Reduces chance to be dodged or parried by $3%',
	pr_statstt_int: "Increases mana by $1<br />Increases spell critical hit chance by $2%",
	pr_statstt_int2: "Increases mana by $1<br />Increases spell critical hit chance by $2%<br />Increases your pet's intellect by $3",
	pr_statstt_mleatkpwr: "Increases damage with melee weapons by $1 per second",
	pr_statstt_mlecritstrkpct: '<span class="q2">Crit rating $1 (+$2% crit chance)</span><br />Increases melee critical strike chance by $3%',
	pr_statstt_mlehastepct: '<span class="q2">Haste rating $1 (+$2% haste)</span><br />Increases melee attack speed by $3%',
	pr_statstt_mlehitpct: '<span class="q2">Hit rating $1 (+$2% hit chance)</span><br />Increases melee chance to hit a level $4 target by $3%',
	pr_statstt_oocmanargn: "$1 mana regenerated every 5 seconds while not casting<br />$2 mana regenerated every 5 seconds while casting",
	pr_statstt_parrypct: '{term:parryrating_tip}',
	pr_statstt_resipct: '{term:resiliencerating_tip}',
	pr_statstt_resist: "Increases resistance to $1-based attacks, spells, and abilities.<br />Average resistance against spells cast by level $3: $1%",
	pr_statstt_rgdatkpwr: "Increases damage with ranged weapons by $1 per second",
	pr_statstt_rgdatkpwr2: "Increases damage with ranged weapons by $1 per second<br />Increases your pet's attack power by $2<br />Increases your pet's spell damage by $3",
	pr_statstt_rgdcritstrkpct: '<span class="q2">Crit rating $1 (+$2% crit chance)</span><br />Increases ranged critical strike chance by $3%',
	pr_statstt_rgdhastepct: '<span class="q2">Haste rating $1 (+$2% haste)</span><br />Increases ranged attack speed by $3%',
	pr_statstt_rgdhitpct: '<span class="q2">Hit rating $1 (+$2% hit chance)</span><br />Increases ranged chance to hit a level $4 target by $3%',
	pr_statstt_spi: "Increases health regeneration by $1 per 5 seconds while not in combat<br />Increases mana regeneration by $2 per 5 seconds while not casting",
	pr_statstt_splcritstrkpct: '<span class="q2">Crit rating $2 (+$3% crit chance)</span><br />$1',
	pr_statstt_spldmg: "$1",
	pr_statstt_spldmg2: "$1<br />Increases your pet's attack power by $3<br />Increases your pet's spell damage by $4",
	pr_statstt_splhastepct: '<span class="q2">Haste rating $1 (+$2% haste)</span><br />Increases spell casting speed by $3%',
	pr_statstt_splheal: "Increases healing by up to $1",
	pr_statstt_splhitpct: '<span class="q2">Hit rating $1 (+$2% hit chance)</span><br />Increases spell chance to hit a level $4 target by $3%',
	pr_statstt_splpen: "Reduces enemy resistances by $1",
	pr_statstt_sta: "Increases health by $1",
	pr_statstt_sta2: "Increases health by $1<br />Increases your pet's stamina by $2",
	pr_statstt_str: "Increases attack power by $1",
	pr_statstt_str2: "Increases attack power by $1<br />Increases block value by $2",
	pr_ach_overall: "Overall Progress",
	pr_note_color: "Color: ",
	pr_note_source: "Source: ",
	pr_note_view: "View: ",
	pr_note_type: "Type: ",
	pr_note_name: "Name: ",
	pr_note_family: "Family: ",
	pr_note_sort: "Sort by: ",
	ddaysago: "$1 days ago",
	pr_note_all: "All",
	pr_note_bc: "BC",
	pr_note_subcategories: "Subcategories",
	pr_note_earned: "Earned",
	pr_note_complete: "Complete",
	pr_note_incomplete: "Incomplete",
	pr_note_excluded: "Excluded",
	pr_note_items: "Items",
	pr_note_match: "Match",
	pr_note_profs: "Professions",
	pr_note_wotlk: "WotLK",
	pr_note_usable: "Usable",
	pr_note_known: "Known",
	pr_note_missing: "Missing",
	pr_note_normal: "Normal",
	pr_note_exotic: "Exotic",
	pr_note_gearscore: "Gear score",
	pr_note_weighted: "Weighted",
*/