	fonavtopic: "{term:topic_format}",
	fonavtopics: "{term:topics_format}",
	fonavpost: "{term:post_format}",
	fonavposts: "{term:posts_format}",
	foboards: {
		0: "{term:wowgeneral}",
		21: "{term:cataclysm}",
		16: "{term:wowhelp}",
		20: "{term:theorycrafting}",
		14: "{term:dungeonsandraids}",
		15: "{term:pvp}",
		18: "{term:deathknight}",
		3: "{term:druid}",
		4: "{term:hunter}",
		6: "{term:mage}",
		7: "{term:paladin}",
		8: "{term:priest}",
		5: "{term:rogue}",
		9: "{term:shaman}",
		10: "{term:warlock}",
		11: "{term:warrior}",
		13: "{term:professions}",
		12: "{term:uiandmacros}",
		19: "{term:loreandroleplaying}",
		17: "{term:guildrecruitment}",
		2: "{term:offtopic}",
		1: "{term:wowheadfeedback}",
		22: "{term:wowmagazine}",
		23: "{term:starcraft2}",
		24: "{term:diablo3}"
	},
	lvboard_by: "{term:by}",
	lvboard_pages: "{term:pages_colon}",
	lvtopic_whuser: "{term:wowheaduser}",
	lvtopic_joined: "{term:joined}",
	lvtopic_posts: "{term:posts_colon}",
	lvtopic_role: "{term:role_colon}",
	lvtopic_roles: "{term:roles_colon}",
	lvtopic_edit: "{term:edit}",
	lvtopic_delete: "{term:delete}",
	lvtopic_quote: "{term:quote}",
	lvtopic_reply: "{term:reply}",
	lvtopic_by: "{term:by}",
	lvtopic_lastedit: "{term:lasteditedby_stc}",
	message_postdeleted: "{term:postdeleted_tip}",
	message_allow5min: "{term:allow5min_tip}",
	message_topicsubject: "{term:topicsubject_tip}",
	message_subjectlimit: "{term:subjectlength_tip}",
	message_topicrenamed: "{term:topicrenamed_tip}",
	message_topiclocked: "{term:topiclocked_tip}",
	message_topicunlocked: "{term:topicunlocked_tip}",
	message_topicdeleted: "{term:topicdeleted_tip}",
	message_topicundeleted: "{term:topicundeleted_tip}",
	confirm_deletepost: "{term:deletepost_prompt}",
	prompt_renametopic: "{term:topicrename_tip}",

/*
	fonavtopic: "$1 topic",
	fonavtopics: "$1 topics",
	fonavpost: "$1 post",
	fonavposts: "$1 posts",
	foboards: {
		0: "WoW General",
		21: "Cataclysm",
		16: "WoW Help",
		20: "Theorycrafting",
		14: "Dungeons & Raids",
		15: "PvP",
		18: "Death Knight",
		3: "Druid",
		4: "Hunter",
		6: "Mage",
		7: "Paladin",
		8: "Priest",
		5: "Rogue",
		9: "Shaman",
		10: "Warlock",
		11: "Warrior",
		13: "Professions",
		12: "UI & Macros",
		19: "Lore & Roleplaying",
		17: "Guild Recruitment",
		2: "Off-Topic",
		1: "Wowhead Feedback",
		22: "WoW Official Magazine",
		23: "StarCraft II",
		24: "Diablo III"
	},
	lvboard_by: "By ",
	lvboard_pages: "Pages: ",
	lvtopic_whuser: "Wowhead User",
	lvtopic_joined: "Joined ",
	lvtopic_posts: "Posts: ",
	lvtopic_role: "Role: ",
	lvtopic_roles: "Roles: ",
	lvtopic_edit: "Edit",
	lvtopic_delete: "Delete",
	lvtopic_quote: "Quote",
	lvtopic_reply: "Reply",
	lvtopic_by: "By ",
	lvtopic_lastedit: "Last edited by ",
	message_postdeleted: "The post is now deleted.",
	message_allow5min: "Please allow up to 5 minutes for this to be reflected on the site.",
	message_topicsubject: "Please enter a subject for your topic.",
	message_subjectlimit: "Subjects cannot have more than 100 characters.",
	message_topicrenamed: "The topic has been renamed.",
	message_topiclocked: "The topic is now locked.",
	message_topicunlocked: "The topic is no longer locked.",
	message_topicdeleted: "The topic is now deleted.",
	message_topicundeleted: "The topic is no longer deleted.",
	confirm_deletepost: "Are you sure you want to delete this post?",
	prompt_renametopic: "You may set a new subject for this topic:",
*/