	fidropdowns: {
		yn: [
			[1, "Yes"],
			[2, "No"]],
		num: [
			[1, ">"],
			[2, ">="],
			[3, "="],
			[4, "<="],
			[5, "<"]],
		side: [
			[1, "Yes"],
			[2, "Alliance"],
			[3, "Horde"],
			[4, "Both"],
			[5, "No"]],
		faction: [
			[1037, "Alliance Vanguard"],
			[1106, "Argent Crusade"],
			[529, "Argent Dawn"],
			[1012, "Ashtongue Deathsworn"],
			[87, "Bloodsail Buccaneers"],
			[21, "Booty Bay"],
			[910, "Brood of Nozdormu"],
			[609, "Cenarion Circle"],
			[942, "Cenarion Expedition"],
			[909, "Darkmoon Faire"],
			[530, "Darkspear Trolls"],
			[69, "Darnassus"],
			[577, "Everlook"],
			[930, "Exodar"],
			[1068, "Explorers' League"],
			[1104, "Frenzyheart Tribe"],
			[729, "Frostwolf Clan"],
			[369, "Gadgetzan"],
			[92, "Gelkis Clan Centaur"],
			[54, "Gnomeregan Exiles"],
			[946, "Honor Hold"],
			[1052, "Horde Expedition"],
			[749, "Hydraxian Waterlords"],
			[47, "Ironforge"],
			[989, "Keepers of Time"],
			[1090, "Kirin Tor"],
			[1098, "Knights of the Ebon Blade"],
			[978, "Kurenai"],
			[1011, "Lower City"],
			[93, "Magram Clan Centaur"],
			[1015, "Netherwing"],
			[1038, "Ogri'la"],
			[76, "Orgrimmar"],
			[470, "Ratchet"],
			[349, "Ravenholdt"],
			[1031, "Sha'tari Skyguard"],
			[1077, "Shattered Sun Offensive"],
			[809, "Shen'dralar"],
			[911, "Silvermoon City"],
			[890, "Silverwing Sentinels"],
			[970, "Sporeggar"],
			[730, "Stormpike Guard"],
			[72, "Stormwind"],
			[70, "Syndicate"],
			[932, "The Aldor"],
			[1156, "The Ashen Verdict"],
			[933, "The Consortium"],
			[510, "The Defilers"],
			[1126, "The Frostborn"],
			[1067, "The Hand of Vengeance"],
			[1073, "The Kalu'ak"],
			[509, "The League of Arathor"],
			[941, "The Mag'har"],
			[1105, "The Oracles"],
			[990, "The Scale of the Sands"],
			[934, "The Scryers"],
			[935, "The Sha'tar"],
			[1094, "The Silver Covenant"],
			[1119, "The Sons of Hodir"],
			[1124, "The Sunreavers"],
			[1064, "The Taunka"],
			[967, "The Violet Eye"],
			[1091, "The Wyrmrest Accord"],
			[59, "Thorium Brotherhood"],
			[947, "Thrallmar"],
			[81, "Thunder Bluff"],
			[576, "Timbermaw Hold"],
			[922, "Tranquillien"],
			[68, "Undercity"],
			[1050, "Valiance Expedition"],
			[1085, "Warsong Offensive"],
			[889, "Warsong Outriders"],
			[589, "Wintersaber Trainers"],
			[270, "Zandalar Tribe"]],
		zone: [
			[4494, "Ahn'kahet: The Old Kingdom"],
			[36, "Alterac Mountains"],
			[2597, "Alterac Valley"],
			[3358, "Arathi Basin"],
			[45, "Arathi Highlands"],
			[331, "Ashenvale"],
			[3790, "Auchenai Crypts"],
			[4277, "Azjol-Nerub"],
			[16, "Azshara"],
			[3524, "Azuremyst Isle"],
			[3, "Badlands"],
			[3959, "Black Temple"],
			[719, "Blackfathom Deeps"],
			[1584, "Blackrock Depths"],
			[25, "Blackrock Mountain"],
			[1583, "Blackrock Spire"],
			[2677, "Blackwing Lair"],
			[3702, "Blade's Edge Arena"],
			[3522, "Blade's Edge Mountains"],
			[4, "Blasted Lands"],
			[3525, "Bloodmyst Isle"],
			[3537, "Borean Tundra"],
			[46, "Burning Steppes"],
			[1941, "Caverns of Time"],
			[3905, "Coilfang Reservoir"],
			[4024, "Coldarra"],
			[2817, "Crystalsong Forest"],
			[4395, "Dalaran"],
			[4378, "Dalaran Arena"],
			[279, "Dalaran Crater"],
			[148, "Darkshore"],
			[393, "Darkspear Strand"],
			[1657, "Darnassus"],
			[41, "Deadwind Pass"],
			[2257, "Deeprun Tram"],
			[405, "Desolace"],
			[2557, "Dire Maul"],
			[65, "Dragonblight"],
			[4196, "Drak'Tharon Keep"],
			[1, "Dun Morogh"],
			[14, "Durotar"],
			[10, "Duskwood"],
			[15, "Dustwallow Marsh"],
			[139, "Eastern Plaguelands"],
			[12, "Elwynn Forest"],
			[3430, "Eversong Woods"],
			[3820, "Eye of the Storm"],
			[361, "Felwood"],
			[357, "Feralas"],
			[3433, "Ghostlands"],
			[721, "Gnomeregan"],
			[394, "Grizzly Hills"],
			[3923, "Gruul's Lair"],
			[4416, "Gundrak"],
			[4272, "Halls of Lightning"],
			[4820, "Halls of Reflection"],
			[4264, "Halls of Stone"],
			[3483, "Hellfire Peninsula"],
			[3562, "Hellfire Ramparts"],
			[267, "Hillsbrad Foothills"],
			[495, "Howling Fjord"],
			[4742, "Hrothgar's Landing"],
			[3606, "Hyjal Summit"],
			[210, "Icecrown"],
			[4812, "Icecrown Citadel"],
			[1537, "Ironforge"],
			[4710, "Isle of Conquest"],
			[4080, "Isle of Quel'Danas"],
			[3457, "Karazhan"],
			[38, "Loch Modan"],
			[4131, "Magisters' Terrace"],
			[3836, "Magtheridon's Lair"],
			[3792, "Mana-Tombs"],
			[2100, "Maraudon"],
			[2717, "Molten Core"],
			[493, "Moonglade"],
			[215, "Mulgore"],
			[3518, "Nagrand"],
			[3698, "Nagrand Arena"],
			[3456, "Naxxramas"],
			[3523, "Netherstorm"],
			[2367, "Old Hillsbrad Foothills"],
			[2159, "Onyxia's Lair"],
			[1637, "Orgrimmar"],
			[4813, "Pit of Saron"],
			[4298, "Plaguelands: The Scarlet Enclave"],
			[2437, "Ragefire Chasm"],
			[722, "Razorfen Downs"],
			[491, "Razorfen Kraul"],
			[44, "Redridge Mountains"],
			[3429, "Ruins of Ahn'Qiraj"],
			[3968, "Ruins of Lordaeron"],
			[796, "Scarlet Monastery"],
			[2057, "Scholomance"],
			[51, "Searing Gorge"],
			[3607, "Serpentshrine Cavern"],
			[3791, "Sethekk Halls"],
			[3789, "Shadow Labyrinth"],
			[209, "Shadowfang Keep"],
			[3520, "Shadowmoon Valley"],
			[3703, "Shattrath City"],
			[3711, "Sholazar Basin"],
			[1377, "Silithus"],
			[3487, "Silvermoon City"],
			[130, "Silverpine Forest"],
			[3679, "Skettis"],
			[406, "Stonetalon Mountains"],
			[1519, "Stormwind City"],
			[4384, "Strand of the Ancients"],
			[33, "Stranglethorn Vale"],
			[2017, "Stratholme"],
			[1417, "Sunken Temple"],
			[4075, "Sunwell Plateau"],
			[8, "Swamp of Sorrows"],
			[440, "Tanaris"],
			[141, "Teldrassil"],
			[3845, "Tempest Keep"],
			[3428, "Temple of Ahn'Qiraj"],
			[3519, "Terokkar Forest"],
			[3848, "The Arcatraz"],
			[17, "The Barrens"],
			[2366, "The Black Morass"],
			[3840, "The Black Temple"],
			[3713, "The Blood Furnace"],
			[3847, "The Botanica"],
			[4100, "The Culling of Stratholme"],
			[1581, "The Deadmines"],
			[3557, "The Exodar"],
			[4500, "The Eye of Eternity"],
			[4809, "The Forge of Souls"],
			[47, "The Hinterlands"],
			[3849, "The Mechanar"],
			[4265, "The Nexus"],
			[4493, "The Obsidian Sanctum"],
			[4228, "The Oculus"],
			[4406, "The Ring of Valor"],
			[3714, "The Shattered Halls"],
			[3717, "The Slave Pens"],
			[3715, "The Steamvault"],
			[717, "The Stockade"],
			[67, "The Storm Peaks"],
			[3716, "The Underbog"],
			[457, "The Veiled Sea"],
			[4415, "The Violet Hold"],
			[400, "Thousand Needles"],
			[1638, "Thunder Bluff"],
			[1216, "Timbermaw Hold"],
			[85, "Tirisfal Glades"],
			[4723, "Trial of the Champion"],
			[4722, "Trial of the Crusader"],
			[1337, "Uldaman"],
			[4273, "Ulduar"],
			[490, "Un'Goro Crater"],
			[1497, "Undercity"],
			[206, "Utgarde Keep"],
			[1196, "Utgarde Pinnacle"],
			[4603, "Vault of Archavon"],
			[718, "Wailing Caverns"],
			[3277, "Warsong Gulch"],
			[28, "Western Plaguelands"],
			[40, "Westfall"],
			[11, "Wetlands"],
			[4197, "Wintergrasp"],
			[618, "Winterspring"],
			[3521, "Zangarmarsh"],
			[3805, "Zul'Aman"],
			[66, "Zul'Drak"],
			[1176, "Zul'Farrak"],
			[1977, "Zul'Gurub"]],
		resistance: [
			[6, "Arcane"],
			[2, "Fire"],
			[3, "Nature"],
			[4, "Frost"],
			[5, "Shadow"],
			[1, "Holy"],
			[0, "Physical"]],
		gem: [
			[5, "Yes"],
			[1, "Meta"],
			[2, "Red"],
			[3, "Yellow"],
			[4, "Blue"],
			[6, "No"]],
		profession: [
			[11, "Yes"],
			[1, "Alchemy"],
			[2, "Blacksmithing"],
			[3, "Cooking"],
			[4, "Enchanting"],
			[5, "Engineering"],
			[6, "First Aid"],
			[13, "Fishing"],
			[14, "Herbalism"],
			[15, "Inscription"],
			[7, "Jewelcrafting"],
			[8, "Leatherworking"],
			[9, "Mining"],
			[10, "Tailoring"],
			[12, "No"]],
		expansion: [
			[3, "Wrath of the Lich King"],
			[2, "The Burning Crusade"],
			[1, "None"]],
		totemcategory: [
			[3, "Air Totem"],
			[14, "Arclight Spanner"],
			[162, "Blacksmith Hammer"],
			[168, "Bladed Pickaxe"],
			[141, "Drums"],
			[2, "Earth Totem"],
			[4, "Fire Totem"],
			[169, "Flint and Tinder"],
			[161, "Gnomish Army Knife"],
			[15, "Gyromatic Micro-Adjustor"],
			[167, "Hammer Pick"],
			[81, "Hollow Quill"],
			[21, "Master Totem"],
			[165, "Mining Pick"],
			[12, "Philosopher's Stone"],
			[62, "Runed Adamantite Rod"],
			[10, "Runed Arcanite Rod"],
			[101, "Runed Azurite Rod"],
			[189, "Runed Cobalt Rod (DO NOT USE)"],
			[6, "Runed Copper Rod"],
			[63, "Runed Eternium Rod"],
			[41, "Runed Fel Iron Rod"],
			[8, "Runed Golden Rod"],
			[7, "Runed Silver Rod"],
			[190, "Runed Titanium Rod"],
			[9, "Runed Truesilver Rod"],
			[166, "Skinning Knife"],
			[121, "Virtuoso Inking Set"],
			[5, "Water Totem"]],
		heroiczone: [
			[4494, "Ahn'kahet: The Old Kingdom"],
			[3790, "Auchenai Crypts"],
			[4277, "Azjol-Nerub"],
			[4196, "Drak'Tharon Keep"],
			[4416, "Gundrak"],
			[4272, "Halls of Lightning"],
			[4820, "Halls of Reflection"],
			[4264, "Halls of Stone"],
			[3562, "Hellfire Ramparts"],
			[4812, "Icecrown Citadel"],
			[4131, "Magisters' Terrace"],
			[3792, "Mana-Tombs"],
			[3456, "Naxxramas"],
			[2367, "Old Hillsbrad Foothills"],
			[4813, "Pit of Saron"],
			[3791, "Sethekk Halls"],
			[3789, "Shadow Labyrinth"],
			[3848, "The Arcatraz"],
			[2366, "The Black Morass"],
			[3713, "The Blood Furnace"],
			[3847, "The Botanica"],
			[4100, "The Culling of Stratholme"],
			[4500, "The Eye of Eternity"],
			[4809, "The Forge of Souls"],
			[3849, "The Mechanar"],
			[4265, "The Nexus"],
			[4493, "The Obsidian Sanctum"],
			[4228, "The Oculus"],
			[3714, "The Shattered Halls"],
			[3717, "The Slave Pens"],
			[3715, "The Steamvault"],
			[3716, "The Underbog"],
			[4415, "The Violet Hold"],
			[4723, "Trial of the Champion"],
			[4722, "Trial of the Crusader"],
			[4273, "Ulduar"],
			[206, "Utgarde Keep"],
			[1196, "Utgarde Pinnacle"],
			[4603, "Vault of Archavon"]],
		heroicdungeon: [
			[4494, "Ahn'kahet: The Old Kingdom"],
			[3790, "Auchenai Crypts"],
			[4277, "Azjol-Nerub"],
			[4196, "Drak'Tharon Keep"],
			[4416, "Gundrak"],
			[4272, "Halls of Lightning"],
			[4820, "Halls of Reflection"],
			[4264, "Halls of Stone"],
			[3562, "Hellfire Ramparts"],
			[4131, "Magisters' Terrace"],
			[3792, "Mana-Tombs"],
			[2367, "Old Hillsbrad Foothills"],
			[4813, "Pit of Saron"],
			[3791, "Sethekk Halls"],
			[3789, "Shadow Labyrinth"],
			[3848, "The Arcatraz"],
			[2366, "The Black Morass"],
			[3713, "The Blood Furnace"],
			[3847, "The Botanica"],
			[4100, "The Culling of Stratholme"],
			[4809, "The Forge of Souls"],
			[3849, "The Mechanar"],
			[4265, "The Nexus"],
			[4228, "The Oculus"],
			[3714, "The Shattered Halls"],
			[3717, "The Slave Pens"],
			[3715, "The Steamvault"],
			[3716, "The Underbog"],
			[4415, "The Violet Hold"],
			[4723, "Trial of the Champion"],
			[206, "Utgarde Keep"],
			[1196, "Utgarde Pinnacle"]],
		heroicraid: [
			[4812, "Icecrown Citadel"],
			[4722, "Trial of the Crusader"]],
		multimoderaid: [
			[4812, "Icecrown Citadel"],
			[3456, "Naxxramas"],
			[2159, "Onyxia's Lair"],
			[4500, "The Eye of Eternity"],
			[4493, "The Obsidian Sanctum"],
			[4722, "Trial of the Crusader"],
			[4273, "Ulduar"],
			[4603, "Vault of Archavon"]],
		event: [
			[372, "Brewfest"],
			[283, "Call to Arms: Alterac Valley"],
			[285, "Call to Arms: Arathi Basin"],
			[353, "Call to Arms: Eye of the Storm"],
			[420, "Call to Arms: Isle of Conquest"],
			[400, "Call to Arms: Strand of the Ancients"],
			[284, "Call to Arms: Warsong Gulch"],
			[201, "Children's Week"],
			[374, "Darkmoon Faire"],
			[409, "Day of the Dead"],
			[141, "Feast of Winter Veil"],
			[324, "Hallow's End"],
			[321, "Harvest Festival"],
			[424, "Kalu'ak Fishing Derby"],
			[335, "Love is in the Air"],
			[327, "Lunar Festival"],
			[341, "Midsummer Fire Festival"],
			[181, "Noblegarden"],
			[404, "Pilgrim's Bounty"],
			[398, "Pirates' Day"],
			[301, "Stranglethorn Fishing Extravaganza"]],
		pvp: [
			[1, "Yes"],
			[3, "Arena"],
			[4, "Battleground"],
			[5, "World"],
			[2, "No"]],
		currency: [
			[20560, "Alterac Valley Mark of Honor"],
			[32572, "Apexis Crystal"],
			[32569, "Apexis Shard"],
			[20559, "Arathi Basin Mark of Honor"],
			[29736, "Arcane Rune"],
			[44128, "Arctic Fur"],
			[29434, "Badge of Justice"],
			[34853, "Belt of the Forgotten Conqueror"],
			[34854, "Belt of the Forgotten Protector"],
			[34855, "Belt of the Forgotten Vanquisher"],
			[34856, "Boots of the Forgotten Conqueror"],
			[34857, "Boots of the Forgotten Protector"],
			[34858, "Boots of the Forgotten Vanquisher"],
			[34848, "Bracers of the Forgotten Conqueror"],
			[34851, "Bracers of the Forgotten Protector"],
			[34852, "Bracers of the Forgotten Vanquisher"],
			[40625, "Breastplate of the Lost Conqueror"],
			[40626, "Breastplate of the Lost Protector"],
			[40627, "Breastplate of the Lost Vanquisher"],
			[45632, "Breastplate of the Wayward Conqueror"],
			[45633, "Breastplate of the Wayward Protector"],
			[45634, "Breastplate of the Wayward Vanquisher"],
			[34169, "Breeches of Natural Aggression"],
			[37829, "Brewfest Prize Token"],
			[23247, "Burning Blossom"],
			[34186, "Chain Links of the Tumultuous Storm"],
			[44990, "Champion's Seal"],
			[29754, "Chestguard of the Fallen Champion"],
			[29753, "Chestguard of the Fallen Defender"],
			[29755, "Chestguard of the Fallen Hero"],
			[31089, "Chestguard of the Forgotten Conqueror"],
			[31091, "Chestguard of the Forgotten Protector"],
			[31090, "Chestguard of the Forgotten Vanquisher"],
			[40610, "Chestguard of the Lost Conqueror"],
			[40611, "Chestguard of the Lost Protector"],
			[40612, "Chestguard of the Lost Vanquisher"],
			[30236, "Chestguard of the Vanquished Champion"],
			[30237, "Chestguard of the Vanquished Defender"],
			[30238, "Chestguard of the Vanquished Hero"],
			[45635, "Chestguard of the Wayward Conqueror"],
			[45636, "Chestguard of the Wayward Protector"],
			[45637, "Chestguard of the Wayward Vanquisher"],
			[24368, "Coilfang Armaments"],
			[52027, "Conqueror's Mark of Sanctification"],
			[52030, "Conqueror's Mark of Sanctification (Heroic)"],
			[34245, "Cover of Ursol the Wise"],
			[34332, "Cowl of Gul'dan"],
			[34339, "Cowl of Light's Purity"],
			[34345, "Crown of Anasterian"],
			[40631, "Crown of the Lost Conqueror"],
			[40632, "Crown of the Lost Protector"],
			[40633, "Crown of the Lost Vanquisher"],
			[45638, "Crown of the Wayward Conqueror"],
			[45639, "Crown of the Wayward Protector"],
			[45640, "Crown of the Wayward Vanquisher"],
			[43016, "Dalaran Cooking Award"],
			[41596, "Dalaran Jewelcrafter's Token"],
			[34052, "Dream Shard"],
			[34244, "Duplicitous Guise"],
			[45624, "Emblem of Conquest"],
			[49426, "Emblem of Frost"],
			[40752, "Emblem of Heroism"],
			[47241, "Emblem of Triumph"],
			[40753, "Emblem of Valor"],
			[34208, "Equilibrium Epaulets"],
			[29024, "Eye of the Storm Mark of Honor"],
			[34180, "Felfury Legplates"],
			[34229, "Garments of Serene Shores"],
			[34350, "Gauntlets of the Ancient Shadowmoon"],
			[40628, "Gauntlets of the Lost Conqueror"],
			[40629, "Gauntlets of the Lost Protector"],
			[40630, "Gauntlets of the Lost Vanquisher"],
			[45641, "Gauntlets of the Wayward Conqueror"],
			[45642, "Gauntlets of the Wayward Protector"],
			[45643, "Gauntlets of the Wayward Vanquisher"],
			[29757, "Gloves of the Fallen Champion"],
			[29758, "Gloves of the Fallen Defender"],
			[29756, "Gloves of the Fallen Hero"],
			[31092, "Gloves of the Forgotten Conqueror"],
			[31094, "Gloves of the Forgotten Protector"],
			[31093, "Gloves of the Forgotten Vanquisher"],
			[40613, "Gloves of the Lost Conqueror"],
			[40614, "Gloves of the Lost Protector"],
			[40615, "Gloves of the Lost Vanquisher"],
			[30239, "Gloves of the Vanquished Champion"],
			[30240, "Gloves of the Vanquished Defender"],
			[30241, "Gloves of the Vanquished Hero"],
			[45644, "Gloves of the Wayward Conqueror"],
			[45645, "Gloves of the Wayward Protector"],
			[45646, "Gloves of the Wayward Vanquisher"],
			[24245, "Glowcap"],
			[26045, "Halaa Battle Token"],
			[26044, "Halaa Research Token"],
			[34342, "Handguards of the Dawn"],
			[34211, "Harness of Carnal Instinct"],
			[38425, "Heavy Borean Leather"],
			[34243, "Helm of Burning Righteousness"],
			[29760, "Helm of the Fallen Champion"],
			[29761, "Helm of the Fallen Defender"],
			[29759, "Helm of the Fallen Hero"],
			[31097, "Helm of the Forgotten Conqueror"],
			[31095, "Helm of the Forgotten Protector"],
			[31096, "Helm of the Forgotten Vanquisher"],
			[40616, "Helm of the Lost Conqueror"],
			[40617, "Helm of the Lost Protector"],
			[40618, "Helm of the Lost Vanquisher"],
			[30242, "Helm of the Vanquished Champion"],
			[30243, "Helm of the Vanquished Defender"],
			[30244, "Helm of the Vanquished Hero"],
			[45647, "Helm of the Wayward Conqueror"],
			[45648, "Helm of the Wayward Protector"],
			[45649, "Helm of the Wayward Vanquisher"],
			[34216, "Heroic Judicator's Chestguard"],
			[29735, "Holy Dust"],
			[29766, "Leggings of the Fallen Champion"],
			[29767, "Leggings of the Fallen Defender"],
			[29765, "Leggings of the Fallen Hero"],
			[31098, "Leggings of the Forgotten Conqueror"],
			[31100, "Leggings of the Forgotten Protector"],
			[31099, "Leggings of the Forgotten Vanquisher"],
			[34188, "Leggings of the Immortal Night"],
			[40619, "Leggings of the Lost Conqueror"],
			[40620, "Leggings of the Lost Protector"],
			[40621, "Leggings of the Lost Vanquisher"],
			[30245, "Leggings of the Vanquished Champion"],
			[30246, "Leggings of the Vanquished Defender"],
			[30247, "Leggings of the Vanquished Hero"],
			[45650, "Leggings of the Wayward Conqueror"],
			[45651, "Leggings of the Wayward Protector"],
			[45652, "Leggings of the Wayward Vanquisher"],
			[34167, "Legplates of the Holy Juggernaut"],
			[40634, "Legplates of the Lost Conqueror"],
			[40635, "Legplates of the Lost Protector"],
			[40636, "Legplates of the Lost Vanquisher"],
			[45653, "Legplates of the Wayward Conqueror"],
			[45654, "Legplates of the Wayward Protector"],
			[45655, "Legplates of the Wayward Vanquisher"],
			[40637, "Mantle of the Lost Conqueror"],
			[40638, "Mantle of the Lost Protector"],
			[40639, "Mantle of the Lost Vanquisher"],
			[45656, "Mantle of the Wayward Conqueror"],
			[45657, "Mantle of the Wayward Protector"],
			[45658, "Mantle of the Wayward Vanquisher"],
			[24579, "Mark of Honor Hold"],
			[24581, "Mark of Thrallmar"],
			[32897, "Mark of the Illidari"],
			[22484, "Necrotic Rune"],
			[34170, "Pantaloons of Calming Strife"],
			[34192, "Pauldrons of Perseverance"],
			[29763, "Pauldrons of the Fallen Champion"],
			[29764, "Pauldrons of the Fallen Defender"],
			[29762, "Pauldrons of the Fallen Hero"],
			[31101, "Pauldrons of the Forgotten Conqueror"],
			[31103, "Pauldrons of the Forgotten Protector"],
			[31102, "Pauldrons of the Forgotten Vanquisher"],
			[30248, "Pauldrons of the Vanquished Champion"],
			[30249, "Pauldrons of the Vanquished Defender"],
			[30250, "Pauldrons of the Vanquished Hero"],
			[52026, "Protector's Mark of Sanctification"],
			[52029, "Protector's Mark of Sanctification (Heroic)"],
			[34233, "Robes of Faltered Light"],
			[34234, "Shadowed Gauntlets of Paroxysm"],
			[34202, "Shawl of Wonderment"],
			[34195, "Shoulderpads of Vehemence"],
			[4291, "Silken Thread"],
			[34209, "Spaulders of Reclamation"],
			[40622, "Spaulders of the Lost Conqueror"],
			[40623, "Spaulders of the Lost Protector"],
			[40624, "Spaulders of the Lost Vanquisher"],
			[34193, "Spaulders of the Thalassian Savior"],
			[45659, "Spaulders of the Wayward Conqueror"],
			[45660, "Spaulders of the Wayward Protector"],
			[45661, "Spaulders of the Wayward Vanquisher"],
			[28558, "Spirit Shard"],
			[43228, "Stone Keeper's Shard"],
			[34212, "Sunglow Vest"],
			[34664, "Sunmote"],
			[34351, "Tranquil Majesty Wraps"],
			[47242, "Trophy of the Crusade"],
			[52025, "Vanquisher's Mark of Sanctification"],
			[52028, "Vanquisher's Mark of Sanctification (Heroic)"],
			[37836, "Venture Coin"],
			[34215, "Warharness of Reckless Fury"],
			[20558, "Warsong Gulch Mark of Honor"],
			[34597, "Winterfin Clam"],
			[43589, "Wintergrasp Mark of Honor"]],
		queststart: [
			[3, "Item"],
			[1, "NPC"],
			[2, "Object"]],
		questend: [
			[1, "NPC"],
			[2, "Object"]],
		spellsource: [
			[1, "Any"],
			[3, "Crafted"],
			[9, "Discovery"],
			[4, "Drop"],
			[6, "Quest"],
			[10, "Talent"],
			[8, "Trainer"],
			[7, "Vendor"],
			[2, "None"]],
		itemsource: [
			[1, "Any"],
			[3, "Crafted"],
			[4, "Drop"],
			[5, "PvP"],
			[6, "Quest"],
			[8, "Redemption"],
			[7, "Vendor"],
			[2, "None"]],
		glyphtype: [
			[1, "Major"],
			[2, "Minor"]],
		classs: [
			[12, "Any"],
			[6, "Death Knight"],
			[11, "Druid"],
			[3, "Hunter"],
			[8, "Mage"],
			[2, "Paladin"],
			[5, "Priest"],
			[4, "Rogue"],
			[7, "Shaman"],
			[9, "Warlock"],
			[1, "Warrior"],
			[13, "None"]],
		race: [
			[12, "Any"],
			[10, "Blood Elf"],
			[11, "Draenei"],
			[3, "Dwarf"],
			[7, "Gnome"],
			[1, "Human"],
			[4, "Night Elf"],
			[2, "Orc"],
			[6, "Tauren"],
			[8, "Troll"],
			[5, "Undead"],
			[13, "None"]],
		disenchanting: [
			[34057, "Abyss Crystal"],
			[22445, "Arcane Dust"],
			[11176, "Dream Dust"],
			[34052, "Dream Shard"],
			[11082, "Greater Astral Essence"],
			[34055, "Greater Cosmic Essence"],
			[16203, "Greater Eternal Essence"],
			[10939, "Greater Magic Essence"],
			[11135, "Greater Mystic Essence"],
			[11175, "Greater Nether Essence"],
			[22446, "Greater Planar Essence"],
			[16204, "Illusion Dust"],
			[34054, "Infinite Dust"],
			[14344, "Large Brilliant Shard"],
			[11084, "Large Glimmering Shard"],
			[11139, "Large Glowing Shard"],
			[22449, "Large Prismatic Shard"],
			[11178, "Large Radiant Shard"],
			[10998, "Lesser Astral Essence"],
			[34056, "Lesser Cosmic Essence"],
			[16202, "Lesser Eternal Essence"],
			[10938, "Lesser Magic Essence"],
			[11134, "Lesser Mystic Essence"],
			[11174, "Lesser Nether Essence"],
			[22447, "Lesser Planar Essence"],
			[20725, "Nexus Crystal"],
			[14343, "Small Brilliant Shard"],
			[34053, "Small Dream Shard"],
			[10978, "Small Glimmering Shard"],
			[11138, "Small Glowing Shard"],
			[22448, "Small Prismatic Shard"],
			[11177, "Small Radiant Shard"],
			[11083, "Soul Dust"],
			[10940, "Strange Dust"],
			[11137, "Vision Dust"],
			[22450, "Void Crystal"]]
	},
	fiitems: {
		addedinexpansion: "Added in expansion",
		addedinpatch: "Added in patch",
		bindonequip: "Binds when equipped",
		bindonpickup: "Binds when picked up",
		bindonuse: "Binds when used",
		bindtoaccount: "Binds to account",
		heroicitem: "Heroic item",
		changedinwotlk: "Changed in Wrath of the Lich King",
		conjureditem: "Conjured item",
		craftedprof: "Crafted by a profession",
		damagetype: "Damage type",
		disenchantable: "Disenchantable",
		disenchantsinto: "Disenchants into...",
		dropsin: "Drops in...",
		dropsinheroic: "Drops in Heroic mode... (Dungeon)",
		dropsinnormal: "Drops in Normal mode... (Dungeon)",
		dropsinnormal10: "Drops in Normal 10 mode... (Raid)",
		dropsinnormal25: "Drops in Normal 25 mode... (Raid)",
		dropsinheroic10: "Drops in Heroic 10 mode... (Raid)",
		dropsinheroic25: "Drops in Heroic 25 mode... (Raid)",
		effecttext: "Effect text",
		fitsgemslot: "Fits a gem slot",
		flavortext: "Flavor text",
		glyphtype: "Glyph type",
		hascomments: "Has comments",
		hasflavortext: "Has a flavor text",
		hasscreenshots: "Has screenshots",
		hasvideos: "Has videos",
		hassockets: "Has sockets",
		icon: "Icon",
		locked: "Locked",
		notavailable: "Not available to players",
		availabletoplayers: "Available to players",
		deprecated: "Deprecated",
		objectivequest: "Objective of a quest",
		openable: "Openable",
		otdisenchanting: "Obtained through disenchanting",
		otfishing: "Obtained through fishing",
		otherbgathering: "Obtained through herb gathering",
		otitemopening: "Obtained through item opening",
		otlooting: "Obtained through looting",
		otmilling: "Obtained through milling",
		otmining: "Obtained through mining",
		otobjectopening: "Obtained through object opening",
		otpickpocketing: "Obtained through pick pocketing",
		otprospecting: "Obtained through prospecting",
		otpvp: "Obtained through PvP",
		otskinning: "Obtained through skinning",
		partofset: "Part of an item set",
		partyloot: "Party loot",
		prospectable: "Prospectable",
		millable: "Millable",
		purchasablewithcurrency: "Purchasable with a currency",
		purchasablewith: "Purchasable with a currency...",
		purchasablewithhonor: "Purchasable with honor points",
		purchasablewitharena: "Purchasable with arena points",
		questitem: "Quest item",
		randomenchants: "Random enchantments (of the...)",
		repaircost: "Repair cost (coppers)",
		randomlyenchanted: "Randomly enchanted",
		readable: "Readable",
		reagentforability: "Reagent for ability/profession",
		refundable: "Refundable",
		requiresprof: "Requires a profession",
		requiresprofspec: "Requires a profession specialization",
		requiresrepwith: "Requires reputation with...",
		rewardedbyfactionquest: "Rewarded by a quest",
		rewardedbyquestin: "Rewarded by a quest in...",
		sepcommunity: "Community",
		sepsource: "Source",
		smartloot: "Smart loot",
		soldbynpc: "Sold by NPC #...",
		soldbyvendor: "Sold by a vendor",
		startsquest: "Starts a quest",
		teachesspell: "Teaches a spell",
		tool: "Tool",
		id: "ID",
		usableinarenas: "Usable in arenas",
		usablewhenshapeshifted: "Usable when shapeshifted",
		unique: "Unique",
		uniqueequipped: "Unique-Equipped",
		classspecific: "Class-specific",
		racespecific: "Race-specific",
		relatedevent: "Related world event",
		requiresevent: "Requires a world event"
	},
	fiitemsets: {
		sepgeneral: "General",
		addedinpatch: "Added in patch",
		id: "ID",
		pieces: "Number of pieces",
		bonustext: "Bonus effect text",
		heroic: "Heroic",
		relatedevent: "Related world event",
		sepcommunity: "Community",
		hascomments: "Has comments",
		hasscreenshots: "Has screenshots",
		hasvideos: "Has videos"
	},
	finpcs: {
		sepgeneral: "General",
		addedinexpansion: "Added in expansion",
		addedinpatch: "Added in patch",
		canrepair: "Can repair",
		faction: "Faction",
		relatedevent: "Related world event",
		foundin: "Found in...",
		health: "Health",
		mana: "Mana",
		instanceboss: "Instance boss",
		startsquest: "Starts a quest",
		endsquest: "Ends a quest",
		usemodel: "Uses model #...",
		useskin: "Uses skin...",
		id: "ID",
		seploot: "Loot",
		averagemoneydropped: "Average money dropped",
		gatherable: "Gatherable (herbalism)",
		lootable: "Lootable",
		minable: "Minable (mining)",
		pickpocketable: "Pick pocketable",
		skinnable: "Skinnable",
		sepgossipoptions: "Gossip options",
		auctioneer: "Auctioneer",
		banker: "Banker",
		battlemaster: "Battlemaster",
		flightmaster: "Flight master",
		guildmaster: "Guild master",
		innkeeper: "Innkeeper",
		talentunlearner: "Talent unlearner",
		tabardvendor: "Tabard vendor",
		stablemaster: "Stable master",
		trainer: "Trainer",
		vendor: "Vendor",
		sepcommunity: "Community",
		hascomments: "Has comments",
		hasscreenshots: "Has screenshots",
		hasvideos: "Has videos"
	},
	fiobjects: {
		sepgeneral: "General",
		addedinexpansion: "Added in expansion",
		addedinpatch: "Added in patch",
		foundin: "Found in...",
		requiredskilllevel: "Required skill level (herbs/veins/footlockers)",
		relatedevent: "Related world event",
		startsquest: "Starts a quest",
		endsquest: "Ends a quest",
		id: "ID",
		seploot: "Loot",
		averagemoneycontained: "Average money contained",
		openable: "Openable",
		sepcommunity: "Community",
		hascomments: "Has comments",
		hasscreenshots: "Has screenshots",
		hasvideos: "Has videos"
	},
	fiquests: {
		sepgeneral: "General",
		addedinexpansion: "Added in expansion",
		addedinpatch: "Added in patch",
		relatedevent: "Related world event",
		daily: "Daily",
		weekly: "Weekly",
		repeatable: "Repeatable",
		objectiveearnrepwith: "Objective: Earn reputation with...",
		sharable: "Sharable",
		startsfrom: "Starts from...",
		endsat: "Ends at...",
		suggestedplayers: "Suggested players",
		timer: "Timer (seconds)",
		availabletoplayers: "Available to players",
		id: "ID",
		classspecific: "Class-specific",
		racespecific: "Race-specific",
		sepgainsrewards: "Gains/rewards",
		experiencegained: "Experience gained",
		arenagained: "Arena points gained",
		honorgained: "Honor gained",
		itemchoices: "Item choices",
		itemrewards: "Item rewards",
		moneyrewarded: "Money rewarded",
		spellrewarded: "Spell rewarded",
		increasesrepwith: "Increases reputation with...",
		decreasesrepwith: "Decreases reputation with...",
		sepseries: "Series",
		firstquestseries: "First quest of a series",
		lastquestseries: "Last quest of a series",
		partseries: "Part of a series",
		sepcommunity: "Community",
		hascomments: "Has comments",
		hasscreenshots: "Has screenshots",
		hasvideos: "Has videos",
		lacksstartend: "Lacks start or end"
	},
	fispells: {
		sepgeneral: "General",
		addedinpatch: "Added in patch",
		prcntbasemanarequired: "% of base mana required",
		firstrank: "First rank",
		lastrank: "Last rank",
		rankno: "Rank #...",
		manaenergyragecost: "Mana/energy/rage cost",
		requiresnearbyobject: "Requires a nearby object",
		hasreagents: "Has reagents",
		scaling: "Scales with level",
		requiresprofspec: "Requires a profession specialization",
		source: "Source",
		trainingcost: "Training cost",
		id: "ID",
		icon: "Icon",
		sepcommunity: "Community",
		hascomments: "Has comments",
		hasscreenshots: "Has screenshots",
		hasvideos: "Has videos"
	},
	fiachievements: {
		sepgeneral: "General",
		addedinpatch: "Added in patch",
		givesreward: "Gives a reward",
		rewardtext: "Reward text",
		location: "Location...",
		relatedevent: "Related world event",
		id: "ID",
		icon: "Icon",
		sepseries: "Series",
		firstseries: "First of a series",
		lastseries: "Last of a series",
		partseries: "Part of a series",
		sepcommunity: "Community",
		hascomments: "Has comments",
		hasscreenshots: "Has screenshots",
		hasvideos: "Has videos"
	},
	fiprofiles: {
		sepgeneral: "General",
		gearscore: "Gear score",
		achievementpoints: "Achievement points",
		wearingitem: "Wearing item #...",
		wearingpermenchant: "Wearing enchantment #...",
		completedachievement: "Completed achievement #...",
		sepprofession: "Professions",
		alchemy: "Alchemy skill",
		blacksmithing: "Blacksmithing skill",
		enchanting: "Enchanting skill",
		engineering: "Engineering skill",
		herbalism: "Herbalism skill",
		inscription: "Inscription skill",
		jewelcrafting: "Jewelcrafting skill",
		leatherworking: "Leatherworking skill",
		mining: "Mining skill",
		skinning: "Skinning skill",
		tailoring: "Tailoring skill",
		septalent: "Talents",
		talenttree1: "Points spent in first talent tree",
		talenttree2: "Points spent in second talent tree",
		talenttree3: "Points spent in third talent tree",
		sepguild: "Guilds",
		hasguild: "Has a guild",
		guildname: "Guild name",
		guildrank: "Guild member rank",
		separenateam: "Arena teams",
		teamname2v2: "2v2 arena team name",
		teamrtng2v2: "2v2 arena team rating",
		teamcontrib2v2: "2v2 arena team contribution",
		teamname3v3: "3v3 arena team name",
		teamrtng3v3: "3v3 arena team rating",
		teamcontrib3v3: "3v3 arena team contribution",
		teamname5v5: "5v5 arena team name",
		teamrtng5v5: "5v5 arena team rating",
		teamcontrib5v5: "5v5 arena team contribution"
	},
	presets: {
		pve: "PvE",
		pvp: "PvP",
		afflic: "Affliction",
		arcane: "Arcane",
		arms: "Arms (DPS)",
		assas: "Assassination",
		balance: "Balance (DPS)",
		beast: "Beast Mastery",
		blooddps: "Blood (DPS)",
		bloodtank: "Blood (Tank)",
		combat: "Combat",
		demo: "Demonology",
		destro: "Destruction",
		disc: "Discipline (Healing)",
		elem: "Elemental Combat (DPS)",
		enhance: "Enhancement (DPS)",
		feraldps: "Feral Combat (DPS)",
		feraltank: "Feral Combat (Tank)",
		fire: "Fire",
		frost: "Frost",
		frostdps: "Frost (DPS)",
		frosttank: "Frost (Tank)",
		fury: "Fury (DPS)",
		generic: "Generic",
		holy: "Holy (Healing)",
		marks: "Marksmanship",
		prot: "Protection (Tank)",
		resto: "Restoration (Healing)",
		retrib: "Retribution (DPS)",
		shadow: "Shadow Magic (DPS)",
		subtle: "Subtlety",
		surv: "Survival",
		unholydps: "Unholy (DPS)"
	},
	traits: {
		agi: ["Agility", "Agi", "Agi"],
		arcres: ["Arcane resistance", "Arcane Resist", "ArcR"],
		arcsplpwr: ["Arcane spell power", "Arcane Power", "ArcP"],
		armor: ["Armor", "Armor", "Armor"],
		armorbonus: ["Additional armor", "Bonus Armor", "AddAr"],
		armorpenrtng: ["Armor penetration rating", "Armor Pen", "Pen"],
		atkpwr: ["Attack power", "AP", "AP"],
		avgbuyout: ["Average buyout price", "Buyout", "AH"],
		avgmoney: ["Average money contained", "Money", "Money"],
		block: ["Block value", "Block Value", "BkVal"],
		blockrtng: ["Block rating", "Block", "Block"],
		buyprice: ["Buy price (coppers)", "Buy", "Buy"],
		cooldown: ["Cooldown (seconds)", "Cooldown", "CD"],
		critstrkrtng: ["Critical strike rating", "Crit", "Crit"],
		defrtng: ["Defense rating", "Defense", "Def"],
		dmg: ["Weapon damage", "Damage", "Dmg"],
		dmgmax1: ["Maximum damage", "Max Damage", "Max"],
		dmgmin1: ["Minimum damage", "Min Damage", "Min"],
		dodgertng: ["Dodge rating", "Dodge", "Dodge"],
		dps: ["Damage per second", "DPS", "DPS"],
		dura: ["Durability", "Durability", "Dura"],
		exprtng: ["Expertise rating", "Expertise", "Exp"],
		feratkpwr: ["Feral attack power", "Feral AP", "FAP"],
		firres: ["Fire resistance", "Fire Resist", "FirR"],
		firsplpwr: ["Fire spell power", "Fire Power", "FireP"],
		frores: ["Frost resistance", "Frost Resist", "FroR"],
		frosplpwr: ["Frost spell power", "Frost Power", "FroP"],
		hastertng: ["Haste rating", "Haste", "Haste"],
		health: ["Health", "Health", "Hlth"],
		healthrgn: ["Health regeneration", "HP5", "HP5"],
		hitrtng: ["Hit rating", "Hit", "Hit"],
		holres: ["Holy resistance", "Holy Resist", "HolR"],
		holsplpwr: ["Holy spell power", "Holy Power", "HolP"],
		"int": ["Intellect", "Int", "Int"],
		level: ["Level", "Level", "Lvl"],
		mana: ["Mana", "Mana", "Mana"],
		manargn: ["Mana regeneration", "MP5", "MP5"],
		masteryrtng: ["Mastery rating", "Mastery", "Mastery"],
		mleatkpwr: ["Melee attack power", "Melee AP", "AP"],
		mlecritstrkrtng: ["Melee critical strike rating", "Melee Crit", "Crit"],
		mledmgmax: ["Melee maximum damage", "Melee Max Damage", "Max"],
		mledmgmin: ["Melee minimum damage", "Melee Min Damage", "Min"],
		mledps: ["Melee DPS", "Melee DPS", "DPS"],
		mlehastertng: ["Melee haste rating", "Melee Haste", "Haste"],
		mlehitrtng: ["Melee hit rating", "Melee Hit", "Hit"],
		mlespeed: ["Melee speed", "Melee Speed", "Speed"],
		natres: ["Nature resistance", "Nature Resist", "NatR"],
		natsplpwr: ["Nature spell power", "Nature Power", "NatP"],
		nsockets: ["Number of sockets", "Sockets", "Sockt"],
		parryrtng: ["Parry rating", "Parry", "Parry"],
		reqarenartng: ["Required personal and team arena rating", "Req Rating", "Rating"],
		reqlevel: ["Required level", "Req Level", "Level"],
		reqskillrank: ["Required skill level", "Req Skill", "Skill"],
		resirtng: ["Resilience rating", "Resilience", "Resil"],
		rgdatkpwr: ["Ranged attack power", "Ranged AP", "RAP"],
		rgdcritstrkrtng: ["Ranged critical strike rating", "Ranged Crit", "Crit"],
		rgddmgmax: ["Ranged maximum damage", "Ranged Max Damage", "Max"],
		rgddmgmin: ["Ranged minimum damage", "Ranged Min Damage", "Min"],
		rgddps: ["Ranged DPS", "Ranged DPS", "DPS"],
		rgdhastertng: ["Ranged haste rating", "Ranged Haste", "Haste"],
		rgdhitrtng: ["Ranged hit rating", "Ranged Hit", "Hit"],
		rgdspeed: ["Ranged speed", "Ranged Speed", "Speed"],
		sellprice: ["Sale price (coppers)", "Sell", "Sell"],
		sepbasestats: "Base stats",
		sepdefensivestats: "Defensive stats",
		sepgeneral: "General",
		sepindividualstats: "Individual stats",
		sepmisc: "Miscellaneous",
		sepoffensivestats: "Offensive stats",
		sepresistances: "Resistances",
		sepweaponstats: "Weapon stats",
		shares: ["Shadow resistance", "Shadow Resist", "ShaR"],
		shasplpwr: ["Shadow spell power", "Shadow Power", "ShaP"],
		speed: ["Speed", "Speed", "Speed"],
		spi: ["Spirit", "Spi", "Spi"],
		splcritstrkrtng: ["Spell critical strike rating", "Spell Crit", "Crit"],
		spldmg: ["Damage done by spells", "Spell Damage", "Dmg"],
		splheal: ["Healing done by spells", "Healing", "Heal"],
		splpwr: ["Spell power", "Spell Power", "SP"],
		splhastertng: ["Spell haste rating", "Spell Haste", "Haste"],
		splhitrtng: ["Spell hit rating", "Spell Hit", "Hit"],
		splpen: ["Spell penetration", "Spell Pen", "Pen"],
		sta: ["Stamina", "Sta", "Sta"],
		str: ["Strength", "Str", "Str"]
	},
	fishow: "Create a filter",
	fihide: "Hide filter options",
	fiany: "Any",
	finone: "None",
	firemove: "remove",
	ficlear: "clear",
	fishowdetails: "show details",
	fihidedetails: "hide details",
	message_fillsomecriteria: "Please fill in some criteria.",
	tooltip_jconlygems: "If checked, jewelcrafter-only gems<br />\nwill also be used to determine the best<br />\npossible gems for an item's weighted score.",
