	showonmap: "{term:showonmap_ellipsis}",
	som_nothing: "{term:nothing}",
	som_questgivers: "{term:questgivers_stc}",
	som_viewnpc: "{term:clicktoviewthisnpc_stc}",
	som_viewobj: "{term:clicktoviewthisobject_stc}",
	som_view: "{term:clicktoview_ellipsis}",
	som_startsquest: "{term:startsthefollowingquest_colon}",
	som_startsquestpl: "{term:starsthefollowingquests_colon}",
	som_legend: "{term:legend_colon}",
	som_legend_alliance: "{term:alliance}",
	som_legend_horde: "{term:horde}",
	som_legend_neutral: "{term:neutral}",
	som: {
		all: "{term:all}",
		alliance: "{term:alliance}",
		horde: "{term:horde}",
		quest: "{term:questgivers}",
		alliancequests: "{term:questgivers}",
		hordequests: "{term:questgivers}",
		repair: "{term:repairers}",
		rare: "{term:rarenpcs}",
		auctioneer: "{term:auctioneers}",
		banker: "{term:bankers}",
		battlemaster: "{term:battlemasters}",
		innkeeper: "{term:innkeepers}",
		guildmaster: "{term:guildmasters_stc}",
		stablemaster: "{term:stablemasters}",
		flightmaster: "{term:flightmasters}",
		trainer: "{term:trainers}",
		vendor: "{term:vendors}",
		book: "{term:books}",
		herb: "{term:herbs}",
		vein: "{term:mineralveins}",
		spirithealer: "{term:spirithealers}"
	},

/*
	showonmap: "Show on map...",
	som_nothing: "Nothing",
	som_questgivers: "Quest givers",
	som_viewnpc: "Click to view this NPC",
	som_viewobj: "Click to view this object",
	som_view: "Click to view...",
	som_startsquest: "Starts the following quest:",
	som_startsquestpl: "Starts the following quests:",
	som_legend: "Legend: ",
	som_legend_alliance: "Alliance",
	som_legend_horde: "Horde",
	som_legend_neutral: "Neutral",
	som: {
		all: "All",
		alliance: "Alliance",
		horde: "Horde",
		quest: "Quest Givers",
		alliancequests: "Quest Givers",
		hordequests: "Quest Givers",
		repair: "Repairers",
		rare: "Rare NPCs",
		auctioneer: "Auctioneers",
		banker: "Bankers",
		battlemaster: "Battlemasters",
		innkeeper: "Innkeepers",
		guildmaster: "Guild masters",
		stablemaster: "Stable Masters",
		flightmaster: "Flight Masters",
		trainer: "Trainers",
		vendor: "Vendors",
		book: "Books",
		herb: "Herbs",
		vein: "Mineral Veins",
		spirithealer: "Spirit Healers"
	},
*/