
var g_item_glyphs = {
	1: "{term:glyph_major}",
	2: "{term:glyph_minor}"
};
var g_item_slots = {
	1: "Head",
	2: "Neck",
	3: "Shoulder",
	4: "Shirt",
	5: "Chest",
	6: "Waist",
	7: "Legs",
	8: "Feet",
	9: "Wrist",
	10: "Hands",
	11: "Finger",
	12: "Trinket",
	13: "One-Hand",
	14: "Shield",
	15: "Ranged",
	16: "Back",
	17: "Two-Hand",
	18: "Bag",
	19: "Tabard",
	21: "Main Hand",
	22: "Off Hand",
	23: "Held In Off-hand",
	24: "Projectile",
	25: "Thrown",
	28: "Relic"
};

var g_item_subclasses = {
	0: {
		0: "Consumable",
		1: "Potion",
		2: "Elixir",
		3: "Flask",
		4: "Scroll",
		5: "Food & Drink",
		6: "Perm. Enhancement",
		"-3": "Temp. Enhancement",
		7: "Bandage",
		8: "Other (Consumables)"
	},
	1: {
		0: "Bag",
		1: "Soul Bag",
		2: "Herb Bag",
		3: "Enchanting Bag",
		4: "Engineering Bag",
		5: "Gem Bag",
		6: "Mining Bag",
		7: "Leatherworking Bag",
		8: "Inscription Bag"
	},
	2: {
		0: "One-Handed Axe",
		1: "Two-Handed Axe",
		2: "Bow",
		3: "Gun",
		4: "One-Handed Mace",
		5: "Two-Handed Mace",
		6: "Polearm",
		7: "One-Handed Sword",
		8: "Two-Handed Sword",
		10: "Staff",
		13: "Fist Weapon",
		14: "Misc. (Weapons)",
		15: "Dagger",
		16: "Thrown",
		18: "Crossbow",
		19: "Wand",
		20: "Fishing Pole"
	},
	3: {
		0: "Red Gem",
		1: "Blue Gem",
		2: "Yellow Gem",
		3: "Purple Gem",
		4: "Green Gem",
		5: "Orange Gem",
		6: "Meta Gem",
		7: "Simple Gem",
		8: "Prismatic Gem"
	},
	4: {
		"-8": "Shirt",
		"-7": "Tabard",
		"-6": "Cloak",
		"-5": "Off-hand Frill",
		"-4": "Trinket",
		"-3": "Amulet",
		"-2": "Ring",
		0: "Misc. (Armor)",
		1: "Cloth Armor",
		2: "Leather Armor",
		3: "Mail Armor",
		4: "Plate Armor",
		6: "Shield",
		7: "Libram",
		8: "Idol",
		9: "Totem",
		10: "Sigil"
	},
	6: {
		2: "Arrow",
		3: "Bullet"
	},
	7: {
		1: "Part",
		2: "Explosive",
		3: "Device",
		4: "Jewelcrafting",
		5: "Cloth",
		6: "Leather",
		7: "Metal & Stone",
		8: "Meat",
		9: "Herb",
		10: "Elemental",
		12: "Enchanting",
		13: "Material",
		14: "Armor Enchantment",
		15: "Weapon Enchantment",
		11: "Other (Trade Goods)"
	},
	9: {
		0: "Book",
		1: "Leatherworking Pattern",
		2: "Tailoring Pattern",
		3: "Engineering Schematic",
		4: "Blacksmithing Plans",
		5: "Cooking Recipe",
		6: "Alchemy Recipe",
		7: "First Aid Book",
		8: "Enchanting Formula",
		9: "Fishing Book",
		10: "Jewelcrafting Design",
		11: "Inscription Technique"
	},
	11: {
		2: "Quiver",
		3: "Ammo Pouch"
	},
	15: {
		"-7": "Flying Mount",
		"-6": "Combat Pet",
		"-2": "Armor Token",
		0: "Junk",
		1: "Reagent",
		2: "Companion",
		3: "Holiday",
		4: "Other (Miscellaneous)",
		5: "Mount"
	},
	16: {
		6: "Death Knight Glyph",
		11: "Druid Glyph",
		3: "Hunter Glyph",
		8: "Mage Glyph",
		2: "Paladin Glyph",
		5: "Priest Glyph",
		4: "Rogue Glyph",
		7: "Shaman Glyph",
		9: "Warlock Glyph",
		1: "Warrior Glyph"
	}
};
var g_item_subsubclasses = {
	0: {
		2: {
			1: "Battle Elixir",
			2: "Guardian Elixir"
		}
	}
};

var g_itemset_types = {
	1: "Cloth",
	2: "Leather",
	3: "Mail",
	4: "Plate",
	5: "Dagger",
	6: "Ring",
	7: "Fist Weapon",
	8: "One-Handed Axe",
	9: "One-Handed Mace",
	10: "One-Handed Sword",
	11: "Trinket",
	12: "Amulet"
};
var g_itemset_notes = {
	1: "Dungeon Set 1",
	2: "Dungeon Set 2",
	14: "Dungeon Set 3",
	3: "Tier 1 Raid Set",
	4: "Tier 2 Raid Set",
	5: "Tier 3 Raid Set",
	12: "Tier 4 Raid Set",
	13: "Tier 5 Raid Set",
	18: "Tier 6 Raid Set",
	23: "Tier 7 Raid Set",
	25: "Tier 8 Raid Set",
	27: "Tier 9 Raid Set",
	29: "Tier 10 Raid Set",
	6: "Level 60 PvP Rare Set",
	7: "Level 60 PvP Rare Set (Old)",
	8: "Level 60 PvP Epic Set",
	16: "Level 70 PvP Rare Set",
	21: "Level 70 PvP Rare Set 2",
	17: "Arena Season 1 Set",
	19: "Arena Season 2 Set",
	20: "Arena Season 3 Set",
	22: "Arena Season 4 Set",
	24: "Arena Season 5 Set",
	26: "Arena Season 6 Set",
	28: "Arena Season 7 Set",
	30: "Arena Season 8 Set",
	15: "Arathi Basin Set",
	9: "Ruins of Ahn'Qiraj Set",
	10: "Temple of Ahn'Qiraj Set",
	11: "Zul'Gurub Set"
};
var g_object_types = {
	9: "Book",
	3: "Container",
	"-5": "Footlocker",
	"-3": "Herb",
	"-4": "Mineral Vein",
	"-2": "Quest"
};

var g_reputation_standings = {
	0:"{term:hated}",
	1:"{term:hostile}",
	2:"{term:unfriendly}",
	3:"{term:neutral}",
	4:"{term:friendly}",
	5:"{term:honored}",
	6:"{term:revered}",
	7:"{term:exalted}"
};

var g_npc_classifications = {
	0: "{term:normal}",
	1: "{term:elite}",
	2: "{term:rare_elite}",
	3: "{term:boss}",
	4: "{term:rare}"
};
var g_quest_categories = {
	"-2": "Uncategorized",
	0: "Eastern Kingdoms",
	1: "Kalimdor",
	2: "Dungeons",
	3: "Raids",
	4: "Classes",
	5: "Professions",
	6: "Battlegrounds",
	7: "Miscellaneous",
	8: "Outland",
	9: "World Events",
	10: "Northrend"
};
var g_sides = {
	1: "{term:alliance}",
	2: "{term:horde}",
	3: "{term:both}"
};
var g_sources = {
	1: "Crafted",
	2: "Drop",
	3: "PvP",
	4: "Quest",
	5: "Vendor",
	6: "Trainer",
	7: "Discovery",
	8: "Redemption",
	9: "Talent",
	10: "Starter",
	11: "Event",
	12: "Achievement"
};
var g_sources_pvp = {
	1: "Arena",
	2: "Battleground",
	4: "World"
};
var g_zone_areas = {
	206: ["Norndir Preparation", "Dragonflayer Ascent", "Tyr's Terrace"],
	1196: ["Lower Pinnacle", "Upper Pinnacle"],
	1637: ["Orgrimmar", "The Cleft of Shadow"],
	3456: ["The Construct Quarter", "The Arachnid Quarter", "The Military Quarter", "The Plague Quarter", "The Lower Necropolis", "The Upper Necropolis"],
	4100: ["Stratholme City", "The Road to Stratholme"],
	4196: ["The Vestibules of Drak'Tharon", "Drak'Tharon Overlook"],
	4228: ["Band of Variance", "Band of Acceleration", "Band of Transmutation", "Band of Alignment"],
	4272: ["Unyielding Garrison", "Walk of the Makers"],
	4273: ["The Grand Approach ", "The Antechamber of Ulduar", "The Inner Sanctum of Ulduar", "The Prison of Yogg-Saron", "The Spark of Imagination", "The Mind's Eye"],
	4277: ["The Brood Pit", "Hadronox's Lair", "The Gilded Gate"],
	4395: ["Dalaran City", "The Underbelly"],
	4494: ["Ahn'kahet", "Level 2"],
	4722: ["The Argent Coliseum", "The Icy Depths"],
	4723: ["The Argent Coliseum", "The Icy Depths"],
	4812: ["The Lower Citadel", "The Rampart of Skulls", "Deathbringer's Rise", "The Frost Queen's Lair", "The Upper Reaches", "Royal Quarters", "The Frozen Throne", "Frostmourne"]
};
var g_zone_categories = {
	"-1": "Elsewhere in Azeroth",
	0: "Eastern Kingdoms",
	1: "Kalimdor",
	8: "Outland",
	10: "Northrend",
	2: "Dungeons",
	3: "Raids",
	6: "Battlegrounds",
	9: "Arenas"
};
var g_zone_instancetypes = {
	1: "Transit",
	2: "Dungeon",
	3: "Raid",
	4: "Battleground",
	5: "Dungeon",
	6: "Arena",
	7: "Raid",
	8: "Raid"
};
var g_zone_territories = {
	0: "Alliance",
	1: "Horde",
	2: "Contested",
	3: "Sanctuary",
	4: "PvP"
};
var g_title_categories = {
	0: "General",
	1: "PvP",
	2: "Reputation",
	3: "Dungeons & Raids",
	4: "Quests",
	5: "Professions",
	6: "World Events"
};
var g_holiday_categories = {
	1: "Holidays",
	2: "Recurring",
	3: "Player vs. Player",
	0: "Uncategorized"
};
var g_user_roles = {
	1: "Tester",
	2: "Administrator",
	3: "Editor",
	4: "Moderator",
	5: "Bureaucrat",
	6: "Developer",
	7: "VIP",
	8: "Blogger",
	9: "Premium",
	10: "Localizer",
	11: "Sales agent",
	12: "Screenshot manager",
	13: "Video manager"
};
var g_gem_colors = {
	1: "Meta",
	2: "Red",
	4: "Yellow",
	6: "Orange",
	8: "Blue",
	10: "Purple",
	12: "Green",
	14: "Prismatic"
};
var g_socket_names = {
	1: "Meta Socket",
	2: "Red Socket",
	4: "Yellow Socket",
	8: "Blue Socket",
	14: "Prismatic Socket"
};
var g_zones = {
	"1": "Dun Morogh",
	"3": "Badlands",
	"4": "Blasted Lands",
	"8": "Swamp of Sorrows",
	"10": "Duskwood",
	"11": "Wetlands",
	"12": "Elwynn Forest",
	"14": "Durotar",
	"15": "Dustwallow Marsh",
	"16": "Azshara",
	"17": "The Barrens",
	"19": "Zul'Gurub",
	"25": "Blackrock Mountain",
	"28": "Western Plaguelands",
	"33": "Stranglethorn Vale",
	"36": "Alterac Mountains",
	"38": "Loch Modan",
	"40": "Westfall",
	"41": "Deadwind Pass",
	"44": "Redridge Mountains",
	"45": "Arathi Highlands",
	"46": "Burning Steppes",
	"47": "The Hinterlands",
	"51": "Searing Gorge",
	"65": "Dragonblight",
	"66": "Zul'Drak",
	"67": "The Storm Peaks",
	"85": "Tirisfal Glades",
	"130": "Silverpine Forest",
	"133": "Gnomeregan",
	"139": "Eastern Plaguelands",
	"141": "Teldrassil",
	"148": "Darkshore",
	"206": "Utgarde Keep",
	"209": "Shadowfang Keep",
	"210": "Icecrown",
	"215": "Mulgore",
	"267": "Hillsbrad Foothills",
	"331": "Ashenvale",
	"357": "Feralas",
	"361": "Felwood",
	"394": "Grizzly Hills",
	"400": "Thousand Needles",
	"405": "Desolace",
	"406": "Stonetalon Mountains",
	"440": "Tanaris",
	"457": "The Veiled Sea",
	"490": "Un'Goro Crater",
	"491": "Razorfen Kraul",
	"493": "Moonglade",
	"495": "Howling Fjord",
	"618": "Winterspring",
	"717": "The Stockade",
	"718": "Wailing Caverns",
	"719": "Blackfathom Deeps",
	"722": "Razorfen Downs",
	"796": "Scarlet Monastery",
	"876": "GM Island",
	"978": "Zul'Farrak",
	"1196": "Utgarde Pinnacle",
	"1337": "Uldaman",
	"1377": "Silithus",
	"1417": "Sunken Temple",
	"1497": "Undercity",
	"1519": "Stormwind City",
	"1537": "Ironforge",
	"1581": "The Deadmines",
	"1583": "Blackrock Spire",
	"1584": "Blackrock Depths",
	"1637": "Orgrimmar",
	"1638": "Thunder Bluff",
	"1657": "Darnassus",
	"2017": "Stratholme",
	"2057": "Scholomance",
	"2100": "Maraudon",
	"2159": "Onyxia's Lair",
	"2257": "Deeprun Tram",
	"2366": "The Black Morass",
	"2367": "Old Hillsbrad Foothills",
	"2437": "Ragefire Chasm",
	"2557": "Dire Maul",
	"2562": "Karazhan",
	"2597": "Alterac Valley",
	"2677": "Blackwing Lair",
	"2717": "Molten Core",
	"2817": "Crystalsong Forest",
	"3277": "Warsong Gulch",
	"3358": "Arathi Basin",
	"3428": "Temple of Ahn'Qiraj",
	"3429": "Ruins of Ahn'Qiraj",
	"3430": "Eversong Woods",
	"3433": "Ghostlands",
	"3456": "Naxxramas",
	"3477": "Azjol-Nerub",
	"3483": "Hellfire Peninsula",
	"3487": "Silvermoon City",
	"3518": "Nagrand",
	"3519": "Terokkar Forest",
	"3520": "Shadowmoon Valley",
	"3521": "Zangarmarsh",
	"3522": "Blade's Edge Mountains",
	"3523": "Netherstorm",
	"3524": "Azuremyst Isle",
	"3525": "Bloodmyst Isle",
	"3537": "Borean Tundra",
	"3557": "The Exodar",
	"3562": "Hellfire Ramparts",
	"3606": "Hyjal Summit",
	"3607": "Serpentshrine Cavern",
	"3618": "Gruul's Lair",
	"3698": "Nagrand Arena",
	"3702": "Blade's Edge Arena",
	"3703": "Shattrath City",
	"3711": "Sholazar Basin",
	"3713": "The Blood Furnace",
	"3714": "The Shattered Halls",
	"3715": "The Steamvault",
	"3716": "The Underbog",
	"3717": "The Slave Pens",
	"3789": "Shadow Labyrinth",
	"3790": "Auchenai Crypts",
	"3791": "Sethekk Halls",
	"3792": "Mana-Tombs",
	"3805": "Zul'Aman",
	"3820": "Eye of the Storm",
	"3836": "Magtheridon's Lair",
	"3842": "The Eye",
	"3846": "The Arcatraz",
	"3847": "The Botanica",
	"3849": "The Mechanar",
	"3959": "Black Temple",
	"3968": "Ruins of Lordaeron",
	"4075": "Sunwell Plateau",
	"4080": "Isle of Quel'Danas",
	"4095": "Magisters' Terrace",
	"4100": "The Culling of Stratholme",
	"4120": "The Nexus",
	"4196": "Drak'Tharon Keep",
	"4197": "Wintergrasp",
	"4228": "The Oculus",
	"4264": "Halls of Stone",
	"4272": "Halls of Lightning",
	"4273": "Ulduar",
	"4298": "Plaguelands: The Scarlet Enclave",
	"4375": "Gundrak",
	"4378": "Dalaran Arena",
	"4384": "Strand of the Ancients",
	"4395": "Dalaran",
	"4406": "The Ring of Valor",
	"4415": "The Violet Hold",
	"4493": "The Obsidian Sanctum",
	"4494": "Ahn'kahet: The Old Kingdom",
	"4500": "The Eye of Eternity",
	"4603": "Vault of Archavon",
	"4710": "Isle of Conquest",
	"4722": "Trial of the Crusader",
	"4723": "Trial of the Champion",
	"4742": "Hrothgar's Landing",
	"4809": "The Forge of Souls",
	"4812": "Icecrown Citadel",
	"4813": "Pit of Saron",
	"4820": "Halls of Reflection",
	"4987": "The Ruby Sanctum"
};

var g_skill_categories = {
	"-6": "Companions",
	"-5": "Mounts",
	"-4": "Racial Traits",
	"6": "Weapon Skills",
	"8": "Armor Proficiencies",
	"9": "Secondary Skills",
	"10": "Languages",
	"11": "Professions"
};