var g_item_glyphs = {
	1: "{term:glyph_major}",
	2: "{term:glyph_minor}"
};
var g_item_slots = {
	1: "{term:head}",
	2: "{term:neck}",
	3: "{term:shoulder}",
	4: "{term:shirt}",
	5: "{term:chest}",
	6: "{term:waist}",
	7: "{term:legs}",
	8: "{term:feet}",
	9: "{term:wrist}",
	10: "{term:hands}",
	11: "{term:finger}",
	12: "{term:trinket}",
	13: "{term:onehand}",
	14: "{term:shield}",
	15: "{term:ranged}",
	16: "{term:back}",
	17: "{term:twohand}",
	18: "{term:bag}",
	19: "{term:tabard}",
	21: "{term:mainhand}",
	22: "{term:offhand}",
	23: "{term:heldinoffhand}",
	24: "{term:projectile}",
	25: "{term:thrown}",
	28: "{term:relic}"
};

var g_item_subclasses = {
	0: {
		0: "{term:consumable}",
		1: "{term:potion}",
		2: "{term:elixir}",
		3: "{term:flask}",
		4: "{term:scroll}",
		5: "{term:foodanddrink}",
		6: "{term:permenhancement}",
		"-3": "{term:tempenhancement}",
		7: "{term:bandage}",
		8: "{term:otherconsumables}"
	},
	1: {
		0: "{term:bag}",
		1: "{term:soulbag}",
		2: "{term:herbbag}",
		3: "{term:enchantingbag}",
		4: "{term:engineeringbag}",
		5: "{term:gembag}",
		6: "{term:miningbag}",
		7: "{term:leatherworkingbag}",
		8: "{term:inscriptionbag}"
	},
	2: {
		0: "{term:onehandedaxe}",
		1: "{term:twohandedaxe}",
		2: "{term:bow}",
		3: "{term:gun}",
		4: "{term:onehandedmace}",
		5: "{term:twohandedmace}",
		6: "{term:polearm}",
		7: "{term:onehandedsword}",
		8: "{term:twohandedsword}",
		10: "{term:staff}",
		13: "{term:fistweapon}",
		14: "{term:miscweapons}",
		15: "{term:dagger}",
		16: "{term:thrown}",
		18: "{term:crossbow}",
		19: "{term:wand}",
		20: "{term:fishingpole}"
	},
	3: {
		0: "{term:redgem}",
		1: "{term:bluegem}",
		2: "{term:yellowgem}",
		3: "{term:purplegem}",
		4: "{term:greengem}",
		5: "{term:orangegem}",
		6: "{term:metagem}",
		7: "{term:simplegem}",
		8: "{term:prismaticgem}"
	},
	4: {
		"-8": "{term:shirt}",
		"-7": "{term:tabard}",
		"-6": "{term:cloak}",
		"-5": "{term:offhandfrill}",
		"-4": "{term:trinket}",
		"-3": "{term:amulet}",
		"-2": "{term:ring}",
		0: "{term:miscarmor}",
		1: "{term:clotharmor}",
		2: "{term:leatherarmor}",
		3: "{term:mailarmor}",
		4: "{term:platearmor}",
		6: "{term:shield}",
		7: "{term:libram}",
		8: "{term:idol}",
		9: "{term:totem}",
		10: "{term:sigil}"
	},
	6: {
		2: "{term:arrow}",
		3: "{term:bullet}"
	},
	7: {
		1: "{term:part}",
		2: "{term:explosive}",
		3: "{term:device}",
		4: "{term:profession_jewelcrafting}",
		5: "{term:cloth}",
		6: "{term:leather}",
		7: "{term:metalandstone}",
		8: "{term:meat}",
		9: "{term:herb}",
		10: "{term:elemental}",
		12: "{term:profession_enchanting}",
		13: "{term:material}",
		14: "{term:armorenchantment}",
		15: "{term:weaponenchantment}",
		11: "{term:othertradegoods}"
	},
	9: {
		0: "{term:book}",
		1: "{term:leatherworkingpattern}",
		2: "{term:tailoringpattern}",
		3: "{term:engineeringschematic}",
		4: "{term:blacksmithingplans}",
		5: "{term:cookingrecipe}",
		6: "{term:alchemyrecipe}",
		7: "{term:firstaidbook}",
		8: "{term:enchantingformula}",
		9: "{term:fishingbook}",
		10: "{term:jewelcraftingdesign}",
		11: "{term:inscriptiontechnique}"
	},
	11: {
		2: "{term:quiver}",
		3: "{term:ammopouch}"
	},
	15: {
		"-7": "{term:flyingmount}",
		"-6": "{term:combatpet}",
		"-2": "{term:armortoken}",
		0: "{term:junk}",
		1: "{term:reagent}",
		2: "{term:companion}",
		3: "{term:holiday}",
		4: "{term:othermiscellaneous}",
		5: "{term:mount}"
	},
	16: {
		6: "{term:deathknightglyph}",
		11: "{term:druidglyph}",
		3: "{term:hunterglyph}",
		8: "{term:mageglyph}",
		2: "{term:paladinglyph}",
		5: "{term:priestglyph}",
		4: "{term:rogueglyph}",
		7: "{term:shamanglyph}",
		9: "{term:warlockglyph}",
		1: "{term:warriorglyph}"
	}
};
var g_item_subsubclasses = {
	0: {
		2: {
			1: "{term:battleelixir}",
			2: "{term:guardianelixir}"
		}
	}
};

var g_itemset_types = {
	1: "{term:cloth}",
	2: "{term:leather}",
	3: "{term:mail}",
	4: "{term:plate}",
	5: "{term:dagger}",
	6: "{term:ring}",
	7: "{term:fistweapon}",
	8: "{term:onehandedaxe}",
	9: "{term:onehandedmace}",
	10: "{term:onehandedsword}",
	11: "{term:trinket}",
	12: "{term:amulet}"
};
var g_itemset_notes = {
	1: "{term:dungeonset1}",
	2: "{term:dungeonset2}",
	14: "{term:dungeonset3}",
	3: "{term:tier1raidset}",
	4: "{term:tier2raidset}",
	5: "{term:tier3raidset}",
	12: "{term:tier4raidset}",
	13: "{term:tier5raidset}",
	18: "{term:tier6raidset}",
	23: "{term:tier7raidset}",
	25: "{term:tier8raidset}",
	27: "{term:tier9raidset}",
	29: "{term:tier10raidset}",
	6: "{term:level60pvprareset}",
	7: "{term:level60pvpraresetold}",
	8: "{term:level60pvpepicset}",
	16: "{term:level70pvprareset}",
	21: "{term:level70pvprareset2}",
	17: "{term:arenaseason1set}",
	19: "{term:arenaseason2set}",
	20: "{term:arenaseason3set}",
	22: "{term:arenaseason4set}",
	24: "{term:arenaseason5set}",
	26: "{term:arenaseason6set}",
	28: "{term:arenaseason7set}",
	30: "{term:arenaseason8set}",
	15: "{term:arathibasinset}",
	9: "{term:ruinsofahnqirajset}",
	10: "{term:templeofahnqirajset}",
	11: "{term:zulgurubset}"
};
var g_object_types = {
	9: "{term:book}",
	3: "{term:container}",
	"-5": "{term:footlocker}",
	"-3": "{term:herb}",
	"-4": "{term:mineralvein}",
	"-2": "{term:quest}"
};

var g_reputation_standings = {
	0:"{term:hated}",
	1:"{term:hostile}",
	2:"{term:unfriendly}",
	3:"{term:neutral}",
	4:"{term:friendly}",
	5:"{term:honored}",
	6:"{term:revered}",
	7:"{term:exalted}"
};

var g_npc_classifications = {
	0: "{term:normal}",
	1: "{term:elite}",
	2: "{term:rareelite}",
	3: "{term:boss}",
	4: "{term:rare}"
};
var g_quest_categories = {
	"-2": "{term:uncategorized}",
	0: "Eastern Kingdoms",
	1: "Kalimdor",
	2: "{term:dungeons}",
	3: "{term:raids}",
	4: "{term:classes}",
	5: "{term:professions}",
	6: "{term:battlegrounds}",
	7: "{term:miscellaneous}",
	8: "Outland",
	9: "{term:worldevents}",
	10: "Northrend"
};
var g_sides = {
	1: "{term:alliance}",
	2: "{term:horde}",
	3: "{term:both}"
};
var g_sources = {
	1: "{term:crafted}",
	2: "{term:drop}",
	3: "{term:pvp}",
	4: "{term:quest}",
	5: "{term:vendor}",
	6: "{term:trainer}",
	7: "{term:discovery}",
	8: "{term:redemption}",
	9: "{term:talent}",
	10: "{term:starter}",
	11: "{term:event}",
	12: "{term:achievement}"
};
var g_sources_pvp = {
	1: "{term:arena}",
	2: "{term:battleground}",
	4: "{term:world}"
};
var g_zone_areas = {
	206: ["{term:norndirpreparation}", "{term:dragonflayerascent}", "{term:tyrsterrace}"],
	1196: ["{term:lowerpinnacle}", "{term:upperpinnacle}"],
	1637: ["{term:orgrimmar}", "{term:thecleftofshadow}"],
	3456: ["{term:theconstructquarter}", "{term:thearachnidquarter}", "{term:themilitaryquarter}", "{term:theplaguequarter}", "{term:thelowernecropolis}", "{term:theuppernecropolis}"],
	4100: ["{term:stratholmecity}", "{term:theroadtostratholme}"],
	4196: ["{term:thevestibulesofdraktharon}", "{term:draktharonoverlook}"],
	4228: ["{term:bandofvariance}", "{term:bandofacceleration}", "{term:bandoftransmutation}", "{term:bandofalignment}"],
	4272: ["{term:unyieldinggarrison}", "{term:walkofthemakers}"],
	4273: ["{term:thegrandapproach}", "{term:theantechamberofulduar}", "{term:theinnersanctumofulduar}", "{term:theprisonofyoggsaron}", "{term:thesparkofimagination}", "{term:themindseye}"],
	4277: ["{term:thebroodpit}", "{term:hadronoxslair}", "{term:thegildedgate}"],
	4395: ["{term:dalarancity}", "{term:theunderbelly}"],
	4494: ["{term:ahnkahet}", "{term:level2}"],
	4722: ["{term:theargentcoliseum}", "{term:theicydepths}"],
	4723: ["{term:theargentcoliseum}", "{term:theicydepths}"],
	4812: ["{term:thelowercitadel}", "{term:therampartofskulls}", "{term:deathbringersrise}", "{term:thefrostqueenslair}", "{term:theupperreaches}", "{term:royalquarters}", "{term:thefrozenthrone}", "{term:frostmourne}"]
};
var g_zone_categories = {
	"-1": "{term:elsewhereinazeroth_stc}",
	0: "Eastern Kingdoms",
	1: "Kalimdor",
	8: "Outland",
	10: "Northrend",
	2: "{term:dungeons}",
	3: "{term:raids}",
	6: "{term:battlegrounds}",
	9: "{term:arenas}"
};
var g_zone_instancetypes = {
	1: "{term:transit}",
	2: "{term:dungeon}",
	3: "{term:raid}",
	4: "{term:battleground}",
	5: "{term:dungeon}",
	6: "{term:arena}",
	7: "{term:raid}",
	8: "{term:raid}"
};
var g_zone_territories = {
	0: "{term:alliance}",
	1: "{term:horde}",
	2: "{term:contested}",
	3: "{term:sanctuary}",
	4: "{term:pvp}"
};
var g_title_categories = {
	0: "{term:general}",
	1: "{term:pvp}",
	2: "{term:reputation}",
	3: "{term:dungeonsandraids}",
	4: "{term:quests}",
	5: "{term:professions}",
	6: "{term:worldevents}"
};
var g_holiday_categories = {
	1: "{term:holidays}",
	2: "{term:recurring}",
	3: "{term:playervsplayer_stc}",
	0: "{term:uncategorized}"
};
var g_user_roles = {
	1: "{term:moderator}",
	2: "{term:gamemaster}",
	3: "{term:role_administrator}",
	4: "{term:role_developer}",
	5: "{term:tester}",
    6: "{term:vip}"
};
var g_gem_colors = {
	1: "{term:meta}",
	2: "{term:red}",
	4: "{term:yellow}",
	6: "{term:orange}",
	8: "{term:blue}",
	10: "{term:purple}",
	12: "{term:green}",
	14: "{term:prismatic}"
};
var g_socket_names = {
	1: "{term:metasocket}",
	2: "{term:redsocket}",
	4: "{term:yellowsocket}",
	8: "{term:bluesocket}",
	14: "{term:prismaticsocket}"
};
var g_zones = {
	"1": "Dun Morogh",
	"3": "Badlands",
	"4": "Blasted Lands",
	"8": "Swamp of Sorrows",
	"10": "Duskwood",
	"11": "Wetlands",
	"12": "Elwynn Forest",
	"14": "Durotar",
	"15": "Dustwallow Marsh",
	"16": "Azshara",
	"17": "The Barrens",
	"19": "Zul'Gurub",
	"25": "Blackrock Mountain",
	"28": "Western Plaguelands",
	"33": "Stranglethorn Vale",
	"36": "Alterac Mountains",
	"38": "Loch Modan",
	"40": "Westfall",
	"41": "Deadwind Pass",
	"44": "Redridge Mountains",
	"45": "Arathi Highlands",
	"46": "Burning Steppes",
	"47": "The Hinterlands",
	"51": "Searing Gorge",
	"65": "Dragonblight",
	"66": "Zul'Drak",
	"67": "The Storm Peaks",
	"85": "Tirisfal Glades",
	"130": "Silverpine Forest",
	"133": "Gnomeregan",
	"139": "Eastern Plaguelands",
	"141": "Teldrassil",
	"148": "Darkshore",
	"206": "Utgarde Keep",
	"209": "Shadowfang Keep",
	"210": "Icecrown",
	"215": "Mulgore",
	"267": "Hillsbrad Foothills",
	"331": "Ashenvale",
	"357": "Feralas",
	"361": "Felwood",
	"394": "Grizzly Hills",
	"400": "Thousand Needles",
	"405": "Desolace",
	"406": "Stonetalon Mountains",
	"440": "Tanaris",
	"457": "The Veiled Sea",
	"490": "Un'Goro Crater",
	"491": "Razorfen Kraul",
	"493": "Moonglade",
	"495": "Howling Fjord",
	"618": "Winterspring",
	"717": "The Stockade",
	"718": "Wailing Caverns",
	"719": "Blackfathom Deeps",
	"722": "Razorfen Downs",
	"796": "Scarlet Monastery",
	"876": "GM Island",
	"978": "Zul'Farrak",
	"1196": "Utgarde Pinnacle",
	"1337": "Uldaman",
	"1377": "Silithus",
	"1417": "Sunken Temple",
	"1497": "Undercity",
	"1519": "Stormwind City",
	"1537": "Ironforge",
	"1581": "The Deadmines",
	"1583": "Blackrock Spire",
	"1584": "Blackrock Depths",
	"1637": "{term:orgrimmar}",
	"1638": "Thunder Bluff",
	"1657": "Darnassus",
	"2017": "Stratholme",
	"2057": "Scholomance",
	"2100": "Maraudon",
	"2159": "Onyxia's Lair",
	"2257": "Deeprun Tram",
	"2366": "The Black Morass",
	"2367": "Old Hillsbrad Foothills",
	"2437": "Ragefire Chasm",
	"2557": "Dire Maul",
	"2562": "Karazhan",
	"2597": "Alterac Valley",
	"2677": "Blackwing Lair",
	"2717": "Molten Core",
	"2817": "Crystalsong Forest",
	"3277": "Warsong Gulch",
	"3358": "Arathi Basin",
	"3428": "Temple of Ahn'Qiraj",
	"3429": "Ruins of Ahn'Qiraj",
	"3430": "Eversong Woods",
	"3433": "Ghostlands",
	"3456": "Naxxramas",
	"3477": "Azjol-Nerub",
	"3483": "Hellfire Peninsula",
	"3487": "Silvermoon City",
	"3518": "Nagrand",
	"3519": "Terokkar Forest",
	"3520": "Shadowmoon Valley",
	"3521": "Zangarmarsh",
	"3522": "Blade's Edge Mountains",
	"3523": "Netherstorm",
	"3524": "Azuremyst Isle",
	"3525": "Bloodmyst Isle",
	"3537": "Borean Tundra",
	"3557": "The Exodar",
	"3562": "Hellfire Ramparts",
	"3606": "Hyjal Summit",
	"3607": "Serpentshrine Cavern",
	"3618": "Gruul's Lair",
	"3698": "Nagrand Arena",
	"3702": "Blade's Edge Arena",
	"3703": "Shattrath City",
	"3711": "Sholazar Basin",
	"3713": "The Blood Furnace",
	"3714": "The Shattered Halls",
	"3715": "The Steamvault",
	"3716": "The Underbog",
	"3717": "The Slave Pens",
	"3789": "Shadow Labyrinth",
	"3790": "Auchenai Crypts",
	"3791": "Sethekk Halls",
	"3792": "Mana-Tombs",
	"3805": "Zul'Aman",
	"3820": "Eye of the Storm",
	"3836": "Magtheridon's Lair",
	"3842": "The Eye",
	"3846": "The Arcatraz",
	"3847": "The Botanica",
	"3849": "The Mechanar",
	"3959": "Black Temple",
	"3968": "Ruins of Lordaeron",
	"4075": "Sunwell Plateau",
	"4080": "Isle of Quel'Danas",
	"4095": "Magisters' Terrace",
	"4100": "The Culling of Stratholme",
	"4120": "The Nexus",
	"4196": "Drak'Tharon Keep",
	"4197": "Wintergrasp",
	"4228": "{term:theoculus}",
	"4264": "Halls of Stone",
	"4272": "Halls of Lightning",
	"4273": "Ulduar",
	"4298": "Plaguelands: The Scarlet Enclave",
	"4375": "Gundrak",
	"4378": "Dalaran Arena",
	"4384": "Strand of the Ancients",
	"4395": "Dalaran",
	"4406": "The Ring of Valor",
	"4415": "The Violet Hold",
	"4493": "The Obsidian Sanctum",
	"4494": "Ahn'kahet: The Old Kingdom",
	"4500": "The Eye of Eternity",
	"4603": "Vault of Archavon",
	"4710": "Isle of Conquest",
	"4722": "Trial of the Crusader",
	"4723": "Trial of the Champion",
	"4742": "Hrothgar's Landing",
	"4809": "The Forge of Souls",
	"4812": "Icecrown Citadel",
	"4813": "Pit of Saron",
	"4820": "Halls of Reflection",
	"4987": "The Ruby Sanctum"
};

var g_skill_categories = {
	"-6": "{term:companions}",
	"-5": "{term:mounts}",
	"-4": "{term:racialtraits}",
	"6": "{term:weaponskills}",
	"8": "{term:armorproficiencies}",
	"9": "{term:secondaryskills}",
	"10": "{term:languages}",
	"11": "{term:professions}"
};
