<?php

/** WEB NUMBER 2.0
 * WebNumber is a special digital value representaion
 * that allows to store numeric values as safe strings.
 *
 * WN Keys are used to encrypt an integer
 * from WN and back.
 *
 * A single WN Key is generated by an attached javascript
 * code piece.
 */

/*
javascript:
function generate_key()
{
	function rnd(n) { return Math.floor(Math.random() * 10000000000000 % n) }

	var a = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890_-';
	var b = a.split('');
	var c = '';
	var k = -1;
	var l = {};
	l[k] = true;

	for(var d = 0; d < b.length; d++)
	{
		while(l[k] == true)
			k = rnd(b.length);

		c += b[k];
		l[k] = 1;
		b[k] = null;
	}

	prompt("Key with " + c.length + " of " + b.length + " symbols", (rnd(2) ? "+" : "-") + c);	
}
generate_key();
*/

enum(array( // WNKeys - TODO: move to config
	'WN_KEY_WEBUSERAUTH'	=> '+TjS85yEgpx97hDwXUoF2rGVH_J-NfnmAZKQM3OPC6zIl10isbavLeWkcYdR4qBtu',
	'WN_KEY_WEBUSERID'		=> '+RQGbSW7Yqyz6fTNAUrI3BE-Zt0FoiMh8ke1_sCmLDwOjgXda9JxH2KcPVu4l5vnp',
	'WN_KEY_BACKURL'		=> '-0a4PDfKj-riFwEW2ge5uLMl6B3vhp7OZUkodxntIcTC8bzSyHRqNXQAG9mYJ_s1V',
));

/** CORE FUNCTIONS **/

function wn_create($value, $key)
{
	$doReverse = substr($key, 0, 1) != '+';

	$key = substr($key, 1);
	$len = strlen($key);

	$result = '';

	do
	{
		$mod = $value % $len;
		$value = floor($value / $len);

		$symbol = $key{$mod};

		$result = $symbol.$result;
	}
	while($value > 0);

	return $doReverse ? strrev($result) : $result;
}

function wn_destroy($value, $key)
{
	$result = 0;

	if(substr($key, 0, 1) != '+')
		$value = strrev($value);

	$key = substr($key, 1);
	$len = strlen($key);

	for($i = 0; $i < strlen($value); $i++)
	{
		$symbol = $value{$i};
		$symbol_value = strpos($key, $symbol);

		if($symbol_value === false)
			return 0;

		$result *= $len;
		$result += $symbol_value;
	}

	return $result;
}

function wn_screate($value, $origkey)
{
	$hexed = hex($value);
	$doReverse = substr($origkey, 0, 1) != '+';

	$size = strlen(wn_create(99999999, $origkey));

	$zeroSymbol = wn_valuesymbol(0, $origkey);

	$result = '';

	for($i = 0; $i < strlen($hexed); $i += 8)
		$result .= str_pad(wn_create(substr($hexed, $i, 8), $origkey), $size, $zeroSymbol, STR_PAD_LEFT);

	return str_pad($size, 2, '0', STR_PAD_LEFT).($doReverse ? strrev($result) : $result);
}

function wn_sdestroy($value, $origkey)
{
	$size = intval(substr($value, 0, 2));
	$value = substr($value, 2);

	if(substr($origkey, 0, 1) != '+')
		$value = strrev($value);

	$result = '';

	for($i = 0; $i < strlen($value); $i += $size)
		$result .= str_pad(wn_destroy(substr($value, $i, $size), $origkey), 8, '0', STR_PAD_LEFT);

	return unhex($result);
}

/** HELPER FUNCTIONS **/

function wn_valuesymbol($value, $key)
{
	return substr($key, $value+1, 1);
}

?>