<?php

require_once('pdev/AdminEnums.php');

class AdminTermsPage extends GenericPage
{
	public function __construct()
	{
		parent::__construct();
	}

	public function finalize()
	{
		$terms = DB::World()->Select('SELECT textid, flags, '.AllLocales('content').', comments FROM ?_terms ORDER BY textid');

		$files = array();
		foreach(Main::$locales as $loc)
			$files[$loc] = "<?php\n// THIS FILE IS AUTO GENERATED FROM DATABASE DATA!\n// DO NOT EDIT THIS FILE!\n\nglobal \$_TERMS;\n\$_TERMS = array(\n";

		foreach($terms as $term)
		{
			foreach(Main::$locales as $loc)
			{
				if(preg_match('/[^\w\d]/', $term['textid']))
					continue;

				$text = empty($term['content_loc'.$loc]) ? ('['.$term['content_loc0'].']') : $term['content_loc'.$loc];
				if(!($term['flags'] & TERMFLAG_CONTAINS_HTML))
					$text = htmlspecialchars($text);
				$files[$loc] .= "\t'".$term['textid']."' => '".strtr($text, array('\''=>'\\\'','\\'=>'\\\\'))."',\n";
			}
		}

		foreach(Main::$locales as $loc)
		{
			$files[$loc] .= ");\n\n?>";
			file_put_contents('./cache/locale.'.Main::$languages[$loc].'.php', $files[$loc]);
		}
	}
}

?>