<?php

$_CONFIG = array(
	'WEBSITE_NAME'		=> 'AoWoW',
	'DEFAULT_LOCALE'	=> 0,

	'U_GROUP_EDITORS'		=> U_GROUP_STAFFERS,
	'U_GROUP_LINKS_ALLOWED'	=> U_GROUP_STAFFERS,
	'U_GROUP_SEE_ADMIN_TAG'	=> U_GROUP_SUPREME,
);

?>